// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rechargebonuspb/rechargebonus.proto

package rechargebonuspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RechargeBonusConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartAt       int64                  `protobuf:"varint,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         int64                  `protobuf:"varint,3,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	UnlockConds   int64                  `protobuf:"varint,5,opt,name=unlock_conds,json=unlockConds,proto3" json:"unlock_conds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeBonusConfig) Reset() {
	*x = RechargeBonusConfig{}
	mi := &file_rechargebonuspb_rechargebonus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeBonusConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeBonusConfig) ProtoMessage() {}

func (x *RechargeBonusConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rechargebonuspb_rechargebonus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeBonusConfig.ProtoReflect.Descriptor instead.
func (*RechargeBonusConfig) Descriptor() ([]byte, []int) {
	return file_rechargebonuspb_rechargebonus_proto_rawDescGZIP(), []int{0}
}

func (x *RechargeBonusConfig) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RechargeBonusConfig) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *RechargeBonusConfig) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *RechargeBonusConfig) GetUnlockConds() int64 {
	if x != nil {
		return x.UnlockConds
	}
	return 0
}

type RangeToRatio struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RechargeRangeMin int64                  `protobuf:"varint,1,opt,name=recharge_range_min,json=rechargeRangeMin,proto3" json:"recharge_range_min,omitempty"`
	RechargeRangeMax int64                  `protobuf:"varint,2,opt,name=recharge_range_max,json=rechargeRangeMax,proto3" json:"recharge_range_max,omitempty"`
	ReturnRatio      int64                  `protobuf:"varint,3,opt,name=return_ratio,json=returnRatio,proto3" json:"return_ratio,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RangeToRatio) Reset() {
	*x = RangeToRatio{}
	mi := &file_rechargebonuspb_rechargebonus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeToRatio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeToRatio) ProtoMessage() {}

func (x *RangeToRatio) ProtoReflect() protoreflect.Message {
	mi := &file_rechargebonuspb_rechargebonus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeToRatio.ProtoReflect.Descriptor instead.
func (*RangeToRatio) Descriptor() ([]byte, []int) {
	return file_rechargebonuspb_rechargebonus_proto_rawDescGZIP(), []int{1}
}

func (x *RangeToRatio) GetRechargeRangeMin() int64 {
	if x != nil {
		return x.RechargeRangeMin
	}
	return 0
}

func (x *RangeToRatio) GetRechargeRangeMax() int64 {
	if x != nil {
		return x.RechargeRangeMax
	}
	return 0
}

func (x *RangeToRatio) GetReturnRatio() int64 {
	if x != nil {
		return x.ReturnRatio
	}
	return 0
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_rechargebonuspb_rechargebonus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rechargebonuspb_rechargebonus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_rechargebonuspb_rechargebonus_proto_rawDescGZIP(), []int{2}
}

type GetConfigReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Configs       []*RechargeBonusConfig `protobuf:"bytes,2,rep,name=configs,proto3" json:"configs,omitempty"`
	Ranges        []*RangeToRatio        `protobuf:"bytes,3,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigReply) Reset() {
	*x = GetConfigReply{}
	mi := &file_rechargebonuspb_rechargebonus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigReply) ProtoMessage() {}

func (x *GetConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_rechargebonuspb_rechargebonus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigReply.ProtoReflect.Descriptor instead.
func (*GetConfigReply) Descriptor() ([]byte, []int) {
	return file_rechargebonuspb_rechargebonus_proto_rawDescGZIP(), []int{3}
}

func (x *GetConfigReply) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetConfigReply) GetConfigs() []*RechargeBonusConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *GetConfigReply) GetRanges() []*RangeToRatio {
	if x != nil {
		return x.Ranges
	}
	return nil
}

type GetPlayerDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerDataRequest) Reset() {
	*x = GetPlayerDataRequest{}
	mi := &file_rechargebonuspb_rechargebonus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerDataRequest) ProtoMessage() {}

func (x *GetPlayerDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rechargebonuspb_rechargebonus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerDataRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerDataRequest) Descriptor() ([]byte, []int) {
	return file_rechargebonuspb_rechargebonus_proto_rawDescGZIP(), []int{4}
}

type GetPlayerDataReply struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalRechargeAmount int64                  `protobuf:"varint,1,opt,name=total_recharge_amount,json=totalRechargeAmount,proto3" json:"total_recharge_amount,omitempty"`
	TotalReturnAmount   int64                  `protobuf:"varint,2,opt,name=total_return_amount,json=totalReturnAmount,proto3" json:"total_return_amount,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetPlayerDataReply) Reset() {
	*x = GetPlayerDataReply{}
	mi := &file_rechargebonuspb_rechargebonus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerDataReply) ProtoMessage() {}

func (x *GetPlayerDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_rechargebonuspb_rechargebonus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerDataReply.ProtoReflect.Descriptor instead.
func (*GetPlayerDataReply) Descriptor() ([]byte, []int) {
	return file_rechargebonuspb_rechargebonus_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlayerDataReply) GetTotalRechargeAmount() int64 {
	if x != nil {
		return x.TotalRechargeAmount
	}
	return 0
}

func (x *GetPlayerDataReply) GetTotalReturnAmount() int64 {
	if x != nil {
		return x.TotalReturnAmount
	}
	return 0
}

var File_rechargebonuspb_rechargebonus_proto protoreflect.FileDescriptor

const file_rechargebonuspb_rechargebonus_proto_rawDesc = "" +
	"\n" +
	"#rechargebonuspb/rechargebonus.proto\x12\x16gamepb.rechargebonuspb\"z\n" +
	"\x13RechargeBonusConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bstart_at\x18\x02 \x01(\x03R\astartAt\x12\x15\n" +
	"\x06end_at\x18\x03 \x01(\x03R\x05endAt\x12!\n" +
	"\funlock_conds\x18\x05 \x01(\x03R\vunlockConds\"\x8d\x01\n" +
	"\fRangeToRatio\x12,\n" +
	"\x12recharge_range_min\x18\x01 \x01(\x03R\x10rechargeRangeMin\x12,\n" +
	"\x12recharge_range_max\x18\x02 \x01(\x03R\x10rechargeRangeMax\x12!\n" +
	"\freturn_ratio\x18\x03 \x01(\x03R\vreturnRatio\"\x12\n" +
	"\x10GetConfigRequest\"\xb2\x01\n" +
	"\x0eGetConfigReply\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12E\n" +
	"\aconfigs\x18\x02 \x03(\v2+.gamepb.rechargebonuspb.RechargeBonusConfigR\aconfigs\x12<\n" +
	"\x06ranges\x18\x03 \x03(\v2$.gamepb.rechargebonuspb.RangeToRatioR\x06ranges\"\x16\n" +
	"\x14GetPlayerDataRequest\"x\n" +
	"\x12GetPlayerDataReply\x122\n" +
	"\x15total_recharge_amount\x18\x01 \x01(\x03R\x13totalRechargeAmount\x12.\n" +
	"\x13total_return_amount\x18\x02 \x01(\x03R\x11totalReturnAmountB#Z!qq-farm-bot/proto/rechargebonuspbb\x06proto3"

var (
	file_rechargebonuspb_rechargebonus_proto_rawDescOnce sync.Once
	file_rechargebonuspb_rechargebonus_proto_rawDescData []byte
)

func file_rechargebonuspb_rechargebonus_proto_rawDescGZIP() []byte {
	file_rechargebonuspb_rechargebonus_proto_rawDescOnce.Do(func() {
		file_rechargebonuspb_rechargebonus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rechargebonuspb_rechargebonus_proto_rawDesc), len(file_rechargebonuspb_rechargebonus_proto_rawDesc)))
	})
	return file_rechargebonuspb_rechargebonus_proto_rawDescData
}

var file_rechargebonuspb_rechargebonus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rechargebonuspb_rechargebonus_proto_goTypes = []any{
	(*RechargeBonusConfig)(nil),  // 0: gamepb.rechargebonuspb.RechargeBonusConfig
	(*RangeToRatio)(nil),         // 1: gamepb.rechargebonuspb.RangeToRatio
	(*GetConfigRequest)(nil),     // 2: gamepb.rechargebonuspb.GetConfigRequest
	(*GetConfigReply)(nil),       // 3: gamepb.rechargebonuspb.GetConfigReply
	(*GetPlayerDataRequest)(nil), // 4: gamepb.rechargebonuspb.GetPlayerDataRequest
	(*GetPlayerDataReply)(nil),   // 5: gamepb.rechargebonuspb.GetPlayerDataReply
}
var file_rechargebonuspb_rechargebonus_proto_depIdxs = []int32{
	0, // 0: gamepb.rechargebonuspb.GetConfigReply.configs:type_name -> gamepb.rechargebonuspb.RechargeBonusConfig
	1, // 1: gamepb.rechargebonuspb.GetConfigReply.ranges:type_name -> gamepb.rechargebonuspb.RangeToRatio
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rechargebonuspb_rechargebonus_proto_init() }
func file_rechargebonuspb_rechargebonus_proto_init() {
	if File_rechargebonuspb_rechargebonus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rechargebonuspb_rechargebonus_proto_rawDesc), len(file_rechargebonuspb_rechargebonus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rechargebonuspb_rechargebonus_proto_goTypes,
		DependencyIndexes: file_rechargebonuspb_rechargebonus_proto_depIdxs,
		MessageInfos:      file_rechargebonuspb_rechargebonus_proto_msgTypes,
	}.Build()
	File_rechargebonuspb_rechargebonus_proto = out.File
	file_rechargebonuspb_rechargebonus_proto_goTypes = nil
	file_rechargebonuspb_rechargebonus_proto_depIdxs = nil
}
