// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: taskpb/task.proto

package taskpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	corepb "qq-farm-bot/proto/corepb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Progress      int64          `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	IsClaimed     bool           `protobuf:"varint,3,opt,name=is_claimed,json=isClaimed,proto3" json:"is_claimed,omitempty"`
	IsUnlocked    bool           `protobuf:"varint,4,opt,name=is_unlocked,json=isUnlocked,proto3" json:"is_unlocked,omitempty"`
	Rewards       []*corepb.Item `protobuf:"bytes,5,rep,name=rewards,proto3" json:"rewards,omitempty"`
	TotalProgress int64          `protobuf:"varint,6,opt,name=total_progress,json=totalProgress,proto3" json:"total_progress,omitempty"`
	ShareMultiple int64          `protobuf:"varint,7,opt,name=share_multiple,json=shareMultiple,proto3" json:"share_multiple,omitempty"`
	Params        []string       `protobuf:"bytes,8,rep,name=params,proto3" json:"params,omitempty"`
	Desc          string         `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc,omitempty"`
	TaskType      int32          `protobuf:"varint,10,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Group         int64          `protobuf:"varint,11,opt,name=group,proto3" json:"group,omitempty"`
	CondType      int64          `protobuf:"varint,12,opt,name=cond_type,json=condType,proto3" json:"cond_type,omitempty"`
	IsShowText    int64          `protobuf:"varint,13,opt,name=is_show_text,json=isShowText,proto3" json:"is_show_text,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_task_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_task_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_taskpb_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Task) GetIsClaimed() bool {
	if x != nil {
		return x.IsClaimed
	}
	return false
}

func (x *Task) GetIsUnlocked() bool {
	if x != nil {
		return x.IsUnlocked
	}
	return false
}

func (x *Task) GetRewards() []*corepb.Item {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *Task) GetTotalProgress() int64 {
	if x != nil {
		return x.TotalProgress
	}
	return 0
}

func (x *Task) GetShareMultiple() int64 {
	if x != nil {
		return x.ShareMultiple
	}
	return 0
}

func (x *Task) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Task) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Task) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *Task) GetGroup() int64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Task) GetCondType() int64 {
	if x != nil {
		return x.CondType
	}
	return 0
}

func (x *Task) GetIsShowText() int64 {
	if x != nil {
		return x.IsShowText
	}
	return 0
}

type Active struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status int32          `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Items  []*corepb.Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Active) Reset() {
	*x = Active{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_task_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Active) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Active) ProtoMessage() {}

func (x *Active) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_task_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Active.ProtoReflect.Descriptor instead.
func (*Active) Descriptor() ([]byte, []int) {
	return file_taskpb_task_proto_rawDescGZIP(), []int{1}
}

func (x *Active) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Active) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Active) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type TaskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GrowthTasks []*Task   `protobuf:"bytes,1,rep,name=growth_tasks,json=growthTasks,proto3" json:"growth_tasks,omitempty"`
	DailyTasks  []*Task   `protobuf:"bytes,2,rep,name=daily_tasks,json=dailyTasks,proto3" json:"daily_tasks,omitempty"`
	Tasks       []*Task   `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Actives     []*Active `protobuf:"bytes,4,rep,name=actives,proto3" json:"actives,omitempty"`
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_task_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_task_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_taskpb_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskInfo) GetGrowthTasks() []*Task {
	if x != nil {
		return x.GrowthTasks
	}
	return nil
}

func (x *TaskInfo) GetDailyTasks() []*Task {
	if x != nil {
		return x.DailyTasks
	}
	return nil
}

func (x *TaskInfo) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *TaskInfo) GetActives() []*Active {
	if x != nil {
		return x.Actives
	}
	return nil
}

type TaskInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskInfoRequest) Reset() {
	*x = TaskInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_task_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoRequest) ProtoMessage() {}

func (x *TaskInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_task_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoRequest.ProtoReflect.Descriptor instead.
func (*TaskInfoRequest) Descriptor() ([]byte, []int) {
	return file_taskpb_task_proto_rawDescGZIP(), []int{3}
}

type TaskInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskInfo *TaskInfo `protobuf:"bytes,1,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`
}

func (x *TaskInfoReply) Reset() {
	*x = TaskInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_task_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoReply) ProtoMessage() {}

func (x *TaskInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_task_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoReply.ProtoReflect.Descriptor instead.
func (*TaskInfoReply) Descriptor() ([]byte, []int) {
	return file_taskpb_task_proto_rawDescGZIP(), []int{4}
}

func (x *TaskInfoReply) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

type ClaimTaskRewardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DoShared bool  `protobuf:"varint,2,opt,name=do_shared,json=doShared,proto3" json:"do_shared,omitempty"`
}

func (x *ClaimTaskRewardRequest) Reset() {
	*x = ClaimTaskRewardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_task_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimTaskRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskRewardRequest) ProtoMessage() {}

func (x *ClaimTaskRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_task_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskRewardRequest.ProtoReflect.Descriptor instead.
func (*ClaimTaskRewardRequest) Descriptor() ([]byte, []int) {
	return file_taskpb_task_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimTaskRewardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClaimTaskRewardRequest) GetDoShared() bool {
	if x != nil {
		return x.DoShared
	}
	return false
}

type ClaimTaskRewardReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items            []*corepb.Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TaskInfo         *TaskInfo      `protobuf:"bytes,2,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`
	CompensatedItems []*corepb.Item `protobuf:"bytes,3,rep,name=compensated_items,json=compensatedItems,proto3" json:"compensated_items,omitempty"`
}

func (x *ClaimTaskRewardReply) Reset() {
	*x = ClaimTaskRewardReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_task_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimTaskRewardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskRewardReply) ProtoMessage() {}

func (x *ClaimTaskRewardReply) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_task_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskRewardReply.ProtoReflect.Descriptor instead.
func (*ClaimTaskRewardReply) Descriptor() ([]byte, []int) {
	return file_taskpb_task_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimTaskRewardReply) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ClaimTaskRewardReply) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

func (x *ClaimTaskRewardReply) GetCompensatedItems() []*corepb.Item {
	if x != nil {
		return x.CompensatedItems
	}
	return nil
}

type BatchClaimTaskRewardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids      []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	DoShared bool    `protobuf:"varint,2,opt,name=do_shared,json=doShared,proto3" json:"do_shared,omitempty"`
}

func (x *BatchClaimTaskRewardRequest) Reset() {
	*x = BatchClaimTaskRewardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_task_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchClaimTaskRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClaimTaskRewardRequest) ProtoMessage() {}

func (x *BatchClaimTaskRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_task_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClaimTaskRewardRequest.ProtoReflect.Descriptor instead.
func (*BatchClaimTaskRewardRequest) Descriptor() ([]byte, []int) {
	return file_taskpb_task_proto_rawDescGZIP(), []int{7}
}

func (x *BatchClaimTaskRewardRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *BatchClaimTaskRewardRequest) GetDoShared() bool {
	if x != nil {
		return x.DoShared
	}
	return false
}

type BatchClaimTaskRewardReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items            []*corepb.Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TaskInfo         *TaskInfo      `protobuf:"bytes,2,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`
	CompensatedItems []*corepb.Item `protobuf:"bytes,3,rep,name=compensated_items,json=compensatedItems,proto3" json:"compensated_items,omitempty"`
}

func (x *BatchClaimTaskRewardReply) Reset() {
	*x = BatchClaimTaskRewardReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_task_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchClaimTaskRewardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClaimTaskRewardReply) ProtoMessage() {}

func (x *BatchClaimTaskRewardReply) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_task_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClaimTaskRewardReply.ProtoReflect.Descriptor instead.
func (*BatchClaimTaskRewardReply) Descriptor() ([]byte, []int) {
	return file_taskpb_task_proto_rawDescGZIP(), []int{8}
}

func (x *BatchClaimTaskRewardReply) GetItems() []*corepb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchClaimTaskRewardReply) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

func (x *BatchClaimTaskRewardReply) GetCompensatedItems() []*corepb.Item {
	if x != nil {
		return x.CompensatedItems
	}
	return nil
}

type TaskInfoNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskInfo *TaskInfo `protobuf:"bytes,1,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`
}

func (x *TaskInfoNotify) Reset() {
	*x = TaskInfoNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_task_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoNotify) ProtoMessage() {}

func (x *TaskInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_task_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoNotify.ProtoReflect.Descriptor instead.
func (*TaskInfoNotify) Descriptor() ([]byte, []int) {
	return file_taskpb_task_proto_rawDescGZIP(), []int{9}
}

func (x *TaskInfoNotify) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

var File_taskpb_task_proto protoreflect.FileDescriptor

var file_taskpb_task_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b,
	0x70, 0x62, 0x1a, 0x11, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x03, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73,
	0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x69, 0x73, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f,
	0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x69, 0x73, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x07, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x5f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0c,
	0x69, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x69, 0x73, 0x53, 0x68, 0x6f, 0x77, 0x54, 0x65, 0x78, 0x74, 0x22, 0x54,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0xd4, 0x01, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x36, 0x0a, 0x0c, 0x67, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x5f, 0x74, 0x61, 0x73, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62,
	0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x0b, 0x67, 0x72,
	0x6f, 0x77, 0x74, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x34, 0x0a, 0x0b, 0x64, 0x61, 0x69,
	0x6c, 0x79, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x0a, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12,
	0x29, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x54,
	0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45,
	0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x34, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b,
	0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x45, 0x0a, 0x16, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x64, 0x6f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0xab, 0x01, 0x0a,
	0x14, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x39, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e,
	0x73, 0x61, 0x74, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x4c, 0x0a, 0x1b, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x6f, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x64, 0x6f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0xb0, 0x01, 0x0a, 0x19, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x39, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x65,
	0x6e, 0x73, 0x61, 0x74, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x46, 0x0a, 0x0e, 0x54,
	0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x34, 0x0a,
	0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x42, 0x1a, 0x5a, 0x18, 0x71, 0x71, 0x2d, 0x66, 0x61, 0x72, 0x6d, 0x2d, 0x62,
	0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_taskpb_task_proto_rawDescOnce sync.Once
	file_taskpb_task_proto_rawDescData = file_taskpb_task_proto_rawDesc
)

func file_taskpb_task_proto_rawDescGZIP() []byte {
	file_taskpb_task_proto_rawDescOnce.Do(func() {
		file_taskpb_task_proto_rawDescData = protoimpl.X.CompressGZIP(file_taskpb_task_proto_rawDescData)
	})
	return file_taskpb_task_proto_rawDescData
}

var file_taskpb_task_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_taskpb_task_proto_goTypes = []interface{}{
	(*Task)(nil),                        // 0: gamepb.taskpb.Task
	(*Active)(nil),                      // 1: gamepb.taskpb.Active
	(*TaskInfo)(nil),                    // 2: gamepb.taskpb.TaskInfo
	(*TaskInfoRequest)(nil),             // 3: gamepb.taskpb.TaskInfoRequest
	(*TaskInfoReply)(nil),               // 4: gamepb.taskpb.TaskInfoReply
	(*ClaimTaskRewardRequest)(nil),      // 5: gamepb.taskpb.ClaimTaskRewardRequest
	(*ClaimTaskRewardReply)(nil),        // 6: gamepb.taskpb.ClaimTaskRewardReply
	(*BatchClaimTaskRewardRequest)(nil), // 7: gamepb.taskpb.BatchClaimTaskRewardRequest
	(*BatchClaimTaskRewardReply)(nil),   // 8: gamepb.taskpb.BatchClaimTaskRewardReply
	(*TaskInfoNotify)(nil),              // 9: gamepb.taskpb.TaskInfoNotify
	(*corepb.Item)(nil),                 // 10: corepb.Item
}
var file_taskpb_task_proto_depIdxs = []int32{
	10, // 0: gamepb.taskpb.Task.rewards:type_name -> corepb.Item
	10, // 1: gamepb.taskpb.Active.items:type_name -> corepb.Item
	0,  // 2: gamepb.taskpb.TaskInfo.growth_tasks:type_name -> gamepb.taskpb.Task
	0,  // 3: gamepb.taskpb.TaskInfo.daily_tasks:type_name -> gamepb.taskpb.Task
	0,  // 4: gamepb.taskpb.TaskInfo.tasks:type_name -> gamepb.taskpb.Task
	1,  // 5: gamepb.taskpb.TaskInfo.actives:type_name -> gamepb.taskpb.Active
	2,  // 6: gamepb.taskpb.TaskInfoReply.task_info:type_name -> gamepb.taskpb.TaskInfo
	10, // 7: gamepb.taskpb.ClaimTaskRewardReply.items:type_name -> corepb.Item
	2,  // 8: gamepb.taskpb.ClaimTaskRewardReply.task_info:type_name -> gamepb.taskpb.TaskInfo
	10, // 9: gamepb.taskpb.ClaimTaskRewardReply.compensated_items:type_name -> corepb.Item
	10, // 10: gamepb.taskpb.BatchClaimTaskRewardReply.items:type_name -> corepb.Item
	2,  // 11: gamepb.taskpb.BatchClaimTaskRewardReply.task_info:type_name -> gamepb.taskpb.TaskInfo
	10, // 12: gamepb.taskpb.BatchClaimTaskRewardReply.compensated_items:type_name -> corepb.Item
	2,  // 13: gamepb.taskpb.TaskInfoNotify.task_info:type_name -> gamepb.taskpb.TaskInfo
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_taskpb_task_proto_init() }
func file_taskpb_task_proto_init() {
	if File_taskpb_task_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_taskpb_task_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_task_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Active); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_task_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_task_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_task_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_task_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimTaskRewardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_task_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimTaskRewardReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_task_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchClaimTaskRewardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_task_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchClaimTaskRewardReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_task_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfoNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_taskpb_task_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_taskpb_task_proto_goTypes,
		DependencyIndexes: file_taskpb_task_proto_depIdxs,
		MessageInfos:      file_taskpb_task_proto_msgTypes,
	}.Build()
	File_taskpb_task_proto = out.File
	file_taskpb_task_proto_rawDesc = nil
	file_taskpb_task_proto_goTypes = nil
	file_taskpb_task_proto_depIdxs = nil
}
