// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: avatarframepb/avatarframe.proto

package avatarframepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvatarFrameType int32

const (
	AvatarFrameType_AVATAR_FRAME_UNKNOWN AvatarFrameType = 0
	AvatarFrameType_PERMANENT            AvatarFrameType = 1
)

// Enum value maps for AvatarFrameType.
var (
	AvatarFrameType_name = map[int32]string{
		0: "AVATAR_FRAME_UNKNOWN",
		1: "PERMANENT",
	}
	AvatarFrameType_value = map[string]int32{
		"AVATAR_FRAME_UNKNOWN": 0,
		"PERMANENT":            1,
	}
)

func (x AvatarFrameType) Enum() *AvatarFrameType {
	p := new(AvatarFrameType)
	*p = x
	return p
}

func (x AvatarFrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvatarFrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_avatarframepb_avatarframe_proto_enumTypes[0].Descriptor()
}

func (AvatarFrameType) Type() protoreflect.EnumType {
	return &file_avatarframepb_avatarframe_proto_enumTypes[0]
}

func (x AvatarFrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvatarFrameType.Descriptor instead.
func (AvatarFrameType) EnumDescriptor() ([]byte, []int) {
	return file_avatarframepb_avatarframe_proto_rawDescGZIP(), []int{0}
}

type AvatarFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarFrame) Reset() {
	*x = AvatarFrame{}
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarFrame) ProtoMessage() {}

func (x *AvatarFrame) ProtoReflect() protoreflect.Message {
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarFrame.ProtoReflect.Descriptor instead.
func (*AvatarFrame) Descriptor() ([]byte, []int) {
	return file_avatarframepb_avatarframe_proto_rawDescGZIP(), []int{0}
}

func (x *AvatarFrame) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AvatarFrame) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AvatarFrame) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AvatarFrame) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type EquipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipRequest) Reset() {
	*x = EquipRequest{}
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipRequest) ProtoMessage() {}

func (x *EquipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipRequest.ProtoReflect.Descriptor instead.
func (*EquipRequest) Descriptor() ([]byte, []int) {
	return file_avatarframepb_avatarframe_proto_rawDescGZIP(), []int{1}
}

func (x *EquipRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EquipReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipReply) Reset() {
	*x = EquipReply{}
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipReply) ProtoMessage() {}

func (x *EquipReply) ProtoReflect() protoreflect.Message {
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipReply.ProtoReflect.Descriptor instead.
func (*EquipReply) Descriptor() ([]byte, []int) {
	return file_avatarframepb_avatarframe_proto_rawDescGZIP(), []int{2}
}

type AvatarFramesEquipedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarFramesEquipedRequest) Reset() {
	*x = AvatarFramesEquipedRequest{}
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarFramesEquipedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarFramesEquipedRequest) ProtoMessage() {}

func (x *AvatarFramesEquipedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarFramesEquipedRequest.ProtoReflect.Descriptor instead.
func (*AvatarFramesEquipedRequest) Descriptor() ([]byte, []int) {
	return file_avatarframepb_avatarframe_proto_rawDescGZIP(), []int{3}
}

type AvatarFramesEquipedReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        []*AvatarFrame         `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarFramesEquipedReply) Reset() {
	*x = AvatarFramesEquipedReply{}
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarFramesEquipedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarFramesEquipedReply) ProtoMessage() {}

func (x *AvatarFramesEquipedReply) ProtoReflect() protoreflect.Message {
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarFramesEquipedReply.ProtoReflect.Descriptor instead.
func (*AvatarFramesEquipedReply) Descriptor() ([]byte, []int) {
	return file_avatarframepb_avatarframe_proto_rawDescGZIP(), []int{4}
}

func (x *AvatarFramesEquipedReply) GetFrames() []*AvatarFrame {
	if x != nil {
		return x.Frames
	}
	return nil
}

type AvatarFramesOwnedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarFramesOwnedRequest) Reset() {
	*x = AvatarFramesOwnedRequest{}
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarFramesOwnedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarFramesOwnedRequest) ProtoMessage() {}

func (x *AvatarFramesOwnedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarFramesOwnedRequest.ProtoReflect.Descriptor instead.
func (*AvatarFramesOwnedRequest) Descriptor() ([]byte, []int) {
	return file_avatarframepb_avatarframe_proto_rawDescGZIP(), []int{5}
}

type AvatarFramesOwnedReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        []*AvatarFrame         `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarFramesOwnedReply) Reset() {
	*x = AvatarFramesOwnedReply{}
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarFramesOwnedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarFramesOwnedReply) ProtoMessage() {}

func (x *AvatarFramesOwnedReply) ProtoReflect() protoreflect.Message {
	mi := &file_avatarframepb_avatarframe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarFramesOwnedReply.ProtoReflect.Descriptor instead.
func (*AvatarFramesOwnedReply) Descriptor() ([]byte, []int) {
	return file_avatarframepb_avatarframe_proto_rawDescGZIP(), []int{6}
}

func (x *AvatarFramesOwnedReply) GetFrames() []*AvatarFrame {
	if x != nil {
		return x.Frames
	}
	return nil
}

var File_avatarframepb_avatarframe_proto protoreflect.FileDescriptor

const file_avatarframepb_avatarframe_proto_rawDesc = "" +
	"\n" +
	"\x1favatarframepb/avatarframe.proto\x12\x14gamepb.avatarframepb\"c\n" +
	"\vAvatarFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\"\x1e\n" +
	"\fEquipRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\f\n" +
	"\n" +
	"EquipReply\"\x1c\n" +
	"\x1aAvatarFramesEquipedRequest\"U\n" +
	"\x18AvatarFramesEquipedReply\x129\n" +
	"\x06frames\x18\x01 \x03(\v2!.gamepb.avatarframepb.AvatarFrameR\x06frames\"\x1a\n" +
	"\x18AvatarFramesOwnedRequest\"S\n" +
	"\x16AvatarFramesOwnedReply\x129\n" +
	"\x06frames\x18\x01 \x03(\v2!.gamepb.avatarframepb.AvatarFrameR\x06frames*:\n" +
	"\x0fAvatarFrameType\x12\x18\n" +
	"\x14AVATAR_FRAME_UNKNOWN\x10\x00\x12\r\n" +
	"\tPERMANENT\x10\x01B!Z\x1fqq-farm-bot/proto/avatarframepbb\x06proto3"

var (
	file_avatarframepb_avatarframe_proto_rawDescOnce sync.Once
	file_avatarframepb_avatarframe_proto_rawDescData []byte
)

func file_avatarframepb_avatarframe_proto_rawDescGZIP() []byte {
	file_avatarframepb_avatarframe_proto_rawDescOnce.Do(func() {
		file_avatarframepb_avatarframe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avatarframepb_avatarframe_proto_rawDesc), len(file_avatarframepb_avatarframe_proto_rawDesc)))
	})
	return file_avatarframepb_avatarframe_proto_rawDescData
}

var file_avatarframepb_avatarframe_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_avatarframepb_avatarframe_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_avatarframepb_avatarframe_proto_goTypes = []any{
	(AvatarFrameType)(0),               // 0: gamepb.avatarframepb.AvatarFrameType
	(*AvatarFrame)(nil),                // 1: gamepb.avatarframepb.AvatarFrame
	(*EquipRequest)(nil),               // 2: gamepb.avatarframepb.EquipRequest
	(*EquipReply)(nil),                 // 3: gamepb.avatarframepb.EquipReply
	(*AvatarFramesEquipedRequest)(nil), // 4: gamepb.avatarframepb.AvatarFramesEquipedRequest
	(*AvatarFramesEquipedReply)(nil),   // 5: gamepb.avatarframepb.AvatarFramesEquipedReply
	(*AvatarFramesOwnedRequest)(nil),   // 6: gamepb.avatarframepb.AvatarFramesOwnedRequest
	(*AvatarFramesOwnedReply)(nil),     // 7: gamepb.avatarframepb.AvatarFramesOwnedReply
}
var file_avatarframepb_avatarframe_proto_depIdxs = []int32{
	1, // 0: gamepb.avatarframepb.AvatarFramesEquipedReply.frames:type_name -> gamepb.avatarframepb.AvatarFrame
	1, // 1: gamepb.avatarframepb.AvatarFramesOwnedReply.frames:type_name -> gamepb.avatarframepb.AvatarFrame
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_avatarframepb_avatarframe_proto_init() }
func file_avatarframepb_avatarframe_proto_init() {
	if File_avatarframepb_avatarframe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avatarframepb_avatarframe_proto_rawDesc), len(file_avatarframepb_avatarframe_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_avatarframepb_avatarframe_proto_goTypes,
		DependencyIndexes: file_avatarframepb_avatarframe_proto_depIdxs,
		EnumInfos:         file_avatarframepb_avatarframe_proto_enumTypes,
		MessageInfos:      file_avatarframepb_avatarframe_proto_msgTypes,
	}.Build()
	File_avatarframepb_avatarframe_proto = out.File
	file_avatarframepb_avatarframe_proto_goTypes = nil
	file_avatarframepb_avatarframe_proto_depIdxs = nil
}
