// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: uicproxypb/uicproxy.proto

package uicproxypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultText    string                 `protobuf:"bytes,2,opt,name=result_text,json=resultText,proto3" json:"result_text,omitempty"`
	IsDirty       bool                   `protobuf:"varint,3,opt,name=is_dirty,json=isDirty,proto3" json:"is_dirty,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_uicproxypb_uicproxy_proto_rawDescGZIP(), []int{0}
}

func (x *Text) GetResultText() string {
	if x != nil {
		return x.ResultText
	}
	return ""
}

func (x *Text) GetIsDirty() bool {
	if x != nil {
		return x.IsDirty
	}
	return false
}

func (x *Text) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TextItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextItem) Reset() {
	*x = TextItem{}
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextItem) ProtoMessage() {}

func (x *TextItem) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextItem.ProtoReflect.Descriptor instead.
func (*TextItem) Descriptor() ([]byte, []int) {
	return file_uicproxypb_uicproxy_proto_rawDescGZIP(), []int{1}
}

func (x *TextItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Pic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultUrl     string                 `protobuf:"bytes,1,opt,name=result_url,json=resultUrl,proto3" json:"result_url,omitempty"`
	IsDirty       bool                   `protobuf:"varint,2,opt,name=is_dirty,json=isDirty,proto3" json:"is_dirty,omitempty"`
	DirtyType     int64                  `protobuf:"varint,3,opt,name=dirty_type,json=dirtyType,proto3" json:"dirty_type,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pic) Reset() {
	*x = Pic{}
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pic) ProtoMessage() {}

func (x *Pic) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pic.ProtoReflect.Descriptor instead.
func (*Pic) Descriptor() ([]byte, []int) {
	return file_uicproxypb_uicproxy_proto_rawDescGZIP(), []int{2}
}

func (x *Pic) GetResultUrl() string {
	if x != nil {
		return x.ResultUrl
	}
	return ""
}

func (x *Pic) GetIsDirty() bool {
	if x != nil {
		return x.IsDirty
	}
	return false
}

func (x *Pic) GetDirtyType() int64 {
	if x != nil {
		return x.DirtyType
	}
	return 0
}

func (x *Pic) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PicItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PicUrl        string                 `protobuf:"bytes,1,opt,name=pic_url,json=picUrl,proto3" json:"pic_url,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PicItem) Reset() {
	*x = PicItem{}
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PicItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PicItem) ProtoMessage() {}

func (x *PicItem) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PicItem.ProtoReflect.Descriptor instead.
func (*PicItem) Descriptor() ([]byte, []int) {
	return file_uicproxypb_uicproxy_proto_rawDescGZIP(), []int{3}
}

func (x *PicItem) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *PicItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ModerateTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModerateTextRequest) Reset() {
	*x = ModerateTextRequest{}
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerateTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerateTextRequest) ProtoMessage() {}

func (x *ModerateTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerateTextRequest.ProtoReflect.Descriptor instead.
func (*ModerateTextRequest) Descriptor() ([]byte, []int) {
	return file_uicproxypb_uicproxy_proto_rawDescGZIP(), []int{4}
}

func (x *ModerateTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ModerateTextRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ModerateTextReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModerateTextReply) Reset() {
	*x = ModerateTextReply{}
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerateTextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerateTextReply) ProtoMessage() {}

func (x *ModerateTextReply) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerateTextReply.ProtoReflect.Descriptor instead.
func (*ModerateTextReply) Descriptor() ([]byte, []int) {
	return file_uicproxypb_uicproxy_proto_rawDescGZIP(), []int{5}
}

func (x *ModerateTextReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BatchModerateTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TextItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchModerateTextRequest) Reset() {
	*x = BatchModerateTextRequest{}
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchModerateTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchModerateTextRequest) ProtoMessage() {}

func (x *BatchModerateTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchModerateTextRequest.ProtoReflect.Descriptor instead.
func (*BatchModerateTextRequest) Descriptor() ([]byte, []int) {
	return file_uicproxypb_uicproxy_proto_rawDescGZIP(), []int{6}
}

func (x *BatchModerateTextRequest) GetItems() []*TextItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchModerateTextReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Text                `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchModerateTextReply) Reset() {
	*x = BatchModerateTextReply{}
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchModerateTextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchModerateTextReply) ProtoMessage() {}

func (x *BatchModerateTextReply) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchModerateTextReply.ProtoReflect.Descriptor instead.
func (*BatchModerateTextReply) Descriptor() ([]byte, []int) {
	return file_uicproxypb_uicproxy_proto_rawDescGZIP(), []int{7}
}

func (x *BatchModerateTextReply) GetResults() []*Text {
	if x != nil {
		return x.Results
	}
	return nil
}

type ModeratePicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PicUrl        string                 `protobuf:"bytes,1,opt,name=pic_url,json=picUrl,proto3" json:"pic_url,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeratePicRequest) Reset() {
	*x = ModeratePicRequest{}
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeratePicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeratePicRequest) ProtoMessage() {}

func (x *ModeratePicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeratePicRequest.ProtoReflect.Descriptor instead.
func (*ModeratePicRequest) Descriptor() ([]byte, []int) {
	return file_uicproxypb_uicproxy_proto_rawDescGZIP(), []int{8}
}

func (x *ModeratePicRequest) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *ModeratePicRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ModeratePicReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeratePicReply) Reset() {
	*x = ModeratePicReply{}
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeratePicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeratePicReply) ProtoMessage() {}

func (x *ModeratePicReply) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeratePicReply.ProtoReflect.Descriptor instead.
func (*ModeratePicReply) Descriptor() ([]byte, []int) {
	return file_uicproxypb_uicproxy_proto_rawDescGZIP(), []int{9}
}

func (x *ModeratePicReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BatchModeratePicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PicItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchModeratePicRequest) Reset() {
	*x = BatchModeratePicRequest{}
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchModeratePicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchModeratePicRequest) ProtoMessage() {}

func (x *BatchModeratePicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchModeratePicRequest.ProtoReflect.Descriptor instead.
func (*BatchModeratePicRequest) Descriptor() ([]byte, []int) {
	return file_uicproxypb_uicproxy_proto_rawDescGZIP(), []int{10}
}

func (x *BatchModeratePicRequest) GetItems() []*PicItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchModeratePicReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Pic                 `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchModeratePicReply) Reset() {
	*x = BatchModeratePicReply{}
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchModeratePicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchModeratePicReply) ProtoMessage() {}

func (x *BatchModeratePicReply) ProtoReflect() protoreflect.Message {
	mi := &file_uicproxypb_uicproxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchModeratePicReply.ProtoReflect.Descriptor instead.
func (*BatchModeratePicReply) Descriptor() ([]byte, []int) {
	return file_uicproxypb_uicproxy_proto_rawDescGZIP(), []int{11}
}

func (x *BatchModeratePicReply) GetResults() []*Pic {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_uicproxypb_uicproxy_proto protoreflect.FileDescriptor

const file_uicproxypb_uicproxy_proto_rawDesc = "" +
	"\n" +
	"\x19uicproxypb/uicproxy.proto\x12\x11gamepb.uicproxypb\"Z\n" +
	"\x04Text\x12\x1f\n" +
	"\vresult_text\x18\x02 \x01(\tR\n" +
	"resultText\x12\x19\n" +
	"\bis_dirty\x18\x03 \x01(\bR\aisDirty\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"6\n" +
	"\bTextItem\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"v\n" +
	"\x03Pic\x12\x1d\n" +
	"\n" +
	"result_url\x18\x01 \x01(\tR\tresultUrl\x12\x19\n" +
	"\bis_dirty\x18\x02 \x01(\bR\aisDirty\x12\x1d\n" +
	"\n" +
	"dirty_type\x18\x03 \x01(\x03R\tdirtyType\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\":\n" +
	"\aPicItem\x12\x17\n" +
	"\apic_url\x18\x01 \x01(\tR\x06picUrl\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"A\n" +
	"\x13ModerateTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"+\n" +
	"\x11ModerateTextReply\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"M\n" +
	"\x18BatchModerateTextRequest\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.gamepb.uicproxypb.TextItemR\x05items\"K\n" +
	"\x16BatchModerateTextReply\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.gamepb.uicproxypb.TextR\aresults\"E\n" +
	"\x12ModeratePicRequest\x12\x17\n" +
	"\apic_url\x18\x01 \x01(\tR\x06picUrl\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"*\n" +
	"\x10ModeratePicReply\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"K\n" +
	"\x17BatchModeratePicRequest\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.gamepb.uicproxypb.PicItemR\x05items\"I\n" +
	"\x15BatchModeratePicReply\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.gamepb.uicproxypb.PicR\aresultsB\x1eZ\x1cqq-farm-bot/proto/uicproxypbb\x06proto3"

var (
	file_uicproxypb_uicproxy_proto_rawDescOnce sync.Once
	file_uicproxypb_uicproxy_proto_rawDescData []byte
)

func file_uicproxypb_uicproxy_proto_rawDescGZIP() []byte {
	file_uicproxypb_uicproxy_proto_rawDescOnce.Do(func() {
		file_uicproxypb_uicproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_uicproxypb_uicproxy_proto_rawDesc), len(file_uicproxypb_uicproxy_proto_rawDesc)))
	})
	return file_uicproxypb_uicproxy_proto_rawDescData
}

var file_uicproxypb_uicproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_uicproxypb_uicproxy_proto_goTypes = []any{
	(*Text)(nil),                     // 0: gamepb.uicproxypb.Text
	(*TextItem)(nil),                 // 1: gamepb.uicproxypb.TextItem
	(*Pic)(nil),                      // 2: gamepb.uicproxypb.Pic
	(*PicItem)(nil),                  // 3: gamepb.uicproxypb.PicItem
	(*ModerateTextRequest)(nil),      // 4: gamepb.uicproxypb.ModerateTextRequest
	(*ModerateTextReply)(nil),        // 5: gamepb.uicproxypb.ModerateTextReply
	(*BatchModerateTextRequest)(nil), // 6: gamepb.uicproxypb.BatchModerateTextRequest
	(*BatchModerateTextReply)(nil),   // 7: gamepb.uicproxypb.BatchModerateTextReply
	(*ModeratePicRequest)(nil),       // 8: gamepb.uicproxypb.ModeratePicRequest
	(*ModeratePicReply)(nil),         // 9: gamepb.uicproxypb.ModeratePicReply
	(*BatchModeratePicRequest)(nil),  // 10: gamepb.uicproxypb.BatchModeratePicRequest
	(*BatchModeratePicReply)(nil),    // 11: gamepb.uicproxypb.BatchModeratePicReply
}
var file_uicproxypb_uicproxy_proto_depIdxs = []int32{
	1, // 0: gamepb.uicproxypb.BatchModerateTextRequest.items:type_name -> gamepb.uicproxypb.TextItem
	0, // 1: gamepb.uicproxypb.BatchModerateTextReply.results:type_name -> gamepb.uicproxypb.Text
	3, // 2: gamepb.uicproxypb.BatchModeratePicRequest.items:type_name -> gamepb.uicproxypb.PicItem
	2, // 3: gamepb.uicproxypb.BatchModeratePicReply.results:type_name -> gamepb.uicproxypb.Pic
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_uicproxypb_uicproxy_proto_init() }
func file_uicproxypb_uicproxy_proto_init() {
	if File_uicproxypb_uicproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_uicproxypb_uicproxy_proto_rawDesc), len(file_uicproxypb_uicproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uicproxypb_uicproxy_proto_goTypes,
		DependencyIndexes: file_uicproxypb_uicproxy_proto_depIdxs,
		MessageInfos:      file_uicproxypb_uicproxy_proto_msgTypes,
	}.Build()
	File_uicproxypb_uicproxy_proto = out.File
	file_uicproxypb_uicproxy_proto_goTypes = nil
	file_uicproxypb_uicproxy_proto_depIdxs = nil
}
