// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: interactpb/interact.proto

package interactpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Time             int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	InteractType     int64                  `protobuf:"varint,2,opt,name=interact_type,json=interactType,proto3" json:"interact_type,omitempty"`
	OprGid           int64                  `protobuf:"varint,3,opt,name=opr_gid,json=oprGid,proto3" json:"opr_gid,omitempty"`
	OprNickname      string                 `protobuf:"bytes,4,opt,name=opr_nickname,json=oprNickname,proto3" json:"opr_nickname,omitempty"`
	OprAvatarUrl     string                 `protobuf:"bytes,5,opt,name=opr_avatar_url,json=oprAvatarUrl,proto3" json:"opr_avatar_url,omitempty"`
	StealItemId      int64                  `protobuf:"varint,6,opt,name=steal_item_id,json=stealItemId,proto3" json:"steal_item_id,omitempty"`
	StealItemNum     int64                  `protobuf:"varint,7,opt,name=steal_item_num,json=stealItemNum,proto3" json:"steal_item_num,omitempty"`
	Count            int64                  `protobuf:"varint,8,opt,name=count,proto3" json:"count,omitempty"`
	AuthorizedStatus int32                  `protobuf:"varint,9,opt,name=authorized_status,json=authorizedStatus,proto3" json:"authorized_status,omitempty"`
	Level            int64                  `protobuf:"varint,10,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_interactpb_interact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_interact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_interactpb_interact_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Record) GetInteractType() int64 {
	if x != nil {
		return x.InteractType
	}
	return 0
}

func (x *Record) GetOprGid() int64 {
	if x != nil {
		return x.OprGid
	}
	return 0
}

func (x *Record) GetOprNickname() string {
	if x != nil {
		return x.OprNickname
	}
	return ""
}

func (x *Record) GetOprAvatarUrl() string {
	if x != nil {
		return x.OprAvatarUrl
	}
	return ""
}

func (x *Record) GetStealItemId() int64 {
	if x != nil {
		return x.StealItemId
	}
	return 0
}

func (x *Record) GetStealItemNum() int64 {
	if x != nil {
		return x.StealItemNum
	}
	return 0
}

func (x *Record) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Record) GetAuthorizedStatus() int32 {
	if x != nil {
		return x.AuthorizedStatus
	}
	return 0
}

func (x *Record) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

type InteractRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractRecordsRequest) Reset() {
	*x = InteractRecordsRequest{}
	mi := &file_interactpb_interact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRecordsRequest) ProtoMessage() {}

func (x *InteractRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_interact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRecordsRequest.ProtoReflect.Descriptor instead.
func (*InteractRecordsRequest) Descriptor() ([]byte, []int) {
	return file_interactpb_interact_proto_rawDescGZIP(), []int{1}
}

func (x *InteractRecordsRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *InteractRecordsRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type InteractRecordsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractRecordsReply) Reset() {
	*x = InteractRecordsReply{}
	mi := &file_interactpb_interact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractRecordsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRecordsReply) ProtoMessage() {}

func (x *InteractRecordsReply) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_interact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRecordsReply.ProtoReflect.Descriptor instead.
func (*InteractRecordsReply) Descriptor() ([]byte, []int) {
	return file_interactpb_interact_proto_rawDescGZIP(), []int{2}
}

func (x *InteractRecordsReply) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type InteractNewRecordNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasUnread     bool                   `protobuf:"varint,1,opt,name=has_unread,json=hasUnread,proto3" json:"has_unread,omitempty"`
	LastReadTime  int64                  `protobuf:"varint,2,opt,name=last_read_time,json=lastReadTime,proto3" json:"last_read_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractNewRecordNotify) Reset() {
	*x = InteractNewRecordNotify{}
	mi := &file_interactpb_interact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractNewRecordNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractNewRecordNotify) ProtoMessage() {}

func (x *InteractNewRecordNotify) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_interact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractNewRecordNotify.ProtoReflect.Descriptor instead.
func (*InteractNewRecordNotify) Descriptor() ([]byte, []int) {
	return file_interactpb_interact_proto_rawDescGZIP(), []int{3}
}

func (x *InteractNewRecordNotify) GetHasUnread() bool {
	if x != nil {
		return x.HasUnread
	}
	return false
}

func (x *InteractNewRecordNotify) GetLastReadTime() int64 {
	if x != nil {
		return x.LastReadTime
	}
	return 0
}

type GetInteractInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractInfoRequest) Reset() {
	*x = GetInteractInfoRequest{}
	mi := &file_interactpb_interact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractInfoRequest) ProtoMessage() {}

func (x *GetInteractInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_interact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInteractInfoRequest) Descriptor() ([]byte, []int) {
	return file_interactpb_interact_proto_rawDescGZIP(), []int{4}
}

type GetInteractInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasUnread     bool                   `protobuf:"varint,1,opt,name=has_unread,json=hasUnread,proto3" json:"has_unread,omitempty"`
	LastReadTime  int64                  `protobuf:"varint,2,opt,name=last_read_time,json=lastReadTime,proto3" json:"last_read_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractInfoReply) Reset() {
	*x = GetInteractInfoReply{}
	mi := &file_interactpb_interact_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractInfoReply) ProtoMessage() {}

func (x *GetInteractInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_interact_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractInfoReply.ProtoReflect.Descriptor instead.
func (*GetInteractInfoReply) Descriptor() ([]byte, []int) {
	return file_interactpb_interact_proto_rawDescGZIP(), []int{5}
}

func (x *GetInteractInfoReply) GetHasUnread() bool {
	if x != nil {
		return x.HasUnread
	}
	return false
}

func (x *GetInteractInfoReply) GetLastReadTime() int64 {
	if x != nil {
		return x.LastReadTime
	}
	return 0
}

var File_interactpb_interact_proto protoreflect.FileDescriptor

const file_interactpb_interact_proto_rawDesc = "" +
	"\n" +
	"\x19interactpb/interact.proto\x12\x11gamepb.interactpb\"\xc6\x02\n" +
	"\x06Record\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12#\n" +
	"\rinteract_type\x18\x02 \x01(\x03R\finteractType\x12\x17\n" +
	"\aopr_gid\x18\x03 \x01(\x03R\x06oprGid\x12!\n" +
	"\fopr_nickname\x18\x04 \x01(\tR\voprNickname\x12$\n" +
	"\x0eopr_avatar_url\x18\x05 \x01(\tR\foprAvatarUrl\x12\"\n" +
	"\rsteal_item_id\x18\x06 \x01(\x03R\vstealItemId\x12$\n" +
	"\x0esteal_item_num\x18\a \x01(\x03R\fstealItemNum\x12\x14\n" +
	"\x05count\x18\b \x01(\x03R\x05count\x12+\n" +
	"\x11authorized_status\x18\t \x01(\x05R\x10authorizedStatus\x12\x14\n" +
	"\x05level\x18\n" +
	" \x01(\x03R\x05level\"B\n" +
	"\x16InteractRecordsRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x03R\x04from\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"K\n" +
	"\x14InteractRecordsReply\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.gamepb.interactpb.RecordR\arecords\"^\n" +
	"\x17InteractNewRecordNotify\x12\x1d\n" +
	"\n" +
	"has_unread\x18\x01 \x01(\bR\thasUnread\x12$\n" +
	"\x0elast_read_time\x18\x02 \x01(\x03R\flastReadTime\"\x18\n" +
	"\x16GetInteractInfoRequest\"[\n" +
	"\x14GetInteractInfoReply\x12\x1d\n" +
	"\n" +
	"has_unread\x18\x01 \x01(\bR\thasUnread\x12$\n" +
	"\x0elast_read_time\x18\x02 \x01(\x03R\flastReadTimeB\x1eZ\x1cqq-farm-bot/proto/interactpbb\x06proto3"

var (
	file_interactpb_interact_proto_rawDescOnce sync.Once
	file_interactpb_interact_proto_rawDescData []byte
)

func file_interactpb_interact_proto_rawDescGZIP() []byte {
	file_interactpb_interact_proto_rawDescOnce.Do(func() {
		file_interactpb_interact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interactpb_interact_proto_rawDesc), len(file_interactpb_interact_proto_rawDesc)))
	})
	return file_interactpb_interact_proto_rawDescData
}

var file_interactpb_interact_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_interactpb_interact_proto_goTypes = []any{
	(*Record)(nil),                  // 0: gamepb.interactpb.Record
	(*InteractRecordsRequest)(nil),  // 1: gamepb.interactpb.InteractRecordsRequest
	(*InteractRecordsReply)(nil),    // 2: gamepb.interactpb.InteractRecordsReply
	(*InteractNewRecordNotify)(nil), // 3: gamepb.interactpb.InteractNewRecordNotify
	(*GetInteractInfoRequest)(nil),  // 4: gamepb.interactpb.GetInteractInfoRequest
	(*GetInteractInfoReply)(nil),    // 5: gamepb.interactpb.GetInteractInfoReply
}
var file_interactpb_interact_proto_depIdxs = []int32{
	0, // 0: gamepb.interactpb.InteractRecordsReply.records:type_name -> gamepb.interactpb.Record
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_interactpb_interact_proto_init() }
func file_interactpb_interact_proto_init() {
	if File_interactpb_interact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interactpb_interact_proto_rawDesc), len(file_interactpb_interact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interactpb_interact_proto_goTypes,
		DependencyIndexes: file_interactpb_interact_proto_depIdxs,
		MessageInfos:      file_interactpb_interact_proto_msgTypes,
	}.Build()
	File_interactpb_interact_proto = out.File
	file_interactpb_interact_proto_goTypes = nil
	file_interactpb_interact_proto_depIdxs = nil
}
