// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: marqueepb/marquee.proto

package marqueepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarqueeType int32

const (
	MarqueeType_MARQUEE_UNKNOWN MarqueeType = 0
	MarqueeType_PERSISTENT      MarqueeType = 1
)

// Enum value maps for MarqueeType.
var (
	MarqueeType_name = map[int32]string{
		0: "MARQUEE_UNKNOWN",
		1: "PERSISTENT",
	}
	MarqueeType_value = map[string]int32{
		"MARQUEE_UNKNOWN": 0,
		"PERSISTENT":      1,
	}
)

func (x MarqueeType) Enum() *MarqueeType {
	p := new(MarqueeType)
	*p = x
	return p
}

func (x MarqueeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarqueeType) Descriptor() protoreflect.EnumDescriptor {
	return file_marqueepb_marquee_proto_enumTypes[0].Descriptor()
}

func (MarqueeType) Type() protoreflect.EnumType {
	return &file_marqueepb_marquee_proto_enumTypes[0]
}

func (x MarqueeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarqueeType.Descriptor instead.
func (MarqueeType) EnumDescriptor() ([]byte, []int) {
	return file_marqueepb_marquee_proto_rawDescGZIP(), []int{0}
}

type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          int64                  `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ConfigId      int32                  `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	DisplayCount  int32                  `protobuf:"varint,7,opt,name=display_count,json=displayCount,proto3" json:"display_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_marqueepb_marquee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_marqueepb_marquee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_marqueepb_marquee_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetUuid() int64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *Msg) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *Msg) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *Msg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Msg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Msg) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Msg) GetDisplayCount() int32 {
	if x != nil {
		return x.DisplayCount
	}
	return 0
}

type GetMarqueeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarqueeRequest) Reset() {
	*x = GetMarqueeRequest{}
	mi := &file_marqueepb_marquee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarqueeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarqueeRequest) ProtoMessage() {}

func (x *GetMarqueeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marqueepb_marquee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarqueeRequest.ProtoReflect.Descriptor instead.
func (*GetMarqueeRequest) Descriptor() ([]byte, []int) {
	return file_marqueepb_marquee_proto_rawDescGZIP(), []int{1}
}

type GetMarqueeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Msg                 `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarqueeReply) Reset() {
	*x = GetMarqueeReply{}
	mi := &file_marqueepb_marquee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarqueeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarqueeReply) ProtoMessage() {}

func (x *GetMarqueeReply) ProtoReflect() protoreflect.Message {
	mi := &file_marqueepb_marquee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarqueeReply.ProtoReflect.Descriptor instead.
func (*GetMarqueeReply) Descriptor() ([]byte, []int) {
	return file_marqueepb_marquee_proto_rawDescGZIP(), []int{2}
}

func (x *GetMarqueeReply) GetMessages() []*Msg {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MarqueeNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Msg                 `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarqueeNotify) Reset() {
	*x = MarqueeNotify{}
	mi := &file_marqueepb_marquee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarqueeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarqueeNotify) ProtoMessage() {}

func (x *MarqueeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_marqueepb_marquee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarqueeNotify.ProtoReflect.Descriptor instead.
func (*MarqueeNotify) Descriptor() ([]byte, []int) {
	return file_marqueepb_marquee_proto_rawDescGZIP(), []int{3}
}

func (x *MarqueeNotify) GetMessages() []*Msg {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_marqueepb_marquee_proto protoreflect.FileDescriptor

const file_marqueepb_marquee_proto_rawDesc = "" +
	"\n" +
	"\x17marqueepb/marquee.proto\x12\x10gamepb.marqueepb\"\xc6\x01\n" +
	"\x03Msg\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\x03R\x04uuid\x12\x1b\n" +
	"\tconfig_id\x18\x02 \x01(\x05R\bconfigId\x12\x1f\n" +
	"\vexpire_time\x18\x03 \x01(\x03R\n" +
	"expireTime\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12#\n" +
	"\rdisplay_count\x18\a \x01(\x05R\fdisplayCount\"\x13\n" +
	"\x11GetMarqueeRequest\"D\n" +
	"\x0fGetMarqueeReply\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.gamepb.marqueepb.MsgR\bmessages\"B\n" +
	"\rMarqueeNotify\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.gamepb.marqueepb.MsgR\bmessages*2\n" +
	"\vMarqueeType\x12\x13\n" +
	"\x0fMARQUEE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"PERSISTENT\x10\x01B\x1dZ\x1bqq-farm-bot/proto/marqueepbb\x06proto3"

var (
	file_marqueepb_marquee_proto_rawDescOnce sync.Once
	file_marqueepb_marquee_proto_rawDescData []byte
)

func file_marqueepb_marquee_proto_rawDescGZIP() []byte {
	file_marqueepb_marquee_proto_rawDescOnce.Do(func() {
		file_marqueepb_marquee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marqueepb_marquee_proto_rawDesc), len(file_marqueepb_marquee_proto_rawDesc)))
	})
	return file_marqueepb_marquee_proto_rawDescData
}

var file_marqueepb_marquee_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_marqueepb_marquee_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_marqueepb_marquee_proto_goTypes = []any{
	(MarqueeType)(0),          // 0: gamepb.marqueepb.MarqueeType
	(*Msg)(nil),               // 1: gamepb.marqueepb.Msg
	(*GetMarqueeRequest)(nil), // 2: gamepb.marqueepb.GetMarqueeRequest
	(*GetMarqueeReply)(nil),   // 3: gamepb.marqueepb.GetMarqueeReply
	(*MarqueeNotify)(nil),     // 4: gamepb.marqueepb.MarqueeNotify
}
var file_marqueepb_marquee_proto_depIdxs = []int32{
	1, // 0: gamepb.marqueepb.GetMarqueeReply.messages:type_name -> gamepb.marqueepb.Msg
	1, // 1: gamepb.marqueepb.MarqueeNotify.messages:type_name -> gamepb.marqueepb.Msg
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_marqueepb_marquee_proto_init() }
func file_marqueepb_marquee_proto_init() {
	if File_marqueepb_marquee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marqueepb_marquee_proto_rawDesc), len(file_marqueepb_marquee_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marqueepb_marquee_proto_goTypes,
		DependencyIndexes: file_marqueepb_marquee_proto_depIdxs,
		EnumInfos:         file_marqueepb_marquee_proto_enumTypes,
		MessageInfos:      file_marqueepb_marquee_proto_msgTypes,
	}.Build()
	File_marqueepb_marquee_proto = out.File
	file_marqueepb_marquee_proto_goTypes = nil
	file_marqueepb_marquee_proto_depIdxs = nil
}
