// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: plantpb/plant.proto

package plantpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlantPhase int32

const (
	PlantPhase_PHASE_UNKNOWN PlantPhase = 0
	PlantPhase_SEED          PlantPhase = 1
	PlantPhase_GERMINATION   PlantPhase = 2
	PlantPhase_SMALL_LEAVES  PlantPhase = 3
	PlantPhase_LARGE_LEAVES  PlantPhase = 4
	PlantPhase_BLOOMING      PlantPhase = 5
	PlantPhase_MATURE        PlantPhase = 6
	PlantPhase_DEAD          PlantPhase = 7
)

// Enum value maps for PlantPhase.
var (
	PlantPhase_name = map[int32]string{
		0: "PHASE_UNKNOWN",
		1: "SEED",
		2: "GERMINATION",
		3: "SMALL_LEAVES",
		4: "LARGE_LEAVES",
		5: "BLOOMING",
		6: "MATURE",
		7: "DEAD",
	}
	PlantPhase_value = map[string]int32{
		"PHASE_UNKNOWN": 0,
		"SEED":          1,
		"GERMINATION":   2,
		"SMALL_LEAVES":  3,
		"LARGE_LEAVES":  4,
		"BLOOMING":      5,
		"MATURE":        6,
		"DEAD":          7,
	}
)

func (x PlantPhase) Enum() *PlantPhase {
	p := new(PlantPhase)
	*p = x
	return p
}

func (x PlantPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlantPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_plantpb_plant_proto_enumTypes[0].Descriptor()
}

func (PlantPhase) Type() protoreflect.EnumType {
	return &file_plantpb_plant_proto_enumTypes[0]
}

func (x PlantPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlantPhase.Descriptor instead.
func (PlantPhase) EnumDescriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{0}
}

type LandInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Unlocked         bool                   `protobuf:"varint,2,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	Level            int64                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	MaxLevel         int64                  `protobuf:"varint,4,opt,name=max_level,json=maxLevel,proto3" json:"max_level,omitempty"`
	CouldUnlock      bool                   `protobuf:"varint,5,opt,name=could_unlock,json=couldUnlock,proto3" json:"could_unlock,omitempty"`
	CouldUpgrade     bool                   `protobuf:"varint,6,opt,name=could_upgrade,json=couldUpgrade,proto3" json:"could_upgrade,omitempty"`
	UnlockCondition  *LandUnlockCondition   `protobuf:"bytes,7,opt,name=unlock_condition,json=unlockCondition,proto3" json:"unlock_condition,omitempty"`
	UpgradeCondition *LandUpgradeCondition  `protobuf:"bytes,8,opt,name=upgrade_condition,json=upgradeCondition,proto3" json:"upgrade_condition,omitempty"`
	Buff             *LandInfo_Buff         `protobuf:"bytes,9,opt,name=buff,proto3" json:"buff,omitempty"`
	Plant            *PlantInfo             `protobuf:"bytes,10,opt,name=plant,proto3" json:"plant,omitempty"`
	IsShared         bool                   `protobuf:"varint,11,opt,name=is_shared,json=isShared,proto3" json:"is_shared,omitempty"`
	CanShare         bool                   `protobuf:"varint,12,opt,name=can_share,json=canShare,proto3" json:"can_share,omitempty"`
	MasterLandId     int64                  `protobuf:"varint,13,opt,name=master_land_id,json=masterLandId,proto3" json:"master_land_id,omitempty"`
	SlaveLandIds     []int64                `protobuf:"varint,14,rep,packed,name=slave_land_ids,json=slaveLandIds,proto3" json:"slave_land_ids,omitempty"`
	LandSize         int64                  `protobuf:"varint,15,opt,name=land_size,json=landSize,proto3" json:"land_size,omitempty"`
	LandsLevel       int64                  `protobuf:"varint,16,opt,name=lands_level,json=landsLevel,proto3" json:"lands_level,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LandInfo) Reset() {
	*x = LandInfo{}
	mi := &file_plantpb_plant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandInfo) ProtoMessage() {}

func (x *LandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandInfo.ProtoReflect.Descriptor instead.
func (*LandInfo) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{0}
}

func (x *LandInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LandInfo) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

func (x *LandInfo) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LandInfo) GetMaxLevel() int64 {
	if x != nil {
		return x.MaxLevel
	}
	return 0
}

func (x *LandInfo) GetCouldUnlock() bool {
	if x != nil {
		return x.CouldUnlock
	}
	return false
}

func (x *LandInfo) GetCouldUpgrade() bool {
	if x != nil {
		return x.CouldUpgrade
	}
	return false
}

func (x *LandInfo) GetUnlockCondition() *LandUnlockCondition {
	if x != nil {
		return x.UnlockCondition
	}
	return nil
}

func (x *LandInfo) GetUpgradeCondition() *LandUpgradeCondition {
	if x != nil {
		return x.UpgradeCondition
	}
	return nil
}

func (x *LandInfo) GetBuff() *LandInfo_Buff {
	if x != nil {
		return x.Buff
	}
	return nil
}

func (x *LandInfo) GetPlant() *PlantInfo {
	if x != nil {
		return x.Plant
	}
	return nil
}

func (x *LandInfo) GetIsShared() bool {
	if x != nil {
		return x.IsShared
	}
	return false
}

func (x *LandInfo) GetCanShare() bool {
	if x != nil {
		return x.CanShare
	}
	return false
}

func (x *LandInfo) GetMasterLandId() int64 {
	if x != nil {
		return x.MasterLandId
	}
	return 0
}

func (x *LandInfo) GetSlaveLandIds() []int64 {
	if x != nil {
		return x.SlaveLandIds
	}
	return nil
}

func (x *LandInfo) GetLandSize() int64 {
	if x != nil {
		return x.LandSize
	}
	return 0
}

func (x *LandInfo) GetLandsLevel() int64 {
	if x != nil {
		return x.LandsLevel
	}
	return 0
}

type LandUnlockCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeedLevel     int64                  `protobuf:"varint,1,opt,name=need_level,json=needLevel,proto3" json:"need_level,omitempty"`
	NeedGold      int64                  `protobuf:"varint,2,opt,name=need_gold,json=needGold,proto3" json:"need_gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandUnlockCondition) Reset() {
	*x = LandUnlockCondition{}
	mi := &file_plantpb_plant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandUnlockCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandUnlockCondition) ProtoMessage() {}

func (x *LandUnlockCondition) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandUnlockCondition.ProtoReflect.Descriptor instead.
func (*LandUnlockCondition) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{1}
}

func (x *LandUnlockCondition) GetNeedLevel() int64 {
	if x != nil {
		return x.NeedLevel
	}
	return 0
}

func (x *LandUnlockCondition) GetNeedGold() int64 {
	if x != nil {
		return x.NeedGold
	}
	return 0
}

type LandUpgradeCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeedLevel     int64                  `protobuf:"varint,1,opt,name=need_level,json=needLevel,proto3" json:"need_level,omitempty"`
	NeedGold      int64                  `protobuf:"varint,2,opt,name=need_gold,json=needGold,proto3" json:"need_gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandUpgradeCondition) Reset() {
	*x = LandUpgradeCondition{}
	mi := &file_plantpb_plant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandUpgradeCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandUpgradeCondition) ProtoMessage() {}

func (x *LandUpgradeCondition) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandUpgradeCondition.ProtoReflect.Descriptor instead.
func (*LandUpgradeCondition) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{2}
}

func (x *LandUpgradeCondition) GetNeedLevel() int64 {
	if x != nil {
		return x.NeedLevel
	}
	return 0
}

func (x *LandUpgradeCondition) GetNeedGold() int64 {
	if x != nil {
		return x.NeedGold
	}
	return 0
}

type PlantInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phases             []*PlantPhaseInfo      `protobuf:"bytes,4,rep,name=phases,proto3" json:"phases,omitempty"`
	Season             int64                  `protobuf:"varint,5,opt,name=season,proto3" json:"season,omitempty"`
	DryNum             int64                  `protobuf:"varint,6,opt,name=dry_num,json=dryNum,proto3" json:"dry_num,omitempty"`
	StoleNum           int64                  `protobuf:"varint,9,opt,name=stole_num,json=stoleNum,proto3" json:"stole_num,omitempty"`
	FruitId            int64                  `protobuf:"varint,10,opt,name=fruit_id,json=fruitId,proto3" json:"fruit_id,omitempty"`
	FruitNum           int64                  `protobuf:"varint,11,opt,name=fruit_num,json=fruitNum,proto3" json:"fruit_num,omitempty"`
	WeedOwners         []int64                `protobuf:"varint,12,rep,packed,name=weed_owners,json=weedOwners,proto3" json:"weed_owners,omitempty"`
	InsectOwners       []int64                `protobuf:"varint,13,rep,packed,name=insect_owners,json=insectOwners,proto3" json:"insect_owners,omitempty"`
	Stealers           []int64                `protobuf:"varint,14,rep,packed,name=stealers,proto3" json:"stealers,omitempty"`
	GrowSec            int64                  `protobuf:"varint,15,opt,name=grow_sec,json=growSec,proto3" json:"grow_sec,omitempty"`
	Stealable          bool                   `protobuf:"varint,16,opt,name=stealable,proto3" json:"stealable,omitempty"`
	LeftInorcFertTimes int64                  `protobuf:"varint,17,opt,name=left_inorc_fert_times,json=leftInorcFertTimes,proto3" json:"left_inorc_fert_times,omitempty"`
	LeftFruitNum       int64                  `protobuf:"varint,18,opt,name=left_fruit_num,json=leftFruitNum,proto3" json:"left_fruit_num,omitempty"`
	StealIntimacyLevel int64                  `protobuf:"varint,19,opt,name=steal_intimacy_level,json=stealIntimacyLevel,proto3" json:"steal_intimacy_level,omitempty"`
	MutantConfigIds    []int64                `protobuf:"varint,20,rep,packed,name=mutant_config_ids,json=mutantConfigIds,proto3" json:"mutant_config_ids,omitempty"`
	IsNudged           bool                   `protobuf:"varint,21,opt,name=is_nudged,json=isNudged,proto3" json:"is_nudged,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PlantInfo) Reset() {
	*x = PlantInfo{}
	mi := &file_plantpb_plant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantInfo) ProtoMessage() {}

func (x *PlantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantInfo.ProtoReflect.Descriptor instead.
func (*PlantInfo) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{3}
}

func (x *PlantInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlantInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlantInfo) GetPhases() []*PlantPhaseInfo {
	if x != nil {
		return x.Phases
	}
	return nil
}

func (x *PlantInfo) GetSeason() int64 {
	if x != nil {
		return x.Season
	}
	return 0
}

func (x *PlantInfo) GetDryNum() int64 {
	if x != nil {
		return x.DryNum
	}
	return 0
}

func (x *PlantInfo) GetStoleNum() int64 {
	if x != nil {
		return x.StoleNum
	}
	return 0
}

func (x *PlantInfo) GetFruitId() int64 {
	if x != nil {
		return x.FruitId
	}
	return 0
}

func (x *PlantInfo) GetFruitNum() int64 {
	if x != nil {
		return x.FruitNum
	}
	return 0
}

func (x *PlantInfo) GetWeedOwners() []int64 {
	if x != nil {
		return x.WeedOwners
	}
	return nil
}

func (x *PlantInfo) GetInsectOwners() []int64 {
	if x != nil {
		return x.InsectOwners
	}
	return nil
}

func (x *PlantInfo) GetStealers() []int64 {
	if x != nil {
		return x.Stealers
	}
	return nil
}

func (x *PlantInfo) GetGrowSec() int64 {
	if x != nil {
		return x.GrowSec
	}
	return 0
}

func (x *PlantInfo) GetStealable() bool {
	if x != nil {
		return x.Stealable
	}
	return false
}

func (x *PlantInfo) GetLeftInorcFertTimes() int64 {
	if x != nil {
		return x.LeftInorcFertTimes
	}
	return 0
}

func (x *PlantInfo) GetLeftFruitNum() int64 {
	if x != nil {
		return x.LeftFruitNum
	}
	return 0
}

func (x *PlantInfo) GetStealIntimacyLevel() int64 {
	if x != nil {
		return x.StealIntimacyLevel
	}
	return 0
}

func (x *PlantInfo) GetMutantConfigIds() []int64 {
	if x != nil {
		return x.MutantConfigIds
	}
	return nil
}

func (x *PlantInfo) GetIsNudged() bool {
	if x != nil {
		return x.IsNudged
	}
	return false
}

type PlantPhaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         int32                  `protobuf:"varint,1,opt,name=phase,proto3" json:"phase,omitempty"`
	BeginTime     int64                  `protobuf:"varint,2,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	PhaseId       int64                  `protobuf:"varint,3,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
	DryTime       int64                  `protobuf:"varint,6,opt,name=dry_time,json=dryTime,proto3" json:"dry_time,omitempty"`
	WeedsTime     int64                  `protobuf:"varint,7,opt,name=weeds_time,json=weedsTime,proto3" json:"weeds_time,omitempty"`
	InsectTime    int64                  `protobuf:"varint,8,opt,name=insect_time,json=insectTime,proto3" json:"insect_time,omitempty"`
	FertsUsed     map[int64]int64        `protobuf:"bytes,9,rep,name=ferts_used,json=fertsUsed,proto3" json:"ferts_used,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Mutants       []*MutantInfo          `protobuf:"bytes,10,rep,name=mutants,proto3" json:"mutants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlantPhaseInfo) Reset() {
	*x = PlantPhaseInfo{}
	mi := &file_plantpb_plant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlantPhaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantPhaseInfo) ProtoMessage() {}

func (x *PlantPhaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantPhaseInfo.ProtoReflect.Descriptor instead.
func (*PlantPhaseInfo) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{4}
}

func (x *PlantPhaseInfo) GetPhase() int32 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *PlantPhaseInfo) GetBeginTime() int64 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *PlantPhaseInfo) GetPhaseId() int64 {
	if x != nil {
		return x.PhaseId
	}
	return 0
}

func (x *PlantPhaseInfo) GetDryTime() int64 {
	if x != nil {
		return x.DryTime
	}
	return 0
}

func (x *PlantPhaseInfo) GetWeedsTime() int64 {
	if x != nil {
		return x.WeedsTime
	}
	return 0
}

func (x *PlantPhaseInfo) GetInsectTime() int64 {
	if x != nil {
		return x.InsectTime
	}
	return 0
}

func (x *PlantPhaseInfo) GetFertsUsed() map[int64]int64 {
	if x != nil {
		return x.FertsUsed
	}
	return nil
}

func (x *PlantPhaseInfo) GetMutants() []*MutantInfo {
	if x != nil {
		return x.Mutants
	}
	return nil
}

type MutantInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MutantTime     int64                  `protobuf:"varint,1,opt,name=mutant_time,json=mutantTime,proto3" json:"mutant_time,omitempty"`
	MutantConfigId int64                  `protobuf:"varint,2,opt,name=mutant_config_id,json=mutantConfigId,proto3" json:"mutant_config_id,omitempty"`
	WeatherId      int64                  `protobuf:"varint,3,opt,name=weather_id,json=weatherId,proto3" json:"weather_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MutantInfo) Reset() {
	*x = MutantInfo{}
	mi := &file_plantpb_plant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutantInfo) ProtoMessage() {}

func (x *MutantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutantInfo.ProtoReflect.Descriptor instead.
func (*MutantInfo) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{5}
}

func (x *MutantInfo) GetMutantTime() int64 {
	if x != nil {
		return x.MutantTime
	}
	return 0
}

func (x *MutantInfo) GetMutantConfigId() int64 {
	if x != nil {
		return x.MutantConfigId
	}
	return 0
}

func (x *MutantInfo) GetWeatherId() int64 {
	if x != nil {
		return x.WeatherId
	}
	return 0
}

type OperationLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DayTimes      int64                  `protobuf:"varint,2,opt,name=day_times,json=dayTimes,proto3" json:"day_times,omitempty"`
	DayTimesLt    int64                  `protobuf:"varint,3,opt,name=day_times_lt,json=dayTimesLt,proto3" json:"day_times_lt,omitempty"`
	DayShareId    int64                  `protobuf:"varint,4,opt,name=day_share_id,json=dayShareId,proto3" json:"day_share_id,omitempty"`
	DayExpTimes   int64                  `protobuf:"varint,5,opt,name=day_exp_times,json=dayExpTimes,proto3" json:"day_exp_times,omitempty"`
	DayExTimesLt  int64                  `protobuf:"varint,6,opt,name=day_ex_times_lt,json=dayExTimesLt,proto3" json:"day_ex_times_lt,omitempty"`
	DayExpShareId int64                  `protobuf:"varint,7,opt,name=day_exp_share_id,json=dayExpShareId,proto3" json:"day_exp_share_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationLimit) Reset() {
	*x = OperationLimit{}
	mi := &file_plantpb_plant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationLimit) ProtoMessage() {}

func (x *OperationLimit) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationLimit.ProtoReflect.Descriptor instead.
func (*OperationLimit) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{6}
}

func (x *OperationLimit) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OperationLimit) GetDayTimes() int64 {
	if x != nil {
		return x.DayTimes
	}
	return 0
}

func (x *OperationLimit) GetDayTimesLt() int64 {
	if x != nil {
		return x.DayTimesLt
	}
	return 0
}

func (x *OperationLimit) GetDayShareId() int64 {
	if x != nil {
		return x.DayShareId
	}
	return 0
}

func (x *OperationLimit) GetDayExpTimes() int64 {
	if x != nil {
		return x.DayExpTimes
	}
	return 0
}

func (x *OperationLimit) GetDayExTimesLt() int64 {
	if x != nil {
		return x.DayExTimesLt
	}
	return 0
}

func (x *OperationLimit) GetDayExpShareId() int64 {
	if x != nil {
		return x.DayExpShareId
	}
	return 0
}

type AllLandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostGid       int64                  `protobuf:"varint,1,opt,name=host_gid,json=hostGid,proto3" json:"host_gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllLandsRequest) Reset() {
	*x = AllLandsRequest{}
	mi := &file_plantpb_plant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllLandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllLandsRequest) ProtoMessage() {}

func (x *AllLandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllLandsRequest.ProtoReflect.Descriptor instead.
func (*AllLandsRequest) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{7}
}

func (x *AllLandsRequest) GetHostGid() int64 {
	if x != nil {
		return x.HostGid
	}
	return 0
}

type AllLandsReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Lands           []*LandInfo            `protobuf:"bytes,1,rep,name=lands,proto3" json:"lands,omitempty"`
	OperationLimits []*OperationLimit      `protobuf:"bytes,2,rep,name=operation_limits,json=operationLimits,proto3" json:"operation_limits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AllLandsReply) Reset() {
	*x = AllLandsReply{}
	mi := &file_plantpb_plant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllLandsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllLandsReply) ProtoMessage() {}

func (x *AllLandsReply) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllLandsReply.ProtoReflect.Descriptor instead.
func (*AllLandsReply) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{8}
}

func (x *AllLandsReply) GetLands() []*LandInfo {
	if x != nil {
		return x.Lands
	}
	return nil
}

func (x *AllLandsReply) GetOperationLimits() []*OperationLimit {
	if x != nil {
		return x.OperationLimits
	}
	return nil
}

type HarvestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandIds       []int64                `protobuf:"varint,1,rep,packed,name=land_ids,json=landIds,proto3" json:"land_ids,omitempty"`
	HostGid       int64                  `protobuf:"varint,2,opt,name=host_gid,json=hostGid,proto3" json:"host_gid,omitempty"`
	IsAll         bool                   `protobuf:"varint,3,opt,name=is_all,json=isAll,proto3" json:"is_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarvestRequest) Reset() {
	*x = HarvestRequest{}
	mi := &file_plantpb_plant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarvestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarvestRequest) ProtoMessage() {}

func (x *HarvestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarvestRequest.ProtoReflect.Descriptor instead.
func (*HarvestRequest) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{9}
}

func (x *HarvestRequest) GetLandIds() []int64 {
	if x != nil {
		return x.LandIds
	}
	return nil
}

func (x *HarvestRequest) GetHostGid() int64 {
	if x != nil {
		return x.HostGid
	}
	return 0
}

func (x *HarvestRequest) GetIsAll() bool {
	if x != nil {
		return x.IsAll
	}
	return false
}

type HarvestReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Land            []*LandInfo            `protobuf:"bytes,1,rep,name=land,proto3" json:"land,omitempty"`
	OperationLimits []*OperationLimit      `protobuf:"bytes,4,rep,name=operation_limits,json=operationLimits,proto3" json:"operation_limits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HarvestReply) Reset() {
	*x = HarvestReply{}
	mi := &file_plantpb_plant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarvestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarvestReply) ProtoMessage() {}

func (x *HarvestReply) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarvestReply.ProtoReflect.Descriptor instead.
func (*HarvestReply) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{10}
}

func (x *HarvestReply) GetLand() []*LandInfo {
	if x != nil {
		return x.Land
	}
	return nil
}

func (x *HarvestReply) GetOperationLimits() []*OperationLimit {
	if x != nil {
		return x.OperationLimits
	}
	return nil
}

type WaterLandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandIds       []int64                `protobuf:"varint,1,rep,packed,name=land_ids,json=landIds,proto3" json:"land_ids,omitempty"`
	HostGid       int64                  `protobuf:"varint,2,opt,name=host_gid,json=hostGid,proto3" json:"host_gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaterLandRequest) Reset() {
	*x = WaterLandRequest{}
	mi := &file_plantpb_plant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaterLandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaterLandRequest) ProtoMessage() {}

func (x *WaterLandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaterLandRequest.ProtoReflect.Descriptor instead.
func (*WaterLandRequest) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{11}
}

func (x *WaterLandRequest) GetLandIds() []int64 {
	if x != nil {
		return x.LandIds
	}
	return nil
}

func (x *WaterLandRequest) GetHostGid() int64 {
	if x != nil {
		return x.HostGid
	}
	return 0
}

type WaterLandReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Land            []*LandInfo            `protobuf:"bytes,1,rep,name=land,proto3" json:"land,omitempty"`
	OperationLimits []*OperationLimit      `protobuf:"bytes,2,rep,name=operation_limits,json=operationLimits,proto3" json:"operation_limits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WaterLandReply) Reset() {
	*x = WaterLandReply{}
	mi := &file_plantpb_plant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaterLandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaterLandReply) ProtoMessage() {}

func (x *WaterLandReply) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaterLandReply.ProtoReflect.Descriptor instead.
func (*WaterLandReply) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{12}
}

func (x *WaterLandReply) GetLand() []*LandInfo {
	if x != nil {
		return x.Land
	}
	return nil
}

func (x *WaterLandReply) GetOperationLimits() []*OperationLimit {
	if x != nil {
		return x.OperationLimits
	}
	return nil
}

type WeedOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandIds       []int64                `protobuf:"varint,1,rep,packed,name=land_ids,json=landIds,proto3" json:"land_ids,omitempty"`
	HostGid       int64                  `protobuf:"varint,2,opt,name=host_gid,json=hostGid,proto3" json:"host_gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeedOutRequest) Reset() {
	*x = WeedOutRequest{}
	mi := &file_plantpb_plant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeedOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeedOutRequest) ProtoMessage() {}

func (x *WeedOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeedOutRequest.ProtoReflect.Descriptor instead.
func (*WeedOutRequest) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{13}
}

func (x *WeedOutRequest) GetLandIds() []int64 {
	if x != nil {
		return x.LandIds
	}
	return nil
}

func (x *WeedOutRequest) GetHostGid() int64 {
	if x != nil {
		return x.HostGid
	}
	return 0
}

type WeedOutReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Land            []*LandInfo            `protobuf:"bytes,1,rep,name=land,proto3" json:"land,omitempty"`
	OperationLimits []*OperationLimit      `protobuf:"bytes,2,rep,name=operation_limits,json=operationLimits,proto3" json:"operation_limits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WeedOutReply) Reset() {
	*x = WeedOutReply{}
	mi := &file_plantpb_plant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeedOutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeedOutReply) ProtoMessage() {}

func (x *WeedOutReply) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeedOutReply.ProtoReflect.Descriptor instead.
func (*WeedOutReply) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{14}
}

func (x *WeedOutReply) GetLand() []*LandInfo {
	if x != nil {
		return x.Land
	}
	return nil
}

func (x *WeedOutReply) GetOperationLimits() []*OperationLimit {
	if x != nil {
		return x.OperationLimits
	}
	return nil
}

type InsecticideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandIds       []int64                `protobuf:"varint,1,rep,packed,name=land_ids,json=landIds,proto3" json:"land_ids,omitempty"`
	HostGid       int64                  `protobuf:"varint,2,opt,name=host_gid,json=hostGid,proto3" json:"host_gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsecticideRequest) Reset() {
	*x = InsecticideRequest{}
	mi := &file_plantpb_plant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsecticideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsecticideRequest) ProtoMessage() {}

func (x *InsecticideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsecticideRequest.ProtoReflect.Descriptor instead.
func (*InsecticideRequest) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{15}
}

func (x *InsecticideRequest) GetLandIds() []int64 {
	if x != nil {
		return x.LandIds
	}
	return nil
}

func (x *InsecticideRequest) GetHostGid() int64 {
	if x != nil {
		return x.HostGid
	}
	return 0
}

type InsecticideReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Land            []*LandInfo            `protobuf:"bytes,1,rep,name=land,proto3" json:"land,omitempty"`
	OperationLimits []*OperationLimit      `protobuf:"bytes,2,rep,name=operation_limits,json=operationLimits,proto3" json:"operation_limits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InsecticideReply) Reset() {
	*x = InsecticideReply{}
	mi := &file_plantpb_plant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsecticideReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsecticideReply) ProtoMessage() {}

func (x *InsecticideReply) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsecticideReply.ProtoReflect.Descriptor instead.
func (*InsecticideReply) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{16}
}

func (x *InsecticideReply) GetLand() []*LandInfo {
	if x != nil {
		return x.Land
	}
	return nil
}

func (x *InsecticideReply) GetOperationLimits() []*OperationLimit {
	if x != nil {
		return x.OperationLimits
	}
	return nil
}

type PlantItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeedId        int64                  `protobuf:"varint,1,opt,name=seed_id,json=seedId,proto3" json:"seed_id,omitempty"`
	LandIds       []int64                `protobuf:"varint,2,rep,packed,name=land_ids,json=landIds,proto3" json:"land_ids,omitempty"`
	AutoSlave     bool                   `protobuf:"varint,3,opt,name=auto_slave,json=autoSlave,proto3" json:"auto_slave,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlantItem) Reset() {
	*x = PlantItem{}
	mi := &file_plantpb_plant_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlantItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantItem) ProtoMessage() {}

func (x *PlantItem) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantItem.ProtoReflect.Descriptor instead.
func (*PlantItem) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{17}
}

func (x *PlantItem) GetSeedId() int64 {
	if x != nil {
		return x.SeedId
	}
	return 0
}

func (x *PlantItem) GetLandIds() []int64 {
	if x != nil {
		return x.LandIds
	}
	return nil
}

func (x *PlantItem) GetAutoSlave() bool {
	if x != nil {
		return x.AutoSlave
	}
	return false
}

type PlantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandAndSeed   map[int64]int64        `protobuf:"bytes,1,rep,name=land_and_seed,json=landAndSeed,proto3" json:"land_and_seed,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Items         []*PlantItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlantRequest) Reset() {
	*x = PlantRequest{}
	mi := &file_plantpb_plant_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantRequest) ProtoMessage() {}

func (x *PlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantRequest.ProtoReflect.Descriptor instead.
func (*PlantRequest) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{18}
}

func (x *PlantRequest) GetLandAndSeed() map[int64]int64 {
	if x != nil {
		return x.LandAndSeed
	}
	return nil
}

func (x *PlantRequest) GetItems() []*PlantItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PlantReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Land            []*LandInfo            `protobuf:"bytes,1,rep,name=land,proto3" json:"land,omitempty"`
	OperationLimits []*OperationLimit      `protobuf:"bytes,2,rep,name=operation_limits,json=operationLimits,proto3" json:"operation_limits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlantReply) Reset() {
	*x = PlantReply{}
	mi := &file_plantpb_plant_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantReply) ProtoMessage() {}

func (x *PlantReply) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantReply.ProtoReflect.Descriptor instead.
func (*PlantReply) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{19}
}

func (x *PlantReply) GetLand() []*LandInfo {
	if x != nil {
		return x.Land
	}
	return nil
}

func (x *PlantReply) GetOperationLimits() []*OperationLimit {
	if x != nil {
		return x.OperationLimits
	}
	return nil
}

type RemovePlantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandIds       []int64                `protobuf:"varint,1,rep,packed,name=land_ids,json=landIds,proto3" json:"land_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePlantRequest) Reset() {
	*x = RemovePlantRequest{}
	mi := &file_plantpb_plant_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePlantRequest) ProtoMessage() {}

func (x *RemovePlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePlantRequest.ProtoReflect.Descriptor instead.
func (*RemovePlantRequest) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{20}
}

func (x *RemovePlantRequest) GetLandIds() []int64 {
	if x != nil {
		return x.LandIds
	}
	return nil
}

type RemovePlantReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Land            []*LandInfo            `protobuf:"bytes,1,rep,name=land,proto3" json:"land,omitempty"`
	OperationLimits []*OperationLimit      `protobuf:"bytes,2,rep,name=operation_limits,json=operationLimits,proto3" json:"operation_limits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemovePlantReply) Reset() {
	*x = RemovePlantReply{}
	mi := &file_plantpb_plant_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePlantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePlantReply) ProtoMessage() {}

func (x *RemovePlantReply) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePlantReply.ProtoReflect.Descriptor instead.
func (*RemovePlantReply) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{21}
}

func (x *RemovePlantReply) GetLand() []*LandInfo {
	if x != nil {
		return x.Land
	}
	return nil
}

func (x *RemovePlantReply) GetOperationLimits() []*OperationLimit {
	if x != nil {
		return x.OperationLimits
	}
	return nil
}

type FertilizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandIds       []int64                `protobuf:"varint,1,rep,packed,name=land_ids,json=landIds,proto3" json:"land_ids,omitempty"`
	FertilizerId  int64                  `protobuf:"varint,2,opt,name=fertilizer_id,json=fertilizerId,proto3" json:"fertilizer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FertilizeRequest) Reset() {
	*x = FertilizeRequest{}
	mi := &file_plantpb_plant_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FertilizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FertilizeRequest) ProtoMessage() {}

func (x *FertilizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FertilizeRequest.ProtoReflect.Descriptor instead.
func (*FertilizeRequest) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{22}
}

func (x *FertilizeRequest) GetLandIds() []int64 {
	if x != nil {
		return x.LandIds
	}
	return nil
}

func (x *FertilizeRequest) GetFertilizerId() int64 {
	if x != nil {
		return x.FertilizerId
	}
	return 0
}

type FertilizeReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Land            []*LandInfo            `protobuf:"bytes,1,rep,name=land,proto3" json:"land,omitempty"`
	OperationLimits []*OperationLimit      `protobuf:"bytes,2,rep,name=operation_limits,json=operationLimits,proto3" json:"operation_limits,omitempty"`
	Fertilizer      int64                  `protobuf:"varint,3,opt,name=fertilizer,proto3" json:"fertilizer,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FertilizeReply) Reset() {
	*x = FertilizeReply{}
	mi := &file_plantpb_plant_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FertilizeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FertilizeReply) ProtoMessage() {}

func (x *FertilizeReply) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FertilizeReply.ProtoReflect.Descriptor instead.
func (*FertilizeReply) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{23}
}

func (x *FertilizeReply) GetLand() []*LandInfo {
	if x != nil {
		return x.Land
	}
	return nil
}

func (x *FertilizeReply) GetOperationLimits() []*OperationLimit {
	if x != nil {
		return x.OperationLimits
	}
	return nil
}

func (x *FertilizeReply) GetFertilizer() int64 {
	if x != nil {
		return x.Fertilizer
	}
	return 0
}

type PutInsectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandIds       []int64                `protobuf:"varint,1,rep,packed,name=land_ids,json=landIds,proto3" json:"land_ids,omitempty"`
	HostGid       int64                  `protobuf:"varint,2,opt,name=host_gid,json=hostGid,proto3" json:"host_gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutInsectsRequest) Reset() {
	*x = PutInsectsRequest{}
	mi := &file_plantpb_plant_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutInsectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutInsectsRequest) ProtoMessage() {}

func (x *PutInsectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutInsectsRequest.ProtoReflect.Descriptor instead.
func (*PutInsectsRequest) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{24}
}

func (x *PutInsectsRequest) GetLandIds() []int64 {
	if x != nil {
		return x.LandIds
	}
	return nil
}

func (x *PutInsectsRequest) GetHostGid() int64 {
	if x != nil {
		return x.HostGid
	}
	return 0
}

type PutInsectsReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Land            []*LandInfo            `protobuf:"bytes,1,rep,name=land,proto3" json:"land,omitempty"`
	OperationLimits []*OperationLimit      `protobuf:"bytes,2,rep,name=operation_limits,json=operationLimits,proto3" json:"operation_limits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PutInsectsReply) Reset() {
	*x = PutInsectsReply{}
	mi := &file_plantpb_plant_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutInsectsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutInsectsReply) ProtoMessage() {}

func (x *PutInsectsReply) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutInsectsReply.ProtoReflect.Descriptor instead.
func (*PutInsectsReply) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{25}
}

func (x *PutInsectsReply) GetLand() []*LandInfo {
	if x != nil {
		return x.Land
	}
	return nil
}

func (x *PutInsectsReply) GetOperationLimits() []*OperationLimit {
	if x != nil {
		return x.OperationLimits
	}
	return nil
}

type PutWeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandIds       []int64                `protobuf:"varint,1,rep,packed,name=land_ids,json=landIds,proto3" json:"land_ids,omitempty"`
	HostGid       int64                  `protobuf:"varint,2,opt,name=host_gid,json=hostGid,proto3" json:"host_gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutWeedsRequest) Reset() {
	*x = PutWeedsRequest{}
	mi := &file_plantpb_plant_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutWeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutWeedsRequest) ProtoMessage() {}

func (x *PutWeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutWeedsRequest.ProtoReflect.Descriptor instead.
func (*PutWeedsRequest) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{26}
}

func (x *PutWeedsRequest) GetLandIds() []int64 {
	if x != nil {
		return x.LandIds
	}
	return nil
}

func (x *PutWeedsRequest) GetHostGid() int64 {
	if x != nil {
		return x.HostGid
	}
	return 0
}

type PutWeedsReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Land            []*LandInfo            `protobuf:"bytes,1,rep,name=land,proto3" json:"land,omitempty"`
	OperationLimits []*OperationLimit      `protobuf:"bytes,2,rep,name=operation_limits,json=operationLimits,proto3" json:"operation_limits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PutWeedsReply) Reset() {
	*x = PutWeedsReply{}
	mi := &file_plantpb_plant_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutWeedsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutWeedsReply) ProtoMessage() {}

func (x *PutWeedsReply) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutWeedsReply.ProtoReflect.Descriptor instead.
func (*PutWeedsReply) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{27}
}

func (x *PutWeedsReply) GetLand() []*LandInfo {
	if x != nil {
		return x.Land
	}
	return nil
}

func (x *PutWeedsReply) GetOperationLimits() []*OperationLimit {
	if x != nil {
		return x.OperationLimits
	}
	return nil
}

type LandsNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lands         []*LandInfo            `protobuf:"bytes,1,rep,name=lands,proto3" json:"lands,omitempty"`
	HostGid       int64                  `protobuf:"varint,2,opt,name=host_gid,json=hostGid,proto3" json:"host_gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandsNotify) Reset() {
	*x = LandsNotify{}
	mi := &file_plantpb_plant_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandsNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandsNotify) ProtoMessage() {}

func (x *LandsNotify) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandsNotify.ProtoReflect.Descriptor instead.
func (*LandsNotify) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{28}
}

func (x *LandsNotify) GetLands() []*LandInfo {
	if x != nil {
		return x.Lands
	}
	return nil
}

func (x *LandsNotify) GetHostGid() int64 {
	if x != nil {
		return x.HostGid
	}
	return 0
}

type UnlockLandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandId        int64                  `protobuf:"varint,1,opt,name=land_id,json=landId,proto3" json:"land_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockLandRequest) Reset() {
	*x = UnlockLandRequest{}
	mi := &file_plantpb_plant_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockLandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockLandRequest) ProtoMessage() {}

func (x *UnlockLandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockLandRequest.ProtoReflect.Descriptor instead.
func (*UnlockLandRequest) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{29}
}

func (x *UnlockLandRequest) GetLandId() int64 {
	if x != nil {
		return x.LandId
	}
	return 0
}

type UnlockLandReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Land          []*LandInfo            `protobuf:"bytes,1,rep,name=land,proto3" json:"land,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockLandReply) Reset() {
	*x = UnlockLandReply{}
	mi := &file_plantpb_plant_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockLandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockLandReply) ProtoMessage() {}

func (x *UnlockLandReply) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockLandReply.ProtoReflect.Descriptor instead.
func (*UnlockLandReply) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{30}
}

func (x *UnlockLandReply) GetLand() []*LandInfo {
	if x != nil {
		return x.Land
	}
	return nil
}

type UpgradeLandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandId        int64                  `protobuf:"varint,1,opt,name=land_id,json=landId,proto3" json:"land_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeLandRequest) Reset() {
	*x = UpgradeLandRequest{}
	mi := &file_plantpb_plant_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeLandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeLandRequest) ProtoMessage() {}

func (x *UpgradeLandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeLandRequest.ProtoReflect.Descriptor instead.
func (*UpgradeLandRequest) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{31}
}

func (x *UpgradeLandRequest) GetLandId() int64 {
	if x != nil {
		return x.LandId
	}
	return 0
}

type UpgradeLandReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Land          []*LandInfo            `protobuf:"bytes,1,rep,name=land,proto3" json:"land,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeLandReply) Reset() {
	*x = UpgradeLandReply{}
	mi := &file_plantpb_plant_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeLandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeLandReply) ProtoMessage() {}

func (x *UpgradeLandReply) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeLandReply.ProtoReflect.Descriptor instead.
func (*UpgradeLandReply) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{32}
}

func (x *UpgradeLandReply) GetLand() []*LandInfo {
	if x != nil {
		return x.Land
	}
	return nil
}

type LandInfo_Buff struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PlantYieldBonus       int64                  `protobuf:"varint,1,opt,name=plant_yield_bonus,json=plantYieldBonus,proto3" json:"plant_yield_bonus,omitempty"`
	PlantingTimeReduction int64                  `protobuf:"varint,2,opt,name=planting_time_reduction,json=plantingTimeReduction,proto3" json:"planting_time_reduction,omitempty"`
	PlantExpBonus         int64                  `protobuf:"varint,3,opt,name=plant_exp_bonus,json=plantExpBonus,proto3" json:"plant_exp_bonus,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LandInfo_Buff) Reset() {
	*x = LandInfo_Buff{}
	mi := &file_plantpb_plant_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandInfo_Buff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandInfo_Buff) ProtoMessage() {}

func (x *LandInfo_Buff) ProtoReflect() protoreflect.Message {
	mi := &file_plantpb_plant_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandInfo_Buff.ProtoReflect.Descriptor instead.
func (*LandInfo_Buff) Descriptor() ([]byte, []int) {
	return file_plantpb_plant_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LandInfo_Buff) GetPlantYieldBonus() int64 {
	if x != nil {
		return x.PlantYieldBonus
	}
	return 0
}

func (x *LandInfo_Buff) GetPlantingTimeReduction() int64 {
	if x != nil {
		return x.PlantingTimeReduction
	}
	return 0
}

func (x *LandInfo_Buff) GetPlantExpBonus() int64 {
	if x != nil {
		return x.PlantExpBonus
	}
	return 0
}

var File_plantpb_plant_proto protoreflect.FileDescriptor

const file_plantpb_plant_proto_rawDesc = "" +
	"\n" +
	"\x13plantpb/plant.proto\x12\x0egamepb.plantpb\"\x91\x06\n" +
	"\bLandInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bunlocked\x18\x02 \x01(\bR\bunlocked\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x03R\x05level\x12\x1b\n" +
	"\tmax_level\x18\x04 \x01(\x03R\bmaxLevel\x12!\n" +
	"\fcould_unlock\x18\x05 \x01(\bR\vcouldUnlock\x12#\n" +
	"\rcould_upgrade\x18\x06 \x01(\bR\fcouldUpgrade\x12N\n" +
	"\x10unlock_condition\x18\a \x01(\v2#.gamepb.plantpb.LandUnlockConditionR\x0funlockCondition\x12Q\n" +
	"\x11upgrade_condition\x18\b \x01(\v2$.gamepb.plantpb.LandUpgradeConditionR\x10upgradeCondition\x121\n" +
	"\x04buff\x18\t \x01(\v2\x1d.gamepb.plantpb.LandInfo.BuffR\x04buff\x12/\n" +
	"\x05plant\x18\n" +
	" \x01(\v2\x19.gamepb.plantpb.PlantInfoR\x05plant\x12\x1b\n" +
	"\tis_shared\x18\v \x01(\bR\bisShared\x12\x1b\n" +
	"\tcan_share\x18\f \x01(\bR\bcanShare\x12$\n" +
	"\x0emaster_land_id\x18\r \x01(\x03R\fmasterLandId\x12$\n" +
	"\x0eslave_land_ids\x18\x0e \x03(\x03R\fslaveLandIds\x12\x1b\n" +
	"\tland_size\x18\x0f \x01(\x03R\blandSize\x12\x1f\n" +
	"\vlands_level\x18\x10 \x01(\x03R\n" +
	"landsLevel\x1a\x92\x01\n" +
	"\x04Buff\x12*\n" +
	"\x11plant_yield_bonus\x18\x01 \x01(\x03R\x0fplantYieldBonus\x126\n" +
	"\x17planting_time_reduction\x18\x02 \x01(\x03R\x15plantingTimeReduction\x12&\n" +
	"\x0fplant_exp_bonus\x18\x03 \x01(\x03R\rplantExpBonus\"Q\n" +
	"\x13LandUnlockCondition\x12\x1d\n" +
	"\n" +
	"need_level\x18\x01 \x01(\x03R\tneedLevel\x12\x1b\n" +
	"\tneed_gold\x18\x02 \x01(\x03R\bneedGold\"R\n" +
	"\x14LandUpgradeCondition\x12\x1d\n" +
	"\n" +
	"need_level\x18\x01 \x01(\x03R\tneedLevel\x12\x1b\n" +
	"\tneed_gold\x18\x02 \x01(\x03R\bneedGold\"\xdc\x04\n" +
	"\tPlantInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\x06phases\x18\x04 \x03(\v2\x1e.gamepb.plantpb.PlantPhaseInfoR\x06phases\x12\x16\n" +
	"\x06season\x18\x05 \x01(\x03R\x06season\x12\x17\n" +
	"\adry_num\x18\x06 \x01(\x03R\x06dryNum\x12\x1b\n" +
	"\tstole_num\x18\t \x01(\x03R\bstoleNum\x12\x19\n" +
	"\bfruit_id\x18\n" +
	" \x01(\x03R\afruitId\x12\x1b\n" +
	"\tfruit_num\x18\v \x01(\x03R\bfruitNum\x12\x1f\n" +
	"\vweed_owners\x18\f \x03(\x03R\n" +
	"weedOwners\x12#\n" +
	"\rinsect_owners\x18\r \x03(\x03R\finsectOwners\x12\x1a\n" +
	"\bstealers\x18\x0e \x03(\x03R\bstealers\x12\x19\n" +
	"\bgrow_sec\x18\x0f \x01(\x03R\agrowSec\x12\x1c\n" +
	"\tstealable\x18\x10 \x01(\bR\tstealable\x121\n" +
	"\x15left_inorc_fert_times\x18\x11 \x01(\x03R\x12leftInorcFertTimes\x12$\n" +
	"\x0eleft_fruit_num\x18\x12 \x01(\x03R\fleftFruitNum\x120\n" +
	"\x14steal_intimacy_level\x18\x13 \x01(\x03R\x12stealIntimacyLevel\x12*\n" +
	"\x11mutant_config_ids\x18\x14 \x03(\x03R\x0fmutantConfigIds\x12\x1b\n" +
	"\tis_nudged\x18\x15 \x01(\bR\bisNudged\"\xfd\x02\n" +
	"\x0ePlantPhaseInfo\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\x05R\x05phase\x12\x1d\n" +
	"\n" +
	"begin_time\x18\x02 \x01(\x03R\tbeginTime\x12\x19\n" +
	"\bphase_id\x18\x03 \x01(\x03R\aphaseId\x12\x19\n" +
	"\bdry_time\x18\x06 \x01(\x03R\adryTime\x12\x1d\n" +
	"\n" +
	"weeds_time\x18\a \x01(\x03R\tweedsTime\x12\x1f\n" +
	"\vinsect_time\x18\b \x01(\x03R\n" +
	"insectTime\x12L\n" +
	"\n" +
	"ferts_used\x18\t \x03(\v2-.gamepb.plantpb.PlantPhaseInfo.FertsUsedEntryR\tfertsUsed\x124\n" +
	"\amutants\x18\n" +
	" \x03(\v2\x1a.gamepb.plantpb.MutantInfoR\amutants\x1a<\n" +
	"\x0eFertsUsedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"v\n" +
	"\n" +
	"MutantInfo\x12\x1f\n" +
	"\vmutant_time\x18\x01 \x01(\x03R\n" +
	"mutantTime\x12(\n" +
	"\x10mutant_config_id\x18\x02 \x01(\x03R\x0emutantConfigId\x12\x1d\n" +
	"\n" +
	"weather_id\x18\x03 \x01(\x03R\tweatherId\"\xf5\x01\n" +
	"\x0eOperationLimit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tday_times\x18\x02 \x01(\x03R\bdayTimes\x12 \n" +
	"\fday_times_lt\x18\x03 \x01(\x03R\n" +
	"dayTimesLt\x12 \n" +
	"\fday_share_id\x18\x04 \x01(\x03R\n" +
	"dayShareId\x12\"\n" +
	"\rday_exp_times\x18\x05 \x01(\x03R\vdayExpTimes\x12%\n" +
	"\x0fday_ex_times_lt\x18\x06 \x01(\x03R\fdayExTimesLt\x12'\n" +
	"\x10day_exp_share_id\x18\a \x01(\x03R\rdayExpShareId\",\n" +
	"\x0fAllLandsRequest\x12\x19\n" +
	"\bhost_gid\x18\x01 \x01(\x03R\ahostGid\"\x8a\x01\n" +
	"\rAllLandsReply\x12.\n" +
	"\x05lands\x18\x01 \x03(\v2\x18.gamepb.plantpb.LandInfoR\x05lands\x12I\n" +
	"\x10operation_limits\x18\x02 \x03(\v2\x1e.gamepb.plantpb.OperationLimitR\x0foperationLimits\"]\n" +
	"\x0eHarvestRequest\x12\x19\n" +
	"\bland_ids\x18\x01 \x03(\x03R\alandIds\x12\x19\n" +
	"\bhost_gid\x18\x02 \x01(\x03R\ahostGid\x12\x15\n" +
	"\x06is_all\x18\x03 \x01(\bR\x05isAll\"\x87\x01\n" +
	"\fHarvestReply\x12,\n" +
	"\x04land\x18\x01 \x03(\v2\x18.gamepb.plantpb.LandInfoR\x04land\x12I\n" +
	"\x10operation_limits\x18\x04 \x03(\v2\x1e.gamepb.plantpb.OperationLimitR\x0foperationLimits\"H\n" +
	"\x10WaterLandRequest\x12\x19\n" +
	"\bland_ids\x18\x01 \x03(\x03R\alandIds\x12\x19\n" +
	"\bhost_gid\x18\x02 \x01(\x03R\ahostGid\"\x89\x01\n" +
	"\x0eWaterLandReply\x12,\n" +
	"\x04land\x18\x01 \x03(\v2\x18.gamepb.plantpb.LandInfoR\x04land\x12I\n" +
	"\x10operation_limits\x18\x02 \x03(\v2\x1e.gamepb.plantpb.OperationLimitR\x0foperationLimits\"F\n" +
	"\x0eWeedOutRequest\x12\x19\n" +
	"\bland_ids\x18\x01 \x03(\x03R\alandIds\x12\x19\n" +
	"\bhost_gid\x18\x02 \x01(\x03R\ahostGid\"\x87\x01\n" +
	"\fWeedOutReply\x12,\n" +
	"\x04land\x18\x01 \x03(\v2\x18.gamepb.plantpb.LandInfoR\x04land\x12I\n" +
	"\x10operation_limits\x18\x02 \x03(\v2\x1e.gamepb.plantpb.OperationLimitR\x0foperationLimits\"J\n" +
	"\x12InsecticideRequest\x12\x19\n" +
	"\bland_ids\x18\x01 \x03(\x03R\alandIds\x12\x19\n" +
	"\bhost_gid\x18\x02 \x01(\x03R\ahostGid\"\x8b\x01\n" +
	"\x10InsecticideReply\x12,\n" +
	"\x04land\x18\x01 \x03(\v2\x18.gamepb.plantpb.LandInfoR\x04land\x12I\n" +
	"\x10operation_limits\x18\x02 \x03(\v2\x1e.gamepb.plantpb.OperationLimitR\x0foperationLimits\"^\n" +
	"\tPlantItem\x12\x17\n" +
	"\aseed_id\x18\x01 \x01(\x03R\x06seedId\x12\x19\n" +
	"\bland_ids\x18\x02 \x03(\x03R\alandIds\x12\x1d\n" +
	"\n" +
	"auto_slave\x18\x03 \x01(\bR\tautoSlave\"\xd2\x01\n" +
	"\fPlantRequest\x12Q\n" +
	"\rland_and_seed\x18\x01 \x03(\v2-.gamepb.plantpb.PlantRequest.LandAndSeedEntryR\vlandAndSeed\x12/\n" +
	"\x05items\x18\x02 \x03(\v2\x19.gamepb.plantpb.PlantItemR\x05items\x1a>\n" +
	"\x10LandAndSeedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x85\x01\n" +
	"\n" +
	"PlantReply\x12,\n" +
	"\x04land\x18\x01 \x03(\v2\x18.gamepb.plantpb.LandInfoR\x04land\x12I\n" +
	"\x10operation_limits\x18\x02 \x03(\v2\x1e.gamepb.plantpb.OperationLimitR\x0foperationLimits\"/\n" +
	"\x12RemovePlantRequest\x12\x19\n" +
	"\bland_ids\x18\x01 \x03(\x03R\alandIds\"\x8b\x01\n" +
	"\x10RemovePlantReply\x12,\n" +
	"\x04land\x18\x01 \x03(\v2\x18.gamepb.plantpb.LandInfoR\x04land\x12I\n" +
	"\x10operation_limits\x18\x02 \x03(\v2\x1e.gamepb.plantpb.OperationLimitR\x0foperationLimits\"R\n" +
	"\x10FertilizeRequest\x12\x19\n" +
	"\bland_ids\x18\x01 \x03(\x03R\alandIds\x12#\n" +
	"\rfertilizer_id\x18\x02 \x01(\x03R\ffertilizerId\"\xa9\x01\n" +
	"\x0eFertilizeReply\x12,\n" +
	"\x04land\x18\x01 \x03(\v2\x18.gamepb.plantpb.LandInfoR\x04land\x12I\n" +
	"\x10operation_limits\x18\x02 \x03(\v2\x1e.gamepb.plantpb.OperationLimitR\x0foperationLimits\x12\x1e\n" +
	"\n" +
	"fertilizer\x18\x03 \x01(\x03R\n" +
	"fertilizer\"I\n" +
	"\x11PutInsectsRequest\x12\x19\n" +
	"\bland_ids\x18\x01 \x03(\x03R\alandIds\x12\x19\n" +
	"\bhost_gid\x18\x02 \x01(\x03R\ahostGid\"\x8a\x01\n" +
	"\x0fPutInsectsReply\x12,\n" +
	"\x04land\x18\x01 \x03(\v2\x18.gamepb.plantpb.LandInfoR\x04land\x12I\n" +
	"\x10operation_limits\x18\x02 \x03(\v2\x1e.gamepb.plantpb.OperationLimitR\x0foperationLimits\"G\n" +
	"\x0fPutWeedsRequest\x12\x19\n" +
	"\bland_ids\x18\x01 \x03(\x03R\alandIds\x12\x19\n" +
	"\bhost_gid\x18\x02 \x01(\x03R\ahostGid\"\x88\x01\n" +
	"\rPutWeedsReply\x12,\n" +
	"\x04land\x18\x01 \x03(\v2\x18.gamepb.plantpb.LandInfoR\x04land\x12I\n" +
	"\x10operation_limits\x18\x02 \x03(\v2\x1e.gamepb.plantpb.OperationLimitR\x0foperationLimits\"X\n" +
	"\vLandsNotify\x12.\n" +
	"\x05lands\x18\x01 \x03(\v2\x18.gamepb.plantpb.LandInfoR\x05lands\x12\x19\n" +
	"\bhost_gid\x18\x02 \x01(\x03R\ahostGid\",\n" +
	"\x11UnlockLandRequest\x12\x17\n" +
	"\aland_id\x18\x01 \x01(\x03R\x06landId\"?\n" +
	"\x0fUnlockLandReply\x12,\n" +
	"\x04land\x18\x01 \x03(\v2\x18.gamepb.plantpb.LandInfoR\x04land\"-\n" +
	"\x12UpgradeLandRequest\x12\x17\n" +
	"\aland_id\x18\x01 \x01(\x03R\x06landId\"@\n" +
	"\x10UpgradeLandReply\x12,\n" +
	"\x04land\x18\x01 \x03(\v2\x18.gamepb.plantpb.LandInfoR\x04land*\x82\x01\n" +
	"\n" +
	"PlantPhase\x12\x11\n" +
	"\rPHASE_UNKNOWN\x10\x00\x12\b\n" +
	"\x04SEED\x10\x01\x12\x0f\n" +
	"\vGERMINATION\x10\x02\x12\x10\n" +
	"\fSMALL_LEAVES\x10\x03\x12\x10\n" +
	"\fLARGE_LEAVES\x10\x04\x12\f\n" +
	"\bBLOOMING\x10\x05\x12\n" +
	"\n" +
	"\x06MATURE\x10\x06\x12\b\n" +
	"\x04DEAD\x10\aB\x1bZ\x19qq-farm-bot/proto/plantpbb\x06proto3"

var (
	file_plantpb_plant_proto_rawDescOnce sync.Once
	file_plantpb_plant_proto_rawDescData []byte
)

func file_plantpb_plant_proto_rawDescGZIP() []byte {
	file_plantpb_plant_proto_rawDescOnce.Do(func() {
		file_plantpb_plant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plantpb_plant_proto_rawDesc), len(file_plantpb_plant_proto_rawDesc)))
	})
	return file_plantpb_plant_proto_rawDescData
}

var file_plantpb_plant_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plantpb_plant_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_plantpb_plant_proto_goTypes = []any{
	(PlantPhase)(0),              // 0: gamepb.plantpb.PlantPhase
	(*LandInfo)(nil),             // 1: gamepb.plantpb.LandInfo
	(*LandUnlockCondition)(nil),  // 2: gamepb.plantpb.LandUnlockCondition
	(*LandUpgradeCondition)(nil), // 3: gamepb.plantpb.LandUpgradeCondition
	(*PlantInfo)(nil),            // 4: gamepb.plantpb.PlantInfo
	(*PlantPhaseInfo)(nil),       // 5: gamepb.plantpb.PlantPhaseInfo
	(*MutantInfo)(nil),           // 6: gamepb.plantpb.MutantInfo
	(*OperationLimit)(nil),       // 7: gamepb.plantpb.OperationLimit
	(*AllLandsRequest)(nil),      // 8: gamepb.plantpb.AllLandsRequest
	(*AllLandsReply)(nil),        // 9: gamepb.plantpb.AllLandsReply
	(*HarvestRequest)(nil),       // 10: gamepb.plantpb.HarvestRequest
	(*HarvestReply)(nil),         // 11: gamepb.plantpb.HarvestReply
	(*WaterLandRequest)(nil),     // 12: gamepb.plantpb.WaterLandRequest
	(*WaterLandReply)(nil),       // 13: gamepb.plantpb.WaterLandReply
	(*WeedOutRequest)(nil),       // 14: gamepb.plantpb.WeedOutRequest
	(*WeedOutReply)(nil),         // 15: gamepb.plantpb.WeedOutReply
	(*InsecticideRequest)(nil),   // 16: gamepb.plantpb.InsecticideRequest
	(*InsecticideReply)(nil),     // 17: gamepb.plantpb.InsecticideReply
	(*PlantItem)(nil),            // 18: gamepb.plantpb.PlantItem
	(*PlantRequest)(nil),         // 19: gamepb.plantpb.PlantRequest
	(*PlantReply)(nil),           // 20: gamepb.plantpb.PlantReply
	(*RemovePlantRequest)(nil),   // 21: gamepb.plantpb.RemovePlantRequest
	(*RemovePlantReply)(nil),     // 22: gamepb.plantpb.RemovePlantReply
	(*FertilizeRequest)(nil),     // 23: gamepb.plantpb.FertilizeRequest
	(*FertilizeReply)(nil),       // 24: gamepb.plantpb.FertilizeReply
	(*PutInsectsRequest)(nil),    // 25: gamepb.plantpb.PutInsectsRequest
	(*PutInsectsReply)(nil),      // 26: gamepb.plantpb.PutInsectsReply
	(*PutWeedsRequest)(nil),      // 27: gamepb.plantpb.PutWeedsRequest
	(*PutWeedsReply)(nil),        // 28: gamepb.plantpb.PutWeedsReply
	(*LandsNotify)(nil),          // 29: gamepb.plantpb.LandsNotify
	(*UnlockLandRequest)(nil),    // 30: gamepb.plantpb.UnlockLandRequest
	(*UnlockLandReply)(nil),      // 31: gamepb.plantpb.UnlockLandReply
	(*UpgradeLandRequest)(nil),   // 32: gamepb.plantpb.UpgradeLandRequest
	(*UpgradeLandReply)(nil),     // 33: gamepb.plantpb.UpgradeLandReply
	(*LandInfo_Buff)(nil),        // 34: gamepb.plantpb.LandInfo.Buff
	nil,                          // 35: gamepb.plantpb.PlantPhaseInfo.FertsUsedEntry
	nil,                          // 36: gamepb.plantpb.PlantRequest.LandAndSeedEntry
}
var file_plantpb_plant_proto_depIdxs = []int32{
	2,  // 0: gamepb.plantpb.LandInfo.unlock_condition:type_name -> gamepb.plantpb.LandUnlockCondition
	3,  // 1: gamepb.plantpb.LandInfo.upgrade_condition:type_name -> gamepb.plantpb.LandUpgradeCondition
	34, // 2: gamepb.plantpb.LandInfo.buff:type_name -> gamepb.plantpb.LandInfo.Buff
	4,  // 3: gamepb.plantpb.LandInfo.plant:type_name -> gamepb.plantpb.PlantInfo
	5,  // 4: gamepb.plantpb.PlantInfo.phases:type_name -> gamepb.plantpb.PlantPhaseInfo
	35, // 5: gamepb.plantpb.PlantPhaseInfo.ferts_used:type_name -> gamepb.plantpb.PlantPhaseInfo.FertsUsedEntry
	6,  // 6: gamepb.plantpb.PlantPhaseInfo.mutants:type_name -> gamepb.plantpb.MutantInfo
	1,  // 7: gamepb.plantpb.AllLandsReply.lands:type_name -> gamepb.plantpb.LandInfo
	7,  // 8: gamepb.plantpb.AllLandsReply.operation_limits:type_name -> gamepb.plantpb.OperationLimit
	1,  // 9: gamepb.plantpb.HarvestReply.land:type_name -> gamepb.plantpb.LandInfo
	7,  // 10: gamepb.plantpb.HarvestReply.operation_limits:type_name -> gamepb.plantpb.OperationLimit
	1,  // 11: gamepb.plantpb.WaterLandReply.land:type_name -> gamepb.plantpb.LandInfo
	7,  // 12: gamepb.plantpb.WaterLandReply.operation_limits:type_name -> gamepb.plantpb.OperationLimit
	1,  // 13: gamepb.plantpb.WeedOutReply.land:type_name -> gamepb.plantpb.LandInfo
	7,  // 14: gamepb.plantpb.WeedOutReply.operation_limits:type_name -> gamepb.plantpb.OperationLimit
	1,  // 15: gamepb.plantpb.InsecticideReply.land:type_name -> gamepb.plantpb.LandInfo
	7,  // 16: gamepb.plantpb.InsecticideReply.operation_limits:type_name -> gamepb.plantpb.OperationLimit
	36, // 17: gamepb.plantpb.PlantRequest.land_and_seed:type_name -> gamepb.plantpb.PlantRequest.LandAndSeedEntry
	18, // 18: gamepb.plantpb.PlantRequest.items:type_name -> gamepb.plantpb.PlantItem
	1,  // 19: gamepb.plantpb.PlantReply.land:type_name -> gamepb.plantpb.LandInfo
	7,  // 20: gamepb.plantpb.PlantReply.operation_limits:type_name -> gamepb.plantpb.OperationLimit
	1,  // 21: gamepb.plantpb.RemovePlantReply.land:type_name -> gamepb.plantpb.LandInfo
	7,  // 22: gamepb.plantpb.RemovePlantReply.operation_limits:type_name -> gamepb.plantpb.OperationLimit
	1,  // 23: gamepb.plantpb.FertilizeReply.land:type_name -> gamepb.plantpb.LandInfo
	7,  // 24: gamepb.plantpb.FertilizeReply.operation_limits:type_name -> gamepb.plantpb.OperationLimit
	1,  // 25: gamepb.plantpb.PutInsectsReply.land:type_name -> gamepb.plantpb.LandInfo
	7,  // 26: gamepb.plantpb.PutInsectsReply.operation_limits:type_name -> gamepb.plantpb.OperationLimit
	1,  // 27: gamepb.plantpb.PutWeedsReply.land:type_name -> gamepb.plantpb.LandInfo
	7,  // 28: gamepb.plantpb.PutWeedsReply.operation_limits:type_name -> gamepb.plantpb.OperationLimit
	1,  // 29: gamepb.plantpb.LandsNotify.lands:type_name -> gamepb.plantpb.LandInfo
	1,  // 30: gamepb.plantpb.UnlockLandReply.land:type_name -> gamepb.plantpb.LandInfo
	1,  // 31: gamepb.plantpb.UpgradeLandReply.land:type_name -> gamepb.plantpb.LandInfo
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_plantpb_plant_proto_init() }
func file_plantpb_plant_proto_init() {
	if File_plantpb_plant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plantpb_plant_proto_rawDesc), len(file_plantpb_plant_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plantpb_plant_proto_goTypes,
		DependencyIndexes: file_plantpb_plant_proto_depIdxs,
		EnumInfos:         file_plantpb_plant_proto_enumTypes,
		MessageInfos:      file_plantpb_plant_proto_msgTypes,
	}.Build()
	File_plantpb_plant_proto = out.File
	file_plantpb_plant_proto_goTypes = nil
	file_plantpb_plant_proto_depIdxs = nil
}
