// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: shoppb/shop.proto

package shoppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	corepb "qq-farm-bot/proto/corepb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShopType int32

const (
	ShopType_SHOP_TYPE_UNKNOWN ShopType = 0
	ShopType_ITEM              ShopType = 1
	ShopType_SEED              ShopType = 2
	ShopType_PET               ShopType = 3
)

// Enum value maps for ShopType.
var (
	ShopType_name = map[int32]string{
		0: "SHOP_TYPE_UNKNOWN",
		1: "ITEM",
		2: "SEED",
		3: "PET",
	}
	ShopType_value = map[string]int32{
		"SHOP_TYPE_UNKNOWN": 0,
		"ITEM":              1,
		"SEED":              2,
		"PET":               3,
	}
)

func (x ShopType) Enum() *ShopType {
	p := new(ShopType)
	*p = x
	return p
}

func (x ShopType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShopType) Descriptor() protoreflect.EnumDescriptor {
	return file_shoppb_shop_proto_enumTypes[0].Descriptor()
}

func (ShopType) Type() protoreflect.EnumType {
	return &file_shoppb_shop_proto_enumTypes[0]
}

func (x ShopType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShopType.Descriptor instead.
func (ShopType) EnumDescriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{0}
}

type System int32

const (
	System_SYSTEM_UNKNOWN System = 0
	System_GM             System = 1
	System_FixMe          System = 2
	System_RoleBasic      System = 101
	System_Shop           System = 102
	System_Plant          System = 104
	System_Share          System = 105
	System_Task           System = 106
	System_Bag            System = 107
)

// Enum value maps for System.
var (
	System_name = map[int32]string{
		0:   "SYSTEM_UNKNOWN",
		1:   "GM",
		2:   "FixMe",
		101: "RoleBasic",
		102: "Shop",
		104: "Plant",
		105: "Share",
		106: "Task",
		107: "Bag",
	}
	System_value = map[string]int32{
		"SYSTEM_UNKNOWN": 0,
		"GM":             1,
		"FixMe":          2,
		"RoleBasic":      101,
		"Shop":           102,
		"Plant":          104,
		"Share":          105,
		"Task":           106,
		"Bag":            107,
	}
)

func (x System) Enum() *System {
	p := new(System)
	*p = x
	return p
}

func (x System) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (System) Descriptor() protoreflect.EnumDescriptor {
	return file_shoppb_shop_proto_enumTypes[1].Descriptor()
}

func (System) Type() protoreflect.EnumType {
	return &file_shoppb_shop_proto_enumTypes[1]
}

func (x System) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use System.Descriptor instead.
func (System) EnumDescriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{1}
}

type CondType int32

const (
	CondType_COND_TYPE_UNKNOWN CondType = 0
	CondType_MIN_LEVEL         CondType = 1
	CondType_UNLOCK_CARD       CondType = 2
)

// Enum value maps for CondType.
var (
	CondType_name = map[int32]string{
		0: "COND_TYPE_UNKNOWN",
		1: "MIN_LEVEL",
		2: "UNLOCK_CARD",
	}
	CondType_value = map[string]int32{
		"COND_TYPE_UNKNOWN": 0,
		"MIN_LEVEL":         1,
		"UNLOCK_CARD":       2,
	}
)

func (x CondType) Enum() *CondType {
	p := new(CondType)
	*p = x
	return p
}

func (x CondType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CondType) Descriptor() protoreflect.EnumDescriptor {
	return file_shoppb_shop_proto_enumTypes[2].Descriptor()
}

func (CondType) Type() protoreflect.EnumType {
	return &file_shoppb_shop_proto_enumTypes[2]
}

func (x CondType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CondType.Descriptor instead.
func (CondType) EnumDescriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{2}
}

type ShopProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        int64                  `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ShopName      string                 `protobuf:"bytes,2,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	ShopType      int32                  `protobuf:"varint,3,opt,name=shop_type,json=shopType,proto3" json:"shop_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopProfile) Reset() {
	*x = ShopProfile{}
	mi := &file_shoppb_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopProfile) ProtoMessage() {}

func (x *ShopProfile) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopProfile.ProtoReflect.Descriptor instead.
func (*ShopProfile) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{0}
}

func (x *ShopProfile) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ShopProfile) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ShopProfile) GetShopType() int32 {
	if x != nil {
		return x.ShopType
	}
	return 0
}

type GoodsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BoughtNum     int64                  `protobuf:"varint,2,opt,name=bought_num,json=boughtNum,proto3" json:"bought_num,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	LimitCount    int64                  `protobuf:"varint,4,opt,name=limit_count,json=limitCount,proto3" json:"limit_count,omitempty"`
	Unlocked      bool                   `protobuf:"varint,5,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	ItemId        int64                  `protobuf:"varint,6,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemCount     int64                  `protobuf:"varint,7,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	Conds         []*Cond                `protobuf:"bytes,8,rep,name=conds,proto3" json:"conds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfo) Reset() {
	*x = GoodsInfo{}
	mi := &file_shoppb_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfo) ProtoMessage() {}

func (x *GoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfo.ProtoReflect.Descriptor instead.
func (*GoodsInfo) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsInfo) GetBoughtNum() int64 {
	if x != nil {
		return x.BoughtNum
	}
	return 0
}

func (x *GoodsInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodsInfo) GetLimitCount() int64 {
	if x != nil {
		return x.LimitCount
	}
	return 0
}

func (x *GoodsInfo) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

func (x *GoodsInfo) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GoodsInfo) GetItemCount() int64 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *GoodsInfo) GetConds() []*Cond {
	if x != nil {
		return x.Conds
	}
	return nil
}

type Cond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Param         int64                  `protobuf:"varint,2,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cond) Reset() {
	*x = Cond{}
	mi := &file_shoppb_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cond) ProtoMessage() {}

func (x *Cond) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cond.ProtoReflect.Descriptor instead.
func (*Cond) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{2}
}

func (x *Cond) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Cond) GetParam() int64 {
	if x != nil {
		return x.Param
	}
	return 0
}

type TemplateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Subscribed    bool                   `protobuf:"varint,2,opt,name=subscribed,proto3" json:"subscribed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateStatus) Reset() {
	*x = TemplateStatus{}
	mi := &file_shoppb_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateStatus) ProtoMessage() {}

func (x *TemplateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateStatus.ProtoReflect.Descriptor instead.
func (*TemplateStatus) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{3}
}

func (x *TemplateStatus) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *TemplateStatus) GetSubscribed() bool {
	if x != nil {
		return x.Subscribed
	}
	return false
}

type ShopProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopProfilesRequest) Reset() {
	*x = ShopProfilesRequest{}
	mi := &file_shoppb_shop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopProfilesRequest) ProtoMessage() {}

func (x *ShopProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopProfilesRequest.ProtoReflect.Descriptor instead.
func (*ShopProfilesRequest) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{4}
}

type ShopProfilesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopProfiles  []*ShopProfile         `protobuf:"bytes,1,rep,name=shop_profiles,json=shopProfiles,proto3" json:"shop_profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopProfilesReply) Reset() {
	*x = ShopProfilesReply{}
	mi := &file_shoppb_shop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopProfilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopProfilesReply) ProtoMessage() {}

func (x *ShopProfilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopProfilesReply.ProtoReflect.Descriptor instead.
func (*ShopProfilesReply) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{5}
}

func (x *ShopProfilesReply) GetShopProfiles() []*ShopProfile {
	if x != nil {
		return x.ShopProfiles
	}
	return nil
}

type ShopInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        int64                  `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopInfoRequest) Reset() {
	*x = ShopInfoRequest{}
	mi := &file_shoppb_shop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopInfoRequest) ProtoMessage() {}

func (x *ShopInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopInfoRequest.ProtoReflect.Descriptor instead.
func (*ShopInfoRequest) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{6}
}

func (x *ShopInfoRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type ShopInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsList     []*GoodsInfo           `protobuf:"bytes,1,rep,name=goods_list,json=goodsList,proto3" json:"goods_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopInfoReply) Reset() {
	*x = ShopInfoReply{}
	mi := &file_shoppb_shop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopInfoReply) ProtoMessage() {}

func (x *ShopInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopInfoReply.ProtoReflect.Descriptor instead.
func (*ShopInfoReply) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{7}
}

func (x *ShopInfoReply) GetGoodsList() []*GoodsInfo {
	if x != nil {
		return x.GoodsList
	}
	return nil
}

type BuyGoodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyGoodsRequest) Reset() {
	*x = BuyGoodsRequest{}
	mi := &file_shoppb_shop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyGoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyGoodsRequest) ProtoMessage() {}

func (x *BuyGoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyGoodsRequest.ProtoReflect.Descriptor instead.
func (*BuyGoodsRequest) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{8}
}

func (x *BuyGoodsRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *BuyGoodsRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *BuyGoodsRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BuyGoodsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goods         *GoodsInfo             `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"`
	GetItems      []*corepb.Item         `protobuf:"bytes,2,rep,name=get_items,json=getItems,proto3" json:"get_items,omitempty"`
	CostItems     []*corepb.Item         `protobuf:"bytes,3,rep,name=cost_items,json=costItems,proto3" json:"cost_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyGoodsReply) Reset() {
	*x = BuyGoodsReply{}
	mi := &file_shoppb_shop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyGoodsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyGoodsReply) ProtoMessage() {}

func (x *BuyGoodsReply) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyGoodsReply.ProtoReflect.Descriptor instead.
func (*BuyGoodsReply) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{9}
}

func (x *BuyGoodsReply) GetGoods() *GoodsInfo {
	if x != nil {
		return x.Goods
	}
	return nil
}

func (x *BuyGoodsReply) GetGetItems() []*corepb.Item {
	if x != nil {
		return x.GetItems
	}
	return nil
}

func (x *BuyGoodsReply) GetCostItems() []*corepb.Item {
	if x != nil {
		return x.CostItems
	}
	return nil
}

type SetSubscribeMessageStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*TemplateStatus      `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSubscribeMessageStatusRequest) Reset() {
	*x = SetSubscribeMessageStatusRequest{}
	mi := &file_shoppb_shop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSubscribeMessageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSubscribeMessageStatusRequest) ProtoMessage() {}

func (x *SetSubscribeMessageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSubscribeMessageStatusRequest.ProtoReflect.Descriptor instead.
func (*SetSubscribeMessageStatusRequest) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{10}
}

func (x *SetSubscribeMessageStatusRequest) GetStatuses() []*TemplateStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type SetSubscribeMessageStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSubscribeMessageStatusReply) Reset() {
	*x = SetSubscribeMessageStatusReply{}
	mi := &file_shoppb_shop_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSubscribeMessageStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSubscribeMessageStatusReply) ProtoMessage() {}

func (x *SetSubscribeMessageStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSubscribeMessageStatusReply.ProtoReflect.Descriptor instead.
func (*SetSubscribeMessageStatusReply) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{11}
}

type GetSubscribeMessageStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribeMessageStatusRequest) Reset() {
	*x = GetSubscribeMessageStatusRequest{}
	mi := &file_shoppb_shop_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribeMessageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribeMessageStatusRequest) ProtoMessage() {}

func (x *GetSubscribeMessageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribeMessageStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSubscribeMessageStatusRequest) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{12}
}

type GetSubscribeMessageStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*TemplateStatus      `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribeMessageStatusReply) Reset() {
	*x = GetSubscribeMessageStatusReply{}
	mi := &file_shoppb_shop_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribeMessageStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribeMessageStatusReply) ProtoMessage() {}

func (x *GetSubscribeMessageStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribeMessageStatusReply.ProtoReflect.Descriptor instead.
func (*GetSubscribeMessageStatusReply) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{13}
}

func (x *GetSubscribeMessageStatusReply) GetStatuses() []*TemplateStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type GoodsUnlockNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsList     []*GoodsInfo           `protobuf:"bytes,1,rep,name=goods_list,json=goodsList,proto3" json:"goods_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsUnlockNotify) Reset() {
	*x = GoodsUnlockNotify{}
	mi := &file_shoppb_shop_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsUnlockNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsUnlockNotify) ProtoMessage() {}

func (x *GoodsUnlockNotify) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsUnlockNotify.ProtoReflect.Descriptor instead.
func (*GoodsUnlockNotify) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{14}
}

func (x *GoodsUnlockNotify) GetGoodsList() []*GoodsInfo {
	if x != nil {
		return x.GoodsList
	}
	return nil
}

var File_shoppb_shop_proto protoreflect.FileDescriptor

const file_shoppb_shop_proto_rawDesc = "" +
	"\n" +
	"\x11shoppb/shop.proto\x12\rgamepb.shoppb\x1a\x11corepb/core.proto\"`\n" +
	"\vShopProfile\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\x03R\x06shopId\x12\x1b\n" +
	"\tshop_name\x18\x02 \x01(\tR\bshopName\x12\x1b\n" +
	"\tshop_type\x18\x03 \x01(\x05R\bshopType\"\xf0\x01\n" +
	"\tGoodsInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"bought_num\x18\x02 \x01(\x03R\tboughtNum\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1f\n" +
	"\vlimit_count\x18\x04 \x01(\x03R\n" +
	"limitCount\x12\x1a\n" +
	"\bunlocked\x18\x05 \x01(\bR\bunlocked\x12\x17\n" +
	"\aitem_id\x18\x06 \x01(\x03R\x06itemId\x12\x1d\n" +
	"\n" +
	"item_count\x18\a \x01(\x03R\titemCount\x12)\n" +
	"\x05conds\x18\b \x03(\v2\x13.gamepb.shoppb.CondR\x05conds\"0\n" +
	"\x04Cond\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x14\n" +
	"\x05param\x18\x02 \x01(\x03R\x05param\"Q\n" +
	"\x0eTemplateStatus\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x1e\n" +
	"\n" +
	"subscribed\x18\x02 \x01(\bR\n" +
	"subscribed\"\x15\n" +
	"\x13ShopProfilesRequest\"T\n" +
	"\x11ShopProfilesReply\x12?\n" +
	"\rshop_profiles\x18\x01 \x03(\v2\x1a.gamepb.shoppb.ShopProfileR\fshopProfiles\"*\n" +
	"\x0fShopInfoRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\x03R\x06shopId\"H\n" +
	"\rShopInfoReply\x127\n" +
	"\n" +
	"goods_list\x18\x01 \x03(\v2\x18.gamepb.shoppb.GoodsInfoR\tgoodsList\"T\n" +
	"\x0fBuyGoodsRequest\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x03R\agoodsId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\"\x97\x01\n" +
	"\rBuyGoodsReply\x12.\n" +
	"\x05goods\x18\x01 \x01(\v2\x18.gamepb.shoppb.GoodsInfoR\x05goods\x12)\n" +
	"\tget_items\x18\x02 \x03(\v2\f.corepb.ItemR\bgetItems\x12+\n" +
	"\n" +
	"cost_items\x18\x03 \x03(\v2\f.corepb.ItemR\tcostItems\"]\n" +
	" SetSubscribeMessageStatusRequest\x129\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1d.gamepb.shoppb.TemplateStatusR\bstatuses\" \n" +
	"\x1eSetSubscribeMessageStatusReply\"\"\n" +
	" GetSubscribeMessageStatusRequest\"[\n" +
	"\x1eGetSubscribeMessageStatusReply\x129\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1d.gamepb.shoppb.TemplateStatusR\bstatuses\"L\n" +
	"\x11GoodsUnlockNotify\x127\n" +
	"\n" +
	"goods_list\x18\x01 \x03(\v2\x18.gamepb.shoppb.GoodsInfoR\tgoodsList*>\n" +
	"\bShopType\x12\x15\n" +
	"\x11SHOP_TYPE_UNKNOWN\x10\x00\x12\b\n" +
	"\x04ITEM\x10\x01\x12\b\n" +
	"\x04SEED\x10\x02\x12\a\n" +
	"\x03PET\x10\x03*q\n" +
	"\x06System\x12\x12\n" +
	"\x0eSYSTEM_UNKNOWN\x10\x00\x12\x06\n" +
	"\x02GM\x10\x01\x12\t\n" +
	"\x05FixMe\x10\x02\x12\r\n" +
	"\tRoleBasic\x10e\x12\b\n" +
	"\x04Shop\x10f\x12\t\n" +
	"\x05Plant\x10h\x12\t\n" +
	"\x05Share\x10i\x12\b\n" +
	"\x04Task\x10j\x12\a\n" +
	"\x03Bag\x10k*A\n" +
	"\bCondType\x12\x15\n" +
	"\x11COND_TYPE_UNKNOWN\x10\x00\x12\r\n" +
	"\tMIN_LEVEL\x10\x01\x12\x0f\n" +
	"\vUNLOCK_CARD\x10\x02B\x1aZ\x18qq-farm-bot/proto/shoppbb\x06proto3"

var (
	file_shoppb_shop_proto_rawDescOnce sync.Once
	file_shoppb_shop_proto_rawDescData []byte
)

func file_shoppb_shop_proto_rawDescGZIP() []byte {
	file_shoppb_shop_proto_rawDescOnce.Do(func() {
		file_shoppb_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shoppb_shop_proto_rawDesc), len(file_shoppb_shop_proto_rawDesc)))
	})
	return file_shoppb_shop_proto_rawDescData
}

var file_shoppb_shop_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_shoppb_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_shoppb_shop_proto_goTypes = []any{
	(ShopType)(0),                            // 0: gamepb.shoppb.ShopType
	(System)(0),                              // 1: gamepb.shoppb.System
	(CondType)(0),                            // 2: gamepb.shoppb.CondType
	(*ShopProfile)(nil),                      // 3: gamepb.shoppb.ShopProfile
	(*GoodsInfo)(nil),                        // 4: gamepb.shoppb.GoodsInfo
	(*Cond)(nil),                             // 5: gamepb.shoppb.Cond
	(*TemplateStatus)(nil),                   // 6: gamepb.shoppb.TemplateStatus
	(*ShopProfilesRequest)(nil),              // 7: gamepb.shoppb.ShopProfilesRequest
	(*ShopProfilesReply)(nil),                // 8: gamepb.shoppb.ShopProfilesReply
	(*ShopInfoRequest)(nil),                  // 9: gamepb.shoppb.ShopInfoRequest
	(*ShopInfoReply)(nil),                    // 10: gamepb.shoppb.ShopInfoReply
	(*BuyGoodsRequest)(nil),                  // 11: gamepb.shoppb.BuyGoodsRequest
	(*BuyGoodsReply)(nil),                    // 12: gamepb.shoppb.BuyGoodsReply
	(*SetSubscribeMessageStatusRequest)(nil), // 13: gamepb.shoppb.SetSubscribeMessageStatusRequest
	(*SetSubscribeMessageStatusReply)(nil),   // 14: gamepb.shoppb.SetSubscribeMessageStatusReply
	(*GetSubscribeMessageStatusRequest)(nil), // 15: gamepb.shoppb.GetSubscribeMessageStatusRequest
	(*GetSubscribeMessageStatusReply)(nil),   // 16: gamepb.shoppb.GetSubscribeMessageStatusReply
	(*GoodsUnlockNotify)(nil),                // 17: gamepb.shoppb.GoodsUnlockNotify
	(*corepb.Item)(nil),                      // 18: corepb.Item
}
var file_shoppb_shop_proto_depIdxs = []int32{
	5,  // 0: gamepb.shoppb.GoodsInfo.conds:type_name -> gamepb.shoppb.Cond
	3,  // 1: gamepb.shoppb.ShopProfilesReply.shop_profiles:type_name -> gamepb.shoppb.ShopProfile
	4,  // 2: gamepb.shoppb.ShopInfoReply.goods_list:type_name -> gamepb.shoppb.GoodsInfo
	4,  // 3: gamepb.shoppb.BuyGoodsReply.goods:type_name -> gamepb.shoppb.GoodsInfo
	18, // 4: gamepb.shoppb.BuyGoodsReply.get_items:type_name -> corepb.Item
	18, // 5: gamepb.shoppb.BuyGoodsReply.cost_items:type_name -> corepb.Item
	6,  // 6: gamepb.shoppb.SetSubscribeMessageStatusRequest.statuses:type_name -> gamepb.shoppb.TemplateStatus
	6,  // 7: gamepb.shoppb.GetSubscribeMessageStatusReply.statuses:type_name -> gamepb.shoppb.TemplateStatus
	4,  // 8: gamepb.shoppb.GoodsUnlockNotify.goods_list:type_name -> gamepb.shoppb.GoodsInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_shoppb_shop_proto_init() }
func file_shoppb_shop_proto_init() {
	if File_shoppb_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shoppb_shop_proto_rawDesc), len(file_shoppb_shop_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shoppb_shop_proto_goTypes,
		DependencyIndexes: file_shoppb_shop_proto_depIdxs,
		EnumInfos:         file_shoppb_shop_proto_enumTypes,
		MessageInfos:      file_shoppb_shop_proto_msgTypes,
	}.Build()
	File_shoppb_shop_proto = out.File
	file_shoppb_shop_proto_goTypes = nil
	file_shoppb_shop_proto_depIdxs = nil
}
