// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dogpb/dog.proto

package dogpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BriefDogInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DogId         int64                  `protobuf:"varint,1,opt,name=dog_id,json=dogId,proto3" json:"dog_id,omitempty"`
	FoodLastSec   int64                  `protobuf:"varint,2,opt,name=food_last_sec,json=foodLastSec,proto3" json:"food_last_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BriefDogInfo) Reset() {
	*x = BriefDogInfo{}
	mi := &file_dogpb_dog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BriefDogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BriefDogInfo) ProtoMessage() {}

func (x *BriefDogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BriefDogInfo.ProtoReflect.Descriptor instead.
func (*BriefDogInfo) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{0}
}

func (x *BriefDogInfo) GetDogId() int64 {
	if x != nil {
		return x.DogId
	}
	return 0
}

func (x *BriefDogInfo) GetFoodLastSec() int64 {
	if x != nil {
		return x.FoodLastSec
	}
	return 0
}

type DogInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProtectProbability int64                  `protobuf:"varint,3,opt,name=protect_probability,json=protectProbability,proto3" json:"protect_probability,omitempty"`
	LostGoldRangeMin   int64                  `protobuf:"varint,4,opt,name=lost_gold_range_min,json=lostGoldRangeMin,proto3" json:"lost_gold_range_min,omitempty"`
	LostGoldRangeMax   int64                  `protobuf:"varint,5,opt,name=lost_gold_range_max,json=lostGoldRangeMax,proto3" json:"lost_gold_range_max,omitempty"`
	Owned              bool                   `protobuf:"varint,6,opt,name=owned,proto3" json:"owned,omitempty"`
	Activated          bool                   `protobuf:"varint,7,opt,name=activated,proto3" json:"activated,omitempty"`
	Price              int64                  `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DogInfo) Reset() {
	*x = DogInfo{}
	mi := &file_dogpb_dog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogInfo) ProtoMessage() {}

func (x *DogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogInfo.ProtoReflect.Descriptor instead.
func (*DogInfo) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{1}
}

func (x *DogInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DogInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DogInfo) GetProtectProbability() int64 {
	if x != nil {
		return x.ProtectProbability
	}
	return 0
}

func (x *DogInfo) GetLostGoldRangeMin() int64 {
	if x != nil {
		return x.LostGoldRangeMin
	}
	return 0
}

func (x *DogInfo) GetLostGoldRangeMax() int64 {
	if x != nil {
		return x.LostGoldRangeMax
	}
	return 0
}

func (x *DogInfo) GetOwned() bool {
	if x != nil {
		return x.Owned
	}
	return false
}

func (x *DogInfo) GetActivated() bool {
	if x != nil {
		return x.Activated
	}
	return false
}

func (x *DogInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type FoodInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time          int64                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	OwnCount      int64                  `protobuf:"varint,3,opt,name=own_count,json=ownCount,proto3" json:"own_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodInfo) Reset() {
	*x = FoodInfo{}
	mi := &file_dogpb_dog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodInfo) ProtoMessage() {}

func (x *FoodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodInfo.ProtoReflect.Descriptor instead.
func (*FoodInfo) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{2}
}

func (x *FoodInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FoodInfo) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *FoodInfo) GetOwnCount() int64 {
	if x != nil {
		return x.OwnCount
	}
	return 0
}

type ProtectLog struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RoleLevel           int64                  `protobuf:"varint,1,opt,name=role_level,json=roleLevel,proto3" json:"role_level,omitempty"`
	RoleName            string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleAvatarUrl       string                 `protobuf:"bytes,3,opt,name=role_avatar_url,json=roleAvatarUrl,proto3" json:"role_avatar_url,omitempty"`
	RoleOnline          bool                   `protobuf:"varint,4,opt,name=role_online,json=roleOnline,proto3" json:"role_online,omitempty"`
	ProtectTimestamp    int64                  `protobuf:"varint,5,opt,name=protect_timestamp,json=protectTimestamp,proto3" json:"protect_timestamp,omitempty"`
	ProtectCount        int64                  `protobuf:"varint,6,opt,name=protect_count,json=protectCount,proto3" json:"protect_count,omitempty"`
	RewardGold          int64                  `protobuf:"varint,7,opt,name=reward_gold,json=rewardGold,proto3" json:"reward_gold,omitempty"`
	DogId               int64                  `protobuf:"varint,8,opt,name=dog_id,json=dogId,proto3" json:"dog_id,omitempty"`
	DogName             string                 `protobuf:"bytes,9,opt,name=dog_name,json=dogName,proto3" json:"dog_name,omitempty"`
	Gid                 int64                  `protobuf:"varint,10,opt,name=gid,proto3" json:"gid,omitempty"`
	LastOnlineTimestamp int64                  `protobuf:"varint,11,opt,name=last_online_timestamp,json=lastOnlineTimestamp,proto3" json:"last_online_timestamp,omitempty"`
	IsRead              bool                   `protobuf:"varint,12,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	AuthorizedStatus    int32                  `protobuf:"varint,13,opt,name=authorized_status,json=authorizedStatus,proto3" json:"authorized_status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProtectLog) Reset() {
	*x = ProtectLog{}
	mi := &file_dogpb_dog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtectLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectLog) ProtoMessage() {}

func (x *ProtectLog) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectLog.ProtoReflect.Descriptor instead.
func (*ProtectLog) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{3}
}

func (x *ProtectLog) GetRoleLevel() int64 {
	if x != nil {
		return x.RoleLevel
	}
	return 0
}

func (x *ProtectLog) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *ProtectLog) GetRoleAvatarUrl() string {
	if x != nil {
		return x.RoleAvatarUrl
	}
	return ""
}

func (x *ProtectLog) GetRoleOnline() bool {
	if x != nil {
		return x.RoleOnline
	}
	return false
}

func (x *ProtectLog) GetProtectTimestamp() int64 {
	if x != nil {
		return x.ProtectTimestamp
	}
	return 0
}

func (x *ProtectLog) GetProtectCount() int64 {
	if x != nil {
		return x.ProtectCount
	}
	return 0
}

func (x *ProtectLog) GetRewardGold() int64 {
	if x != nil {
		return x.RewardGold
	}
	return 0
}

func (x *ProtectLog) GetDogId() int64 {
	if x != nil {
		return x.DogId
	}
	return 0
}

func (x *ProtectLog) GetDogName() string {
	if x != nil {
		return x.DogName
	}
	return ""
}

func (x *ProtectLog) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ProtectLog) GetLastOnlineTimestamp() int64 {
	if x != nil {
		return x.LastOnlineTimestamp
	}
	return 0
}

func (x *ProtectLog) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *ProtectLog) GetAuthorizedStatus() int32 {
	if x != nil {
		return x.AuthorizedStatus
	}
	return 0
}

type GetDogInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDogInfoRequest) Reset() {
	*x = GetDogInfoRequest{}
	mi := &file_dogpb_dog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDogInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDogInfoRequest) ProtoMessage() {}

func (x *GetDogInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDogInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDogInfoRequest) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{4}
}

type GetDogInfoReply struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Dogs                 []*DogInfo             `protobuf:"bytes,1,rep,name=dogs,proto3" json:"dogs,omitempty"`
	CurrentDeployedDogId int64                  `protobuf:"varint,2,opt,name=current_deployed_dog_id,json=currentDeployedDogId,proto3" json:"current_deployed_dog_id,omitempty"`
	FoodLastSec          int64                  `protobuf:"varint,3,opt,name=food_last_sec,json=foodLastSec,proto3" json:"food_last_sec,omitempty"`
	MaxFoodLastSec       int64                  `protobuf:"varint,4,opt,name=max_food_last_sec,json=maxFoodLastSec,proto3" json:"max_food_last_sec,omitempty"`
	IsExistNewLog        bool                   `protobuf:"varint,6,opt,name=is_exist_new_log,json=isExistNewLog,proto3" json:"is_exist_new_log,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetDogInfoReply) Reset() {
	*x = GetDogInfoReply{}
	mi := &file_dogpb_dog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDogInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDogInfoReply) ProtoMessage() {}

func (x *GetDogInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDogInfoReply.ProtoReflect.Descriptor instead.
func (*GetDogInfoReply) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{5}
}

func (x *GetDogInfoReply) GetDogs() []*DogInfo {
	if x != nil {
		return x.Dogs
	}
	return nil
}

func (x *GetDogInfoReply) GetCurrentDeployedDogId() int64 {
	if x != nil {
		return x.CurrentDeployedDogId
	}
	return 0
}

func (x *GetDogInfoReply) GetFoodLastSec() int64 {
	if x != nil {
		return x.FoodLastSec
	}
	return 0
}

func (x *GetDogInfoReply) GetMaxFoodLastSec() int64 {
	if x != nil {
		return x.MaxFoodLastSec
	}
	return 0
}

func (x *GetDogInfoReply) GetIsExistNewLog() bool {
	if x != nil {
		return x.IsExistNewLog
	}
	return false
}

type BuyAndActivateDogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DogId         int64                  `protobuf:"varint,1,opt,name=dog_id,json=dogId,proto3" json:"dog_id,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyAndActivateDogRequest) Reset() {
	*x = BuyAndActivateDogRequest{}
	mi := &file_dogpb_dog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAndActivateDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAndActivateDogRequest) ProtoMessage() {}

func (x *BuyAndActivateDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAndActivateDogRequest.ProtoReflect.Descriptor instead.
func (*BuyAndActivateDogRequest) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{6}
}

func (x *BuyAndActivateDogRequest) GetDogId() int64 {
	if x != nil {
		return x.DogId
	}
	return 0
}

func (x *BuyAndActivateDogRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BuyAndActivateDogReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyAndActivateDogReply) Reset() {
	*x = BuyAndActivateDogReply{}
	mi := &file_dogpb_dog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyAndActivateDogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyAndActivateDogReply) ProtoMessage() {}

func (x *BuyAndActivateDogReply) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyAndActivateDogReply.ProtoReflect.Descriptor instead.
func (*BuyAndActivateDogReply) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{7}
}

type ActivateDogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DogId         int64                  `protobuf:"varint,1,opt,name=dog_id,json=dogId,proto3" json:"dog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateDogRequest) Reset() {
	*x = ActivateDogRequest{}
	mi := &file_dogpb_dog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateDogRequest) ProtoMessage() {}

func (x *ActivateDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateDogRequest.ProtoReflect.Descriptor instead.
func (*ActivateDogRequest) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{8}
}

func (x *ActivateDogRequest) GetDogId() int64 {
	if x != nil {
		return x.DogId
	}
	return 0
}

type ActivateDogReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateDogReply) Reset() {
	*x = ActivateDogReply{}
	mi := &file_dogpb_dog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateDogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateDogReply) ProtoMessage() {}

func (x *ActivateDogReply) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateDogReply.ProtoReflect.Descriptor instead.
func (*ActivateDogReply) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{9}
}

type DeployDogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DogId         int64                  `protobuf:"varint,1,opt,name=dog_id,json=dogId,proto3" json:"dog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployDogRequest) Reset() {
	*x = DeployDogRequest{}
	mi := &file_dogpb_dog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployDogRequest) ProtoMessage() {}

func (x *DeployDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployDogRequest.ProtoReflect.Descriptor instead.
func (*DeployDogRequest) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{10}
}

func (x *DeployDogRequest) GetDogId() int64 {
	if x != nil {
		return x.DogId
	}
	return 0
}

type DeployDogReply struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DeployedDogId         int64                  `protobuf:"varint,1,opt,name=deployed_dog_id,json=deployedDogId,proto3" json:"deployed_dog_id,omitempty"`
	PreviousDeployedDogId int64                  `protobuf:"varint,2,opt,name=previous_deployed_dog_id,json=previousDeployedDogId,proto3" json:"previous_deployed_dog_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeployDogReply) Reset() {
	*x = DeployDogReply{}
	mi := &file_dogpb_dog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployDogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployDogReply) ProtoMessage() {}

func (x *DeployDogReply) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployDogReply.ProtoReflect.Descriptor instead.
func (*DeployDogReply) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{11}
}

func (x *DeployDogReply) GetDeployedDogId() int64 {
	if x != nil {
		return x.DeployedDogId
	}
	return 0
}

func (x *DeployDogReply) GetPreviousDeployedDogId() int64 {
	if x != nil {
		return x.PreviousDeployedDogId
	}
	return 0
}

type WithdrawDogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawDogRequest) Reset() {
	*x = WithdrawDogRequest{}
	mi := &file_dogpb_dog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawDogRequest) ProtoMessage() {}

func (x *WithdrawDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawDogRequest.ProtoReflect.Descriptor instead.
func (*WithdrawDogRequest) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{12}
}

type WithdrawDogReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WithdrawnDogId int64                  `protobuf:"varint,1,opt,name=withdrawn_dog_id,json=withdrawnDogId,proto3" json:"withdrawn_dog_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WithdrawDogReply) Reset() {
	*x = WithdrawDogReply{}
	mi := &file_dogpb_dog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawDogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawDogReply) ProtoMessage() {}

func (x *WithdrawDogReply) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawDogReply.ProtoReflect.Descriptor instead.
func (*WithdrawDogReply) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{13}
}

func (x *WithdrawDogReply) GetWithdrawnDogId() int64 {
	if x != nil {
		return x.WithdrawnDogId
	}
	return 0
}

type GetProtectLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtectLogsRequest) Reset() {
	*x = GetProtectLogsRequest{}
	mi := &file_dogpb_dog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtectLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtectLogsRequest) ProtoMessage() {}

func (x *GetProtectLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtectLogsRequest.ProtoReflect.Descriptor instead.
func (*GetProtectLogsRequest) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{14}
}

func (x *GetProtectLogsRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *GetProtectLogsRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetProtectLogsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*ProtectLog          `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtectLogsReply) Reset() {
	*x = GetProtectLogsReply{}
	mi := &file_dogpb_dog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtectLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtectLogsReply) ProtoMessage() {}

func (x *GetProtectLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtectLogsReply.ProtoReflect.Descriptor instead.
func (*GetProtectLogsReply) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{15}
}

func (x *GetProtectLogsReply) GetLogs() []*ProtectLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetProtectLogsReply) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type AddFoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodId        int64                  `protobuf:"varint,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFoodRequest) Reset() {
	*x = AddFoodRequest{}
	mi := &file_dogpb_dog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFoodRequest) ProtoMessage() {}

func (x *AddFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFoodRequest.ProtoReflect.Descriptor instead.
func (*AddFoodRequest) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{16}
}

func (x *AddFoodRequest) GetFoodId() int64 {
	if x != nil {
		return x.FoodId
	}
	return 0
}

func (x *AddFoodRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AddFoodReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodLastSec   int64                  `protobuf:"varint,1,opt,name=food_last_sec,json=foodLastSec,proto3" json:"food_last_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFoodReply) Reset() {
	*x = AddFoodReply{}
	mi := &file_dogpb_dog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFoodReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFoodReply) ProtoMessage() {}

func (x *AddFoodReply) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFoodReply.ProtoReflect.Descriptor instead.
func (*AddFoodReply) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{17}
}

func (x *AddFoodReply) GetFoodLastSec() int64 {
	if x != nil {
		return x.FoodLastSec
	}
	return 0
}

type NewProtectLogNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewProtectLogNotify) Reset() {
	*x = NewProtectLogNotify{}
	mi := &file_dogpb_dog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewProtectLogNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewProtectLogNotify) ProtoMessage() {}

func (x *NewProtectLogNotify) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewProtectLogNotify.ProtoReflect.Descriptor instead.
func (*NewProtectLogNotify) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{18}
}

type DogStatusNotify struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DeployedDogId         int64                  `protobuf:"varint,1,opt,name=deployed_dog_id,json=deployedDogId,proto3" json:"deployed_dog_id,omitempty"`
	PreviousDeployedDogId int64                  `protobuf:"varint,2,opt,name=previous_deployed_dog_id,json=previousDeployedDogId,proto3" json:"previous_deployed_dog_id,omitempty"`
	FoodLastSec           int64                  `protobuf:"varint,3,opt,name=food_last_sec,json=foodLastSec,proto3" json:"food_last_sec,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DogStatusNotify) Reset() {
	*x = DogStatusNotify{}
	mi := &file_dogpb_dog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogStatusNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogStatusNotify) ProtoMessage() {}

func (x *DogStatusNotify) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogStatusNotify.ProtoReflect.Descriptor instead.
func (*DogStatusNotify) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{19}
}

func (x *DogStatusNotify) GetDeployedDogId() int64 {
	if x != nil {
		return x.DeployedDogId
	}
	return 0
}

func (x *DogStatusNotify) GetPreviousDeployedDogId() int64 {
	if x != nil {
		return x.PreviousDeployedDogId
	}
	return 0
}

func (x *DogStatusNotify) GetFoodLastSec() int64 {
	if x != nil {
		return x.FoodLastSec
	}
	return 0
}

type DogProtectionNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DogProtectionNotify) Reset() {
	*x = DogProtectionNotify{}
	mi := &file_dogpb_dog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogProtectionNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogProtectionNotify) ProtoMessage() {}

func (x *DogProtectionNotify) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_dog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogProtectionNotify.ProtoReflect.Descriptor instead.
func (*DogProtectionNotify) Descriptor() ([]byte, []int) {
	return file_dogpb_dog_proto_rawDescGZIP(), []int{20}
}

var File_dogpb_dog_proto protoreflect.FileDescriptor

const file_dogpb_dog_proto_rawDesc = "" +
	"\n" +
	"\x0fdogpb/dog.proto\x12\fgamepb.dogpb\"I\n" +
	"\fBriefDogInfo\x12\x15\n" +
	"\x06dog_id\x18\x01 \x01(\x03R\x05dogId\x12\"\n" +
	"\rfood_last_sec\x18\x02 \x01(\x03R\vfoodLastSec\"\x86\x02\n" +
	"\aDogInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x13protect_probability\x18\x03 \x01(\x03R\x12protectProbability\x12-\n" +
	"\x13lost_gold_range_min\x18\x04 \x01(\x03R\x10lostGoldRangeMin\x12-\n" +
	"\x13lost_gold_range_max\x18\x05 \x01(\x03R\x10lostGoldRangeMax\x12\x14\n" +
	"\x05owned\x18\x06 \x01(\bR\x05owned\x12\x1c\n" +
	"\tactivated\x18\a \x01(\bR\tactivated\x12\x14\n" +
	"\x05price\x18\b \x01(\x03R\x05price\"K\n" +
	"\bFoodInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x03R\x04time\x12\x1b\n" +
	"\town_count\x18\x03 \x01(\x03R\bownCount\"\xc2\x03\n" +
	"\n" +
	"ProtectLog\x12\x1d\n" +
	"\n" +
	"role_level\x18\x01 \x01(\x03R\troleLevel\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12&\n" +
	"\x0frole_avatar_url\x18\x03 \x01(\tR\rroleAvatarUrl\x12\x1f\n" +
	"\vrole_online\x18\x04 \x01(\bR\n" +
	"roleOnline\x12+\n" +
	"\x11protect_timestamp\x18\x05 \x01(\x03R\x10protectTimestamp\x12#\n" +
	"\rprotect_count\x18\x06 \x01(\x03R\fprotectCount\x12\x1f\n" +
	"\vreward_gold\x18\a \x01(\x03R\n" +
	"rewardGold\x12\x15\n" +
	"\x06dog_id\x18\b \x01(\x03R\x05dogId\x12\x19\n" +
	"\bdog_name\x18\t \x01(\tR\adogName\x12\x10\n" +
	"\x03gid\x18\n" +
	" \x01(\x03R\x03gid\x122\n" +
	"\x15last_online_timestamp\x18\v \x01(\x03R\x13lastOnlineTimestamp\x12\x17\n" +
	"\ais_read\x18\f \x01(\bR\x06isRead\x12+\n" +
	"\x11authorized_status\x18\r \x01(\x05R\x10authorizedStatus\"\x13\n" +
	"\x11GetDogInfoRequest\"\xeb\x01\n" +
	"\x0fGetDogInfoReply\x12)\n" +
	"\x04dogs\x18\x01 \x03(\v2\x15.gamepb.dogpb.DogInfoR\x04dogs\x125\n" +
	"\x17current_deployed_dog_id\x18\x02 \x01(\x03R\x14currentDeployedDogId\x12\"\n" +
	"\rfood_last_sec\x18\x03 \x01(\x03R\vfoodLastSec\x12)\n" +
	"\x11max_food_last_sec\x18\x04 \x01(\x03R\x0emaxFoodLastSec\x12'\n" +
	"\x10is_exist_new_log\x18\x06 \x01(\bR\risExistNewLog\"G\n" +
	"\x18BuyAndActivateDogRequest\x12\x15\n" +
	"\x06dog_id\x18\x01 \x01(\x03R\x05dogId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\"\x18\n" +
	"\x16BuyAndActivateDogReply\"+\n" +
	"\x12ActivateDogRequest\x12\x15\n" +
	"\x06dog_id\x18\x01 \x01(\x03R\x05dogId\"\x12\n" +
	"\x10ActivateDogReply\")\n" +
	"\x10DeployDogRequest\x12\x15\n" +
	"\x06dog_id\x18\x01 \x01(\x03R\x05dogId\"q\n" +
	"\x0eDeployDogReply\x12&\n" +
	"\x0fdeployed_dog_id\x18\x01 \x01(\x03R\rdeployedDogId\x127\n" +
	"\x18previous_deployed_dog_id\x18\x02 \x01(\x03R\x15previousDeployedDogId\"\x14\n" +
	"\x12WithdrawDogRequest\"<\n" +
	"\x10WithdrawDogReply\x12(\n" +
	"\x10withdrawn_dog_id\x18\x01 \x01(\x03R\x0ewithdrawnDogId\"A\n" +
	"\x15GetProtectLogsRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x03R\x04from\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"d\n" +
	"\x13GetProtectLogsReply\x12,\n" +
	"\x04logs\x18\x01 \x03(\v2\x18.gamepb.dogpb.ProtectLogR\x04logs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"?\n" +
	"\x0eAddFoodRequest\x12\x17\n" +
	"\afood_id\x18\x01 \x01(\x03R\x06foodId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"2\n" +
	"\fAddFoodReply\x12\"\n" +
	"\rfood_last_sec\x18\x01 \x01(\x03R\vfoodLastSec\"\x15\n" +
	"\x13NewProtectLogNotify\"\x96\x01\n" +
	"\x0fDogStatusNotify\x12&\n" +
	"\x0fdeployed_dog_id\x18\x01 \x01(\x03R\rdeployedDogId\x127\n" +
	"\x18previous_deployed_dog_id\x18\x02 \x01(\x03R\x15previousDeployedDogId\x12\"\n" +
	"\rfood_last_sec\x18\x03 \x01(\x03R\vfoodLastSec\"\x15\n" +
	"\x13DogProtectionNotifyB\x19Z\x17qq-farm-bot/proto/dogpbb\x06proto3"

var (
	file_dogpb_dog_proto_rawDescOnce sync.Once
	file_dogpb_dog_proto_rawDescData []byte
)

func file_dogpb_dog_proto_rawDescGZIP() []byte {
	file_dogpb_dog_proto_rawDescOnce.Do(func() {
		file_dogpb_dog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dogpb_dog_proto_rawDesc), len(file_dogpb_dog_proto_rawDesc)))
	})
	return file_dogpb_dog_proto_rawDescData
}

var file_dogpb_dog_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_dogpb_dog_proto_goTypes = []any{
	(*BriefDogInfo)(nil),             // 0: gamepb.dogpb.BriefDogInfo
	(*DogInfo)(nil),                  // 1: gamepb.dogpb.DogInfo
	(*FoodInfo)(nil),                 // 2: gamepb.dogpb.FoodInfo
	(*ProtectLog)(nil),               // 3: gamepb.dogpb.ProtectLog
	(*GetDogInfoRequest)(nil),        // 4: gamepb.dogpb.GetDogInfoRequest
	(*GetDogInfoReply)(nil),          // 5: gamepb.dogpb.GetDogInfoReply
	(*BuyAndActivateDogRequest)(nil), // 6: gamepb.dogpb.BuyAndActivateDogRequest
	(*BuyAndActivateDogReply)(nil),   // 7: gamepb.dogpb.BuyAndActivateDogReply
	(*ActivateDogRequest)(nil),       // 8: gamepb.dogpb.ActivateDogRequest
	(*ActivateDogReply)(nil),         // 9: gamepb.dogpb.ActivateDogReply
	(*DeployDogRequest)(nil),         // 10: gamepb.dogpb.DeployDogRequest
	(*DeployDogReply)(nil),           // 11: gamepb.dogpb.DeployDogReply
	(*WithdrawDogRequest)(nil),       // 12: gamepb.dogpb.WithdrawDogRequest
	(*WithdrawDogReply)(nil),         // 13: gamepb.dogpb.WithdrawDogReply
	(*GetProtectLogsRequest)(nil),    // 14: gamepb.dogpb.GetProtectLogsRequest
	(*GetProtectLogsReply)(nil),      // 15: gamepb.dogpb.GetProtectLogsReply
	(*AddFoodRequest)(nil),           // 16: gamepb.dogpb.AddFoodRequest
	(*AddFoodReply)(nil),             // 17: gamepb.dogpb.AddFoodReply
	(*NewProtectLogNotify)(nil),      // 18: gamepb.dogpb.NewProtectLogNotify
	(*DogStatusNotify)(nil),          // 19: gamepb.dogpb.DogStatusNotify
	(*DogProtectionNotify)(nil),      // 20: gamepb.dogpb.DogProtectionNotify
}
var file_dogpb_dog_proto_depIdxs = []int32{
	1, // 0: gamepb.dogpb.GetDogInfoReply.dogs:type_name -> gamepb.dogpb.DogInfo
	3, // 1: gamepb.dogpb.GetProtectLogsReply.logs:type_name -> gamepb.dogpb.ProtectLog
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dogpb_dog_proto_init() }
func file_dogpb_dog_proto_init() {
	if File_dogpb_dog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dogpb_dog_proto_rawDesc), len(file_dogpb_dog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dogpb_dog_proto_goTypes,
		DependencyIndexes: file_dogpb_dog_proto_depIdxs,
		MessageInfos:      file_dogpb_dog_proto_msgTypes,
	}.Build()
	File_dogpb_dog_proto = out.File
	file_dogpb_dog_proto_goTypes = nil
	file_dogpb_dog_proto_depIdxs = nil
}
