// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: illustratedpb/illustrated.proto

package illustratedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IllustratedInfoV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FruitId       int32                  `protobuf:"varint,1,opt,name=fruit_id,json=fruitId,proto3" json:"fruit_id,omitempty"`
	Rarity        int32                  `protobuf:"varint,2,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Unlocked      bool                   `protobuf:"varint,3,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	Progress      int32                  `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Layer         int32                  `protobuf:"varint,5,opt,name=layer,proto3" json:"layer,omitempty"`
	IsNew         bool                   `protobuf:"varint,7,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IllustratedInfoV2) Reset() {
	*x = IllustratedInfoV2{}
	mi := &file_illustratedpb_illustrated_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IllustratedInfoV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IllustratedInfoV2) ProtoMessage() {}

func (x *IllustratedInfoV2) ProtoReflect() protoreflect.Message {
	mi := &file_illustratedpb_illustrated_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IllustratedInfoV2.ProtoReflect.Descriptor instead.
func (*IllustratedInfoV2) Descriptor() ([]byte, []int) {
	return file_illustratedpb_illustrated_proto_rawDescGZIP(), []int{0}
}

func (x *IllustratedInfoV2) GetFruitId() int32 {
	if x != nil {
		return x.FruitId
	}
	return 0
}

func (x *IllustratedInfoV2) GetRarity() int32 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *IllustratedInfoV2) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

func (x *IllustratedInfoV2) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *IllustratedInfoV2) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *IllustratedInfoV2) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

type GetIllustratedListV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIllustratedListV2Request) Reset() {
	*x = GetIllustratedListV2Request{}
	mi := &file_illustratedpb_illustrated_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIllustratedListV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIllustratedListV2Request) ProtoMessage() {}

func (x *GetIllustratedListV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_illustratedpb_illustrated_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIllustratedListV2Request.ProtoReflect.Descriptor instead.
func (*GetIllustratedListV2Request) Descriptor() ([]byte, []int) {
	return file_illustratedpb_illustrated_proto_rawDescGZIP(), []int{1}
}

type GetIllustratedListV2Reply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Items              []*IllustratedInfoV2   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalProgress      int32                  `protobuf:"varint,2,opt,name=total_progress,json=totalProgress,proto3" json:"total_progress,omitempty"`
	CurrentLevel       int32                  `protobuf:"varint,3,opt,name=current_level,json=currentLevel,proto3" json:"current_level,omitempty"`
	Type               int32                  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	NextLevelProgress  int32                  `protobuf:"varint,7,opt,name=next_level_progress,json=nextLevelProgress,proto3" json:"next_level_progress,omitempty"`
	HasClaimableReward bool                   `protobuf:"varint,8,opt,name=has_claimable_reward,json=hasClaimableReward,proto3" json:"has_claimable_reward,omitempty"`
	HasClaimedReward   bool                   `protobuf:"varint,9,opt,name=has_claimed_reward,json=hasClaimedReward,proto3" json:"has_claimed_reward,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetIllustratedListV2Reply) Reset() {
	*x = GetIllustratedListV2Reply{}
	mi := &file_illustratedpb_illustrated_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIllustratedListV2Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIllustratedListV2Reply) ProtoMessage() {}

func (x *GetIllustratedListV2Reply) ProtoReflect() protoreflect.Message {
	mi := &file_illustratedpb_illustrated_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIllustratedListV2Reply.ProtoReflect.Descriptor instead.
func (*GetIllustratedListV2Reply) Descriptor() ([]byte, []int) {
	return file_illustratedpb_illustrated_proto_rawDescGZIP(), []int{2}
}

func (x *GetIllustratedListV2Reply) GetItems() []*IllustratedInfoV2 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetIllustratedListV2Reply) GetTotalProgress() int32 {
	if x != nil {
		return x.TotalProgress
	}
	return 0
}

func (x *GetIllustratedListV2Reply) GetCurrentLevel() int32 {
	if x != nil {
		return x.CurrentLevel
	}
	return 0
}

func (x *GetIllustratedListV2Reply) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetIllustratedListV2Reply) GetNextLevelProgress() int32 {
	if x != nil {
		return x.NextLevelProgress
	}
	return 0
}

func (x *GetIllustratedListV2Reply) GetHasClaimableReward() bool {
	if x != nil {
		return x.HasClaimableReward
	}
	return false
}

func (x *GetIllustratedListV2Reply) GetHasClaimedReward() bool {
	if x != nil {
		return x.HasClaimedReward
	}
	return false
}

type IllustratedLevelInfoV2 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Level          int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	PointCondition int32                  `protobuf:"varint,2,opt,name=point_condition,json=pointCondition,proto3" json:"point_condition,omitempty"`
	CanClaim       bool                   `protobuf:"varint,4,opt,name=can_claim,json=canClaim,proto3" json:"can_claim,omitempty"`
	Claimed        bool                   `protobuf:"varint,5,opt,name=claimed,proto3" json:"claimed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IllustratedLevelInfoV2) Reset() {
	*x = IllustratedLevelInfoV2{}
	mi := &file_illustratedpb_illustrated_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IllustratedLevelInfoV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IllustratedLevelInfoV2) ProtoMessage() {}

func (x *IllustratedLevelInfoV2) ProtoReflect() protoreflect.Message {
	mi := &file_illustratedpb_illustrated_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IllustratedLevelInfoV2.ProtoReflect.Descriptor instead.
func (*IllustratedLevelInfoV2) Descriptor() ([]byte, []int) {
	return file_illustratedpb_illustrated_proto_rawDescGZIP(), []int{3}
}

func (x *IllustratedLevelInfoV2) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *IllustratedLevelInfoV2) GetPointCondition() int32 {
	if x != nil {
		return x.PointCondition
	}
	return 0
}

func (x *IllustratedLevelInfoV2) GetCanClaim() bool {
	if x != nil {
		return x.CanClaim
	}
	return false
}

func (x *IllustratedLevelInfoV2) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

type GetIllustratedLevelListV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIllustratedLevelListV2Request) Reset() {
	*x = GetIllustratedLevelListV2Request{}
	mi := &file_illustratedpb_illustrated_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIllustratedLevelListV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIllustratedLevelListV2Request) ProtoMessage() {}

func (x *GetIllustratedLevelListV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_illustratedpb_illustrated_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIllustratedLevelListV2Request.ProtoReflect.Descriptor instead.
func (*GetIllustratedLevelListV2Request) Descriptor() ([]byte, []int) {
	return file_illustratedpb_illustrated_proto_rawDescGZIP(), []int{4}
}

func (x *GetIllustratedLevelListV2Request) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GetIllustratedLevelListV2Reply struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	CurrentLevel  int32                     `protobuf:"varint,1,opt,name=current_level,json=currentLevel,proto3" json:"current_level,omitempty"`
	TotalProgress int32                     `protobuf:"varint,2,opt,name=total_progress,json=totalProgress,proto3" json:"total_progress,omitempty"`
	Levels        []*IllustratedLevelInfoV2 `protobuf:"bytes,3,rep,name=levels,proto3" json:"levels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIllustratedLevelListV2Reply) Reset() {
	*x = GetIllustratedLevelListV2Reply{}
	mi := &file_illustratedpb_illustrated_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIllustratedLevelListV2Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIllustratedLevelListV2Reply) ProtoMessage() {}

func (x *GetIllustratedLevelListV2Reply) ProtoReflect() protoreflect.Message {
	mi := &file_illustratedpb_illustrated_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIllustratedLevelListV2Reply.ProtoReflect.Descriptor instead.
func (*GetIllustratedLevelListV2Reply) Descriptor() ([]byte, []int) {
	return file_illustratedpb_illustrated_proto_rawDescGZIP(), []int{5}
}

func (x *GetIllustratedLevelListV2Reply) GetCurrentLevel() int32 {
	if x != nil {
		return x.CurrentLevel
	}
	return 0
}

func (x *GetIllustratedLevelListV2Reply) GetTotalProgress() int32 {
	if x != nil {
		return x.TotalProgress
	}
	return 0
}

func (x *GetIllustratedLevelListV2Reply) GetLevels() []*IllustratedLevelInfoV2 {
	if x != nil {
		return x.Levels
	}
	return nil
}

type ClaimAllRewardsV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimAllRewardsV2Request) Reset() {
	*x = ClaimAllRewardsV2Request{}
	mi := &file_illustratedpb_illustrated_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimAllRewardsV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimAllRewardsV2Request) ProtoMessage() {}

func (x *ClaimAllRewardsV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_illustratedpb_illustrated_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimAllRewardsV2Request.ProtoReflect.Descriptor instead.
func (*ClaimAllRewardsV2Request) Descriptor() ([]byte, []int) {
	return file_illustratedpb_illustrated_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimAllRewardsV2Request) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ClaimAllRewardsV2Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentLevel  int32                  `protobuf:"varint,3,opt,name=current_level,json=currentLevel,proto3" json:"current_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimAllRewardsV2Reply) Reset() {
	*x = ClaimAllRewardsV2Reply{}
	mi := &file_illustratedpb_illustrated_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimAllRewardsV2Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimAllRewardsV2Reply) ProtoMessage() {}

func (x *ClaimAllRewardsV2Reply) ProtoReflect() protoreflect.Message {
	mi := &file_illustratedpb_illustrated_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimAllRewardsV2Reply.ProtoReflect.Descriptor instead.
func (*ClaimAllRewardsV2Reply) Descriptor() ([]byte, []int) {
	return file_illustratedpb_illustrated_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimAllRewardsV2Reply) GetCurrentLevel() int32 {
	if x != nil {
		return x.CurrentLevel
	}
	return 0
}

type UnlockedFruitInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FruitId             int32                  `protobuf:"varint,1,opt,name=fruit_id,json=fruitId,proto3" json:"fruit_id,omitempty"`
	Progress            int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	ProgressToNextLevel int32                  `protobuf:"varint,3,opt,name=progress_to_next_level,json=progressToNextLevel,proto3" json:"progress_to_next_level,omitempty"`
	TotalProgressBefore int32                  `protobuf:"varint,4,opt,name=total_progress_before,json=totalProgressBefore,proto3" json:"total_progress_before,omitempty"`
	TotalProgressAfter  int32                  `protobuf:"varint,5,opt,name=total_progress_after,json=totalProgressAfter,proto3" json:"total_progress_after,omitempty"`
	LevelBefore         int32                  `protobuf:"varint,6,opt,name=level_before,json=levelBefore,proto3" json:"level_before,omitempty"`
	LevelAfter          int32                  `protobuf:"varint,7,opt,name=level_after,json=levelAfter,proto3" json:"level_after,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UnlockedFruitInfo) Reset() {
	*x = UnlockedFruitInfo{}
	mi := &file_illustratedpb_illustrated_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockedFruitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockedFruitInfo) ProtoMessage() {}

func (x *UnlockedFruitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_illustratedpb_illustrated_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockedFruitInfo.ProtoReflect.Descriptor instead.
func (*UnlockedFruitInfo) Descriptor() ([]byte, []int) {
	return file_illustratedpb_illustrated_proto_rawDescGZIP(), []int{8}
}

func (x *UnlockedFruitInfo) GetFruitId() int32 {
	if x != nil {
		return x.FruitId
	}
	return 0
}

func (x *UnlockedFruitInfo) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *UnlockedFruitInfo) GetProgressToNextLevel() int32 {
	if x != nil {
		return x.ProgressToNextLevel
	}
	return 0
}

func (x *UnlockedFruitInfo) GetTotalProgressBefore() int32 {
	if x != nil {
		return x.TotalProgressBefore
	}
	return 0
}

func (x *UnlockedFruitInfo) GetTotalProgressAfter() int32 {
	if x != nil {
		return x.TotalProgressAfter
	}
	return 0
}

func (x *UnlockedFruitInfo) GetLevelBefore() int32 {
	if x != nil {
		return x.LevelBefore
	}
	return 0
}

func (x *UnlockedFruitInfo) GetLevelAfter() int32 {
	if x != nil {
		return x.LevelAfter
	}
	return 0
}

type IllustratedChangeNotifyV2 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Fruits          []*UnlockedFruitInfo   `protobuf:"bytes,1,rep,name=fruits,proto3" json:"fruits,omitempty"`
	OldLevel        int32                  `protobuf:"varint,2,opt,name=old_level,json=oldLevel,proto3" json:"old_level,omitempty"`
	NewLevel        int32                  `protobuf:"varint,3,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
	Type            int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	OldProgress     int32                  `protobuf:"varint,5,opt,name=old_progress,json=oldProgress,proto3" json:"old_progress,omitempty"`
	CurrentProgress int32                  `protobuf:"varint,6,opt,name=current_progress,json=currentProgress,proto3" json:"current_progress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IllustratedChangeNotifyV2) Reset() {
	*x = IllustratedChangeNotifyV2{}
	mi := &file_illustratedpb_illustrated_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IllustratedChangeNotifyV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IllustratedChangeNotifyV2) ProtoMessage() {}

func (x *IllustratedChangeNotifyV2) ProtoReflect() protoreflect.Message {
	mi := &file_illustratedpb_illustrated_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IllustratedChangeNotifyV2.ProtoReflect.Descriptor instead.
func (*IllustratedChangeNotifyV2) Descriptor() ([]byte, []int) {
	return file_illustratedpb_illustrated_proto_rawDescGZIP(), []int{9}
}

func (x *IllustratedChangeNotifyV2) GetFruits() []*UnlockedFruitInfo {
	if x != nil {
		return x.Fruits
	}
	return nil
}

func (x *IllustratedChangeNotifyV2) GetOldLevel() int32 {
	if x != nil {
		return x.OldLevel
	}
	return 0
}

func (x *IllustratedChangeNotifyV2) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

func (x *IllustratedChangeNotifyV2) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *IllustratedChangeNotifyV2) GetOldProgress() int32 {
	if x != nil {
		return x.OldProgress
	}
	return 0
}

func (x *IllustratedChangeNotifyV2) GetCurrentProgress() int32 {
	if x != nil {
		return x.CurrentProgress
	}
	return 0
}

type IllustratedRewardRedDotNotifyV2 struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NormalRewardAvailable  bool                   `protobuf:"varint,1,opt,name=normal_reward_available,json=normalRewardAvailable,proto3" json:"normal_reward_available,omitempty"`
	PremiumRewardAvailable bool                   `protobuf:"varint,2,opt,name=premium_reward_available,json=premiumRewardAvailable,proto3" json:"premium_reward_available,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IllustratedRewardRedDotNotifyV2) Reset() {
	*x = IllustratedRewardRedDotNotifyV2{}
	mi := &file_illustratedpb_illustrated_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IllustratedRewardRedDotNotifyV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IllustratedRewardRedDotNotifyV2) ProtoMessage() {}

func (x *IllustratedRewardRedDotNotifyV2) ProtoReflect() protoreflect.Message {
	mi := &file_illustratedpb_illustrated_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IllustratedRewardRedDotNotifyV2.ProtoReflect.Descriptor instead.
func (*IllustratedRewardRedDotNotifyV2) Descriptor() ([]byte, []int) {
	return file_illustratedpb_illustrated_proto_rawDescGZIP(), []int{10}
}

func (x *IllustratedRewardRedDotNotifyV2) GetNormalRewardAvailable() bool {
	if x != nil {
		return x.NormalRewardAvailable
	}
	return false
}

func (x *IllustratedRewardRedDotNotifyV2) GetPremiumRewardAvailable() bool {
	if x != nil {
		return x.PremiumRewardAvailable
	}
	return false
}

type ClearNewUnlockedFruitsV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearNewUnlockedFruitsV2Request) Reset() {
	*x = ClearNewUnlockedFruitsV2Request{}
	mi := &file_illustratedpb_illustrated_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearNewUnlockedFruitsV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearNewUnlockedFruitsV2Request) ProtoMessage() {}

func (x *ClearNewUnlockedFruitsV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_illustratedpb_illustrated_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearNewUnlockedFruitsV2Request.ProtoReflect.Descriptor instead.
func (*ClearNewUnlockedFruitsV2Request) Descriptor() ([]byte, []int) {
	return file_illustratedpb_illustrated_proto_rawDescGZIP(), []int{11}
}

type ClearNewUnlockedFruitsV2Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearNewUnlockedFruitsV2Reply) Reset() {
	*x = ClearNewUnlockedFruitsV2Reply{}
	mi := &file_illustratedpb_illustrated_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearNewUnlockedFruitsV2Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearNewUnlockedFruitsV2Reply) ProtoMessage() {}

func (x *ClearNewUnlockedFruitsV2Reply) ProtoReflect() protoreflect.Message {
	mi := &file_illustratedpb_illustrated_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearNewUnlockedFruitsV2Reply.ProtoReflect.Descriptor instead.
func (*ClearNewUnlockedFruitsV2Reply) Descriptor() ([]byte, []int) {
	return file_illustratedpb_illustrated_proto_rawDescGZIP(), []int{12}
}

var File_illustratedpb_illustrated_proto protoreflect.FileDescriptor

const file_illustratedpb_illustrated_proto_rawDesc = "" +
	"\n" +
	"\x1fillustratedpb/illustrated.proto\x12\x14gamepb.illustratedpb\"\xab\x01\n" +
	"\x11IllustratedInfoV2\x12\x19\n" +
	"\bfruit_id\x18\x01 \x01(\x05R\afruitId\x12\x16\n" +
	"\x06rarity\x18\x02 \x01(\x05R\x06rarity\x12\x1a\n" +
	"\bunlocked\x18\x03 \x01(\bR\bunlocked\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x05R\bprogress\x12\x14\n" +
	"\x05layer\x18\x05 \x01(\x05R\x05layer\x12\x15\n" +
	"\x06is_new\x18\a \x01(\bR\x05isNew\"\x1d\n" +
	"\x1bGetIllustratedListV2Request\"\xca\x02\n" +
	"\x19GetIllustratedListV2Reply\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.gamepb.illustratedpb.IllustratedInfoV2R\x05items\x12%\n" +
	"\x0etotal_progress\x18\x02 \x01(\x05R\rtotalProgress\x12#\n" +
	"\rcurrent_level\x18\x03 \x01(\x05R\fcurrentLevel\x12\x12\n" +
	"\x04type\x18\x06 \x01(\x05R\x04type\x12.\n" +
	"\x13next_level_progress\x18\a \x01(\x05R\x11nextLevelProgress\x120\n" +
	"\x14has_claimable_reward\x18\b \x01(\bR\x12hasClaimableReward\x12,\n" +
	"\x12has_claimed_reward\x18\t \x01(\bR\x10hasClaimedReward\"\x8e\x01\n" +
	"\x16IllustratedLevelInfoV2\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12'\n" +
	"\x0fpoint_condition\x18\x02 \x01(\x05R\x0epointCondition\x12\x1b\n" +
	"\tcan_claim\x18\x04 \x01(\bR\bcanClaim\x12\x18\n" +
	"\aclaimed\x18\x05 \x01(\bR\aclaimed\"6\n" +
	" GetIllustratedLevelListV2Request\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\"\xb2\x01\n" +
	"\x1eGetIllustratedLevelListV2Reply\x12#\n" +
	"\rcurrent_level\x18\x01 \x01(\x05R\fcurrentLevel\x12%\n" +
	"\x0etotal_progress\x18\x02 \x01(\x05R\rtotalProgress\x12D\n" +
	"\x06levels\x18\x03 \x03(\v2,.gamepb.illustratedpb.IllustratedLevelInfoV2R\x06levels\".\n" +
	"\x18ClaimAllRewardsV2Request\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\"=\n" +
	"\x16ClaimAllRewardsV2Reply\x12#\n" +
	"\rcurrent_level\x18\x03 \x01(\x05R\fcurrentLevel\"\xa9\x02\n" +
	"\x11UnlockedFruitInfo\x12\x19\n" +
	"\bfruit_id\x18\x01 \x01(\x05R\afruitId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x123\n" +
	"\x16progress_to_next_level\x18\x03 \x01(\x05R\x13progressToNextLevel\x122\n" +
	"\x15total_progress_before\x18\x04 \x01(\x05R\x13totalProgressBefore\x120\n" +
	"\x14total_progress_after\x18\x05 \x01(\x05R\x12totalProgressAfter\x12!\n" +
	"\flevel_before\x18\x06 \x01(\x05R\vlevelBefore\x12\x1f\n" +
	"\vlevel_after\x18\a \x01(\x05R\n" +
	"levelAfter\"\xf8\x01\n" +
	"\x19IllustratedChangeNotifyV2\x12?\n" +
	"\x06fruits\x18\x01 \x03(\v2'.gamepb.illustratedpb.UnlockedFruitInfoR\x06fruits\x12\x1b\n" +
	"\told_level\x18\x02 \x01(\x05R\boldLevel\x12\x1b\n" +
	"\tnew_level\x18\x03 \x01(\x05R\bnewLevel\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12!\n" +
	"\fold_progress\x18\x05 \x01(\x05R\voldProgress\x12)\n" +
	"\x10current_progress\x18\x06 \x01(\x05R\x0fcurrentProgress\"\x93\x01\n" +
	"\x1fIllustratedRewardRedDotNotifyV2\x126\n" +
	"\x17normal_reward_available\x18\x01 \x01(\bR\x15normalRewardAvailable\x128\n" +
	"\x18premium_reward_available\x18\x02 \x01(\bR\x16premiumRewardAvailable\"!\n" +
	"\x1fClearNewUnlockedFruitsV2Request\"\x1f\n" +
	"\x1dClearNewUnlockedFruitsV2ReplyB!Z\x1fqq-farm-bot/proto/illustratedpbb\x06proto3"

var (
	file_illustratedpb_illustrated_proto_rawDescOnce sync.Once
	file_illustratedpb_illustrated_proto_rawDescData []byte
)

func file_illustratedpb_illustrated_proto_rawDescGZIP() []byte {
	file_illustratedpb_illustrated_proto_rawDescOnce.Do(func() {
		file_illustratedpb_illustrated_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_illustratedpb_illustrated_proto_rawDesc), len(file_illustratedpb_illustrated_proto_rawDesc)))
	})
	return file_illustratedpb_illustrated_proto_rawDescData
}

var file_illustratedpb_illustrated_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_illustratedpb_illustrated_proto_goTypes = []any{
	(*IllustratedInfoV2)(nil),                // 0: gamepb.illustratedpb.IllustratedInfoV2
	(*GetIllustratedListV2Request)(nil),      // 1: gamepb.illustratedpb.GetIllustratedListV2Request
	(*GetIllustratedListV2Reply)(nil),        // 2: gamepb.illustratedpb.GetIllustratedListV2Reply
	(*IllustratedLevelInfoV2)(nil),           // 3: gamepb.illustratedpb.IllustratedLevelInfoV2
	(*GetIllustratedLevelListV2Request)(nil), // 4: gamepb.illustratedpb.GetIllustratedLevelListV2Request
	(*GetIllustratedLevelListV2Reply)(nil),   // 5: gamepb.illustratedpb.GetIllustratedLevelListV2Reply
	(*ClaimAllRewardsV2Request)(nil),         // 6: gamepb.illustratedpb.ClaimAllRewardsV2Request
	(*ClaimAllRewardsV2Reply)(nil),           // 7: gamepb.illustratedpb.ClaimAllRewardsV2Reply
	(*UnlockedFruitInfo)(nil),                // 8: gamepb.illustratedpb.UnlockedFruitInfo
	(*IllustratedChangeNotifyV2)(nil),        // 9: gamepb.illustratedpb.IllustratedChangeNotifyV2
	(*IllustratedRewardRedDotNotifyV2)(nil),  // 10: gamepb.illustratedpb.IllustratedRewardRedDotNotifyV2
	(*ClearNewUnlockedFruitsV2Request)(nil),  // 11: gamepb.illustratedpb.ClearNewUnlockedFruitsV2Request
	(*ClearNewUnlockedFruitsV2Reply)(nil),    // 12: gamepb.illustratedpb.ClearNewUnlockedFruitsV2Reply
}
var file_illustratedpb_illustrated_proto_depIdxs = []int32{
	0, // 0: gamepb.illustratedpb.GetIllustratedListV2Reply.items:type_name -> gamepb.illustratedpb.IllustratedInfoV2
	3, // 1: gamepb.illustratedpb.GetIllustratedLevelListV2Reply.levels:type_name -> gamepb.illustratedpb.IllustratedLevelInfoV2
	8, // 2: gamepb.illustratedpb.IllustratedChangeNotifyV2.fruits:type_name -> gamepb.illustratedpb.UnlockedFruitInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_illustratedpb_illustrated_proto_init() }
func file_illustratedpb_illustrated_proto_init() {
	if File_illustratedpb_illustrated_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_illustratedpb_illustrated_proto_rawDesc), len(file_illustratedpb_illustrated_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_illustratedpb_illustrated_proto_goTypes,
		DependencyIndexes: file_illustratedpb_illustrated_proto_depIdxs,
		MessageInfos:      file_illustratedpb_illustrated_proto_msgTypes,
	}.Build()
	File_illustratedpb_illustrated_proto = out.File
	file_illustratedpb_illustrated_proto_goTypes = nil
	file_illustratedpb_illustrated_proto_depIdxs = nil
}
