// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: guidepb/guide.proto

package guidepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nodestatus int32

const (
	Nodestatus_NODESTATUS_UNKNOWN Nodestatus = 0
	Nodestatus_COMPLETED          Nodestatus = 1
	Nodestatus_UNCOMPLETED        Nodestatus = 2
	Nodestatus_REWARDED           Nodestatus = 3
)

// Enum value maps for Nodestatus.
var (
	Nodestatus_name = map[int32]string{
		0: "NODESTATUS_UNKNOWN",
		1: "COMPLETED",
		2: "UNCOMPLETED",
		3: "REWARDED",
	}
	Nodestatus_value = map[string]int32{
		"NODESTATUS_UNKNOWN": 0,
		"COMPLETED":          1,
		"UNCOMPLETED":        2,
		"REWARDED":           3,
	}
)

func (x Nodestatus) Enum() *Nodestatus {
	p := new(Nodestatus)
	*p = x
	return p
}

func (x Nodestatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Nodestatus) Descriptor() protoreflect.EnumDescriptor {
	return file_guidepb_guide_proto_enumTypes[0].Descriptor()
}

func (Nodestatus) Type() protoreflect.EnumType {
	return &file_guidepb_guide_proto_enumTypes[0]
}

func (x Nodestatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Nodestatus.Descriptor instead.
func (Nodestatus) EnumDescriptor() ([]byte, []int) {
	return file_guidepb_guide_proto_rawDescGZIP(), []int{0}
}

type GuideInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrNodeId    int64                  `protobuf:"varint,1,opt,name=curr_node_id,json=currNodeId,proto3" json:"curr_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuideInfo) Reset() {
	*x = GuideInfo{}
	mi := &file_guidepb_guide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuideInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuideInfo) ProtoMessage() {}

func (x *GuideInfo) ProtoReflect() protoreflect.Message {
	mi := &file_guidepb_guide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuideInfo.ProtoReflect.Descriptor instead.
func (*GuideInfo) Descriptor() ([]byte, []int) {
	return file_guidepb_guide_proto_rawDescGZIP(), []int{0}
}

func (x *GuideInfo) GetCurrNodeId() int64 {
	if x != nil {
		return x.CurrNodeId
	}
	return 0
}

type WeakGuideNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeakGuideNode) Reset() {
	*x = WeakGuideNode{}
	mi := &file_guidepb_guide_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeakGuideNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeakGuideNode) ProtoMessage() {}

func (x *WeakGuideNode) ProtoReflect() protoreflect.Message {
	mi := &file_guidepb_guide_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeakGuideNode.ProtoReflect.Descriptor instead.
func (*WeakGuideNode) Descriptor() ([]byte, []int) {
	return file_guidepb_guide_proto_rawDescGZIP(), []int{1}
}

func (x *WeakGuideNode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WeakGuideNode) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type SetCurrNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCurrNodeRequest) Reset() {
	*x = SetCurrNodeRequest{}
	mi := &file_guidepb_guide_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCurrNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCurrNodeRequest) ProtoMessage() {}

func (x *SetCurrNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guidepb_guide_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCurrNodeRequest.ProtoReflect.Descriptor instead.
func (*SetCurrNodeRequest) Descriptor() ([]byte, []int) {
	return file_guidepb_guide_proto_rawDescGZIP(), []int{2}
}

func (x *SetCurrNodeRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type SetCurrNodeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCurrNodeReply) Reset() {
	*x = SetCurrNodeReply{}
	mi := &file_guidepb_guide_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCurrNodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCurrNodeReply) ProtoMessage() {}

func (x *SetCurrNodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_guidepb_guide_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCurrNodeReply.ProtoReflect.Descriptor instead.
func (*SetCurrNodeReply) Descriptor() ([]byte, []int) {
	return file_guidepb_guide_proto_rawDescGZIP(), []int{3}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_guidepb_guide_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guidepb_guide_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_guidepb_guide_proto_rawDescGZIP(), []int{4}
}

type GetInfoReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GuideInfo      *GuideInfo             `protobuf:"bytes,1,opt,name=guide_info,json=guideInfo,proto3" json:"guide_info,omitempty"`
	WeakGuideNodes []*WeakGuideNode       `protobuf:"bytes,2,rep,name=weak_guide_nodes,json=weakGuideNodes,proto3" json:"weak_guide_nodes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetInfoReply) Reset() {
	*x = GetInfoReply{}
	mi := &file_guidepb_guide_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoReply) ProtoMessage() {}

func (x *GetInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_guidepb_guide_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoReply.ProtoReflect.Descriptor instead.
func (*GetInfoReply) Descriptor() ([]byte, []int) {
	return file_guidepb_guide_proto_rawDescGZIP(), []int{5}
}

func (x *GetInfoReply) GetGuideInfo() *GuideInfo {
	if x != nil {
		return x.GuideInfo
	}
	return nil
}

func (x *GetInfoReply) GetWeakGuideNodes() []*WeakGuideNode {
	if x != nil {
		return x.WeakGuideNodes
	}
	return nil
}

type SetWeakGuideNodeCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWeakGuideNodeCompleteRequest) Reset() {
	*x = SetWeakGuideNodeCompleteRequest{}
	mi := &file_guidepb_guide_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWeakGuideNodeCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWeakGuideNodeCompleteRequest) ProtoMessage() {}

func (x *SetWeakGuideNodeCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guidepb_guide_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWeakGuideNodeCompleteRequest.ProtoReflect.Descriptor instead.
func (*SetWeakGuideNodeCompleteRequest) Descriptor() ([]byte, []int) {
	return file_guidepb_guide_proto_rawDescGZIP(), []int{6}
}

func (x *SetWeakGuideNodeCompleteRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type SetWeakGuideNodeCompleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWeakGuideNodeCompleteReply) Reset() {
	*x = SetWeakGuideNodeCompleteReply{}
	mi := &file_guidepb_guide_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWeakGuideNodeCompleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWeakGuideNodeCompleteReply) ProtoMessage() {}

func (x *SetWeakGuideNodeCompleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_guidepb_guide_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWeakGuideNodeCompleteReply.ProtoReflect.Descriptor instead.
func (*SetWeakGuideNodeCompleteReply) Descriptor() ([]byte, []int) {
	return file_guidepb_guide_proto_rawDescGZIP(), []int{7}
}

type ClaimWeakGuideRewardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimWeakGuideRewardRequest) Reset() {
	*x = ClaimWeakGuideRewardRequest{}
	mi := &file_guidepb_guide_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimWeakGuideRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimWeakGuideRewardRequest) ProtoMessage() {}

func (x *ClaimWeakGuideRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guidepb_guide_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimWeakGuideRewardRequest.ProtoReflect.Descriptor instead.
func (*ClaimWeakGuideRewardRequest) Descriptor() ([]byte, []int) {
	return file_guidepb_guide_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimWeakGuideRewardRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type ClaimWeakGuideRewardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimWeakGuideRewardReply) Reset() {
	*x = ClaimWeakGuideRewardReply{}
	mi := &file_guidepb_guide_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimWeakGuideRewardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimWeakGuideRewardReply) ProtoMessage() {}

func (x *ClaimWeakGuideRewardReply) ProtoReflect() protoreflect.Message {
	mi := &file_guidepb_guide_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimWeakGuideRewardReply.ProtoReflect.Descriptor instead.
func (*ClaimWeakGuideRewardReply) Descriptor() ([]byte, []int) {
	return file_guidepb_guide_proto_rawDescGZIP(), []int{9}
}

var File_guidepb_guide_proto protoreflect.FileDescriptor

const file_guidepb_guide_proto_rawDesc = "" +
	"\n" +
	"\x13guidepb/guide.proto\x12\x0egamepb.guidepb\"-\n" +
	"\tGuideInfo\x12 \n" +
	"\fcurr_node_id\x18\x01 \x01(\x03R\n" +
	"currNodeId\"7\n" +
	"\rWeakGuideNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"-\n" +
	"\x12SetCurrNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"\x12\n" +
	"\x10SetCurrNodeReply\"\x10\n" +
	"\x0eGetInfoRequest\"\x91\x01\n" +
	"\fGetInfoReply\x128\n" +
	"\n" +
	"guide_info\x18\x01 \x01(\v2\x19.gamepb.guidepb.GuideInfoR\tguideInfo\x12G\n" +
	"\x10weak_guide_nodes\x18\x02 \x03(\v2\x1d.gamepb.guidepb.WeakGuideNodeR\x0eweakGuideNodes\":\n" +
	"\x1fSetWeakGuideNodeCompleteRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"\x1f\n" +
	"\x1dSetWeakGuideNodeCompleteReply\"6\n" +
	"\x1bClaimWeakGuideRewardRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"\x1b\n" +
	"\x19ClaimWeakGuideRewardReply*R\n" +
	"\n" +
	"Nodestatus\x12\x16\n" +
	"\x12NODESTATUS_UNKNOWN\x10\x00\x12\r\n" +
	"\tCOMPLETED\x10\x01\x12\x0f\n" +
	"\vUNCOMPLETED\x10\x02\x12\f\n" +
	"\bREWARDED\x10\x03B\x1bZ\x19qq-farm-bot/proto/guidepbb\x06proto3"

var (
	file_guidepb_guide_proto_rawDescOnce sync.Once
	file_guidepb_guide_proto_rawDescData []byte
)

func file_guidepb_guide_proto_rawDescGZIP() []byte {
	file_guidepb_guide_proto_rawDescOnce.Do(func() {
		file_guidepb_guide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guidepb_guide_proto_rawDesc), len(file_guidepb_guide_proto_rawDesc)))
	})
	return file_guidepb_guide_proto_rawDescData
}

var file_guidepb_guide_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_guidepb_guide_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_guidepb_guide_proto_goTypes = []any{
	(Nodestatus)(0),                         // 0: gamepb.guidepb.Nodestatus
	(*GuideInfo)(nil),                       // 1: gamepb.guidepb.GuideInfo
	(*WeakGuideNode)(nil),                   // 2: gamepb.guidepb.WeakGuideNode
	(*SetCurrNodeRequest)(nil),              // 3: gamepb.guidepb.SetCurrNodeRequest
	(*SetCurrNodeReply)(nil),                // 4: gamepb.guidepb.SetCurrNodeReply
	(*GetInfoRequest)(nil),                  // 5: gamepb.guidepb.GetInfoRequest
	(*GetInfoReply)(nil),                    // 6: gamepb.guidepb.GetInfoReply
	(*SetWeakGuideNodeCompleteRequest)(nil), // 7: gamepb.guidepb.SetWeakGuideNodeCompleteRequest
	(*SetWeakGuideNodeCompleteReply)(nil),   // 8: gamepb.guidepb.SetWeakGuideNodeCompleteReply
	(*ClaimWeakGuideRewardRequest)(nil),     // 9: gamepb.guidepb.ClaimWeakGuideRewardRequest
	(*ClaimWeakGuideRewardReply)(nil),       // 10: gamepb.guidepb.ClaimWeakGuideRewardReply
}
var file_guidepb_guide_proto_depIdxs = []int32{
	1, // 0: gamepb.guidepb.GetInfoReply.guide_info:type_name -> gamepb.guidepb.GuideInfo
	2, // 1: gamepb.guidepb.GetInfoReply.weak_guide_nodes:type_name -> gamepb.guidepb.WeakGuideNode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_guidepb_guide_proto_init() }
func file_guidepb_guide_proto_init() {
	if File_guidepb_guide_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guidepb_guide_proto_rawDesc), len(file_guidepb_guide_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guidepb_guide_proto_goTypes,
		DependencyIndexes: file_guidepb_guide_proto_depIdxs,
		EnumInfos:         file_guidepb_guide_proto_enumTypes,
		MessageInfos:      file_guidepb_guide_proto_msgTypes,
	}.Build()
	File_guidepb_guide_proto = out.File
	file_guidepb_guide_proto_goTypes = nil
	file_guidepb_guide_proto_depIdxs = nil
}
