// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: friendpb/friend.proto

package friendpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	avatarframepb "qq-farm-bot/proto/avatarframepb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DryTimeSec    int64                  `protobuf:"varint,1,opt,name=dry_time_sec,json=dryTimeSec,proto3" json:"dry_time_sec,omitempty"`
	WeedTimeSec   int64                  `protobuf:"varint,2,opt,name=weed_time_sec,json=weedTimeSec,proto3" json:"weed_time_sec,omitempty"`
	InsectTimeSec int64                  `protobuf:"varint,3,opt,name=insect_time_sec,json=insectTimeSec,proto3" json:"insect_time_sec,omitempty"`
	RipeTimeSec   int64                  `protobuf:"varint,4,opt,name=ripe_time_sec,json=ripeTimeSec,proto3" json:"ripe_time_sec,omitempty"`
	RipeFruitId   int64                  `protobuf:"varint,5,opt,name=ripe_fruit_id,json=ripeFruitId,proto3" json:"ripe_fruit_id,omitempty"`
	StealPlantNum int64                  `protobuf:"varint,6,opt,name=steal_plant_num,json=stealPlantNum,proto3" json:"steal_plant_num,omitempty"`
	DryNum        int64                  `protobuf:"varint,7,opt,name=dry_num,json=dryNum,proto3" json:"dry_num,omitempty"`
	WeedNum       int64                  `protobuf:"varint,8,opt,name=weed_num,json=weedNum,proto3" json:"weed_num,omitempty"`
	InsectNum     int64                  `protobuf:"varint,9,opt,name=insect_num,json=insectNum,proto3" json:"insect_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plant) Reset() {
	*x = Plant{}
	mi := &file_friendpb_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plant) ProtoMessage() {}

func (x *Plant) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plant.ProtoReflect.Descriptor instead.
func (*Plant) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{0}
}

func (x *Plant) GetDryTimeSec() int64 {
	if x != nil {
		return x.DryTimeSec
	}
	return 0
}

func (x *Plant) GetWeedTimeSec() int64 {
	if x != nil {
		return x.WeedTimeSec
	}
	return 0
}

func (x *Plant) GetInsectTimeSec() int64 {
	if x != nil {
		return x.InsectTimeSec
	}
	return 0
}

func (x *Plant) GetRipeTimeSec() int64 {
	if x != nil {
		return x.RipeTimeSec
	}
	return 0
}

func (x *Plant) GetRipeFruitId() int64 {
	if x != nil {
		return x.RipeFruitId
	}
	return 0
}

func (x *Plant) GetStealPlantNum() int64 {
	if x != nil {
		return x.StealPlantNum
	}
	return 0
}

func (x *Plant) GetDryNum() int64 {
	if x != nil {
		return x.DryNum
	}
	return 0
}

func (x *Plant) GetWeedNum() int64 {
	if x != nil {
		return x.WeedNum
	}
	return 0
}

func (x *Plant) GetInsectNum() int64 {
	if x != nil {
		return x.InsectNum
	}
	return 0
}

type Tags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsNew         bool                   `protobuf:"varint,1,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	IsFollow      bool                   `protobuf:"varint,2,opt,name=is_follow,json=isFollow,proto3" json:"is_follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tags) Reset() {
	*x = Tags{}
	mi := &file_friendpb_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tags) ProtoMessage() {}

func (x *Tags) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tags.ProtoReflect.Descriptor instead.
func (*Tags) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{1}
}

func (x *Tags) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *Tags) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

type GameFriend struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Gid              int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	OpenId           string                 `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl        string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Remark           string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Level            int64                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Gold             int64                  `protobuf:"varint,7,opt,name=gold,proto3" json:"gold,omitempty"`
	Tags             *Tags                  `protobuf:"bytes,8,opt,name=tags,proto3" json:"tags,omitempty"`
	Plant            *Plant                 `protobuf:"bytes,9,opt,name=plant,proto3" json:"plant,omitempty"`
	AuthorizedStatus int32                  `protobuf:"varint,10,opt,name=authorized_status,json=authorizedStatus,proto3" json:"authorized_status,omitempty"`
	// field 11 reserved
	Illustrated       *Illustrated                 `protobuf:"bytes,12,opt,name=illustrated,proto3" json:"illustrated,omitempty"`
	EquipAvatarFrames []*avatarframepb.AvatarFrame `protobuf:"bytes,13,rep,name=equip_avatar_frames,json=equipAvatarFrames,proto3" json:"equip_avatar_frames,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameFriend) Reset() {
	*x = GameFriend{}
	mi := &file_friendpb_friend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameFriend) ProtoMessage() {}

func (x *GameFriend) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameFriend.ProtoReflect.Descriptor instead.
func (*GameFriend) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{2}
}

func (x *GameFriend) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *GameFriend) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *GameFriend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameFriend) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *GameFriend) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *GameFriend) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GameFriend) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *GameFriend) GetTags() *Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GameFriend) GetPlant() *Plant {
	if x != nil {
		return x.Plant
	}
	return nil
}

func (x *GameFriend) GetAuthorizedStatus() int32 {
	if x != nil {
		return x.AuthorizedStatus
	}
	return 0
}

func (x *GameFriend) GetIllustrated() *Illustrated {
	if x != nil {
		return x.Illustrated
	}
	return nil
}

func (x *GameFriend) GetEquipAvatarFrames() []*avatarframepb.AvatarFrame {
	if x != nil {
		return x.EquipAvatarFrames
	}
	return nil
}

type Illustrated struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NormalProgress  int32                  `protobuf:"varint,1,opt,name=normal_progress,json=normalProgress,proto3" json:"normal_progress,omitempty"`
	PremiumProgress int32                  `protobuf:"varint,2,opt,name=premium_progress,json=premiumProgress,proto3" json:"premium_progress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Illustrated) Reset() {
	*x = Illustrated{}
	mi := &file_friendpb_friend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Illustrated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Illustrated) ProtoMessage() {}

func (x *Illustrated) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Illustrated.ProtoReflect.Descriptor instead.
func (*Illustrated) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{3}
}

func (x *Illustrated) GetNormalProgress() int32 {
	if x != nil {
		return x.NormalProgress
	}
	return 0
}

func (x *Illustrated) GetPremiumProgress() int32 {
	if x != nil {
		return x.PremiumProgress
	}
	return 0
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_friendpb_friend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{4}
}

type GetAllReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GameFriends      []*GameFriend          `protobuf:"bytes,1,rep,name=game_friends,json=gameFriends,proto3" json:"game_friends,omitempty"`
	Invitations      []*Invitation          `protobuf:"bytes,2,rep,name=invitations,proto3" json:"invitations,omitempty"`
	ApplicationCount int64                  `protobuf:"varint,3,opt,name=application_count,json=applicationCount,proto3" json:"application_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAllReply) Reset() {
	*x = GetAllReply{}
	mi := &file_friendpb_friend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReply) ProtoMessage() {}

func (x *GetAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReply.ProtoReflect.Descriptor instead.
func (*GetAllReply) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllReply) GetGameFriends() []*GameFriend {
	if x != nil {
		return x.GameFriends
	}
	return nil
}

func (x *GetAllReply) GetInvitations() []*Invitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

func (x *GetAllReply) GetApplicationCount() int64 {
	if x != nil {
		return x.ApplicationCount
	}
	return 0
}

type SyncAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenIds       []string               `protobuf:"bytes,2,rep,name=open_ids,json=openIds,proto3" json:"open_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAllRequest) Reset() {
	*x = SyncAllRequest{}
	mi := &file_friendpb_friend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAllRequest) ProtoMessage() {}

func (x *SyncAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAllRequest.ProtoReflect.Descriptor instead.
func (*SyncAllRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{6}
}

func (x *SyncAllRequest) GetOpenIds() []string {
	if x != nil {
		return x.OpenIds
	}
	return nil
}

type SyncAllReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GameFriends      []*GameFriend          `protobuf:"bytes,1,rep,name=game_friends,json=gameFriends,proto3" json:"game_friends,omitempty"`
	Invitations      []*Invitation          `protobuf:"bytes,2,rep,name=invitations,proto3" json:"invitations,omitempty"`
	ApplicationCount int64                  `protobuf:"varint,3,opt,name=application_count,json=applicationCount,proto3" json:"application_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncAllReply) Reset() {
	*x = SyncAllReply{}
	mi := &file_friendpb_friend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAllReply) ProtoMessage() {}

func (x *SyncAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAllReply.ProtoReflect.Descriptor instead.
func (*SyncAllReply) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{7}
}

func (x *SyncAllReply) GetGameFriends() []*GameFriend {
	if x != nil {
		return x.GameFriends
	}
	return nil
}

func (x *SyncAllReply) GetInvitations() []*Invitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

func (x *SyncAllReply) GetApplicationCount() int64 {
	if x != nil {
		return x.ApplicationCount
	}
	return 0
}

type Application struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	TimeAt        int64                  `protobuf:"varint,2,opt,name=time_at,json=timeAt,proto3" json:"time_at,omitempty"`
	OpenId        string                 `protobuf:"bytes,3,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Level         int64                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_friendpb_friend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{8}
}

func (x *Application) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Application) GetTimeAt() int64 {
	if x != nil {
		return x.TimeAt
	}
	return 0
}

func (x *Application) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Application) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

type Invitation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	TimeAt        int64                  `protobuf:"varint,2,opt,name=time_at,json=timeAt,proto3" json:"time_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	mi := &file_friendpb_friend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{9}
}

func (x *Invitation) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *Invitation) GetTimeAt() int64 {
	if x != nil {
		return x.TimeAt
	}
	return 0
}

type GetApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationsRequest) Reset() {
	*x = GetApplicationsRequest{}
	mi := &file_friendpb_friend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationsRequest) ProtoMessage() {}

func (x *GetApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationsRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{10}
}

type GetApplicationsReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Applications      []*Application         `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	BlockApplications bool                   `protobuf:"varint,2,opt,name=block_applications,json=blockApplications,proto3" json:"block_applications,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetApplicationsReply) Reset() {
	*x = GetApplicationsReply{}
	mi := &file_friendpb_friend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationsReply) ProtoMessage() {}

func (x *GetApplicationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationsReply.ProtoReflect.Descriptor instead.
func (*GetApplicationsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{11}
}

func (x *GetApplicationsReply) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *GetApplicationsReply) GetBlockApplications() bool {
	if x != nil {
		return x.BlockApplications
	}
	return false
}

type AcceptFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendGids    []int64                `protobuf:"varint,1,rep,packed,name=friend_gids,json=friendGids,proto3" json:"friend_gids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendsRequest) Reset() {
	*x = AcceptFriendsRequest{}
	mi := &file_friendpb_friend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendsRequest) ProtoMessage() {}

func (x *AcceptFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendsRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{12}
}

func (x *AcceptFriendsRequest) GetFriendGids() []int64 {
	if x != nil {
		return x.FriendGids
	}
	return nil
}

type AcceptFriendsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*GameFriend          `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendsReply) Reset() {
	*x = AcceptFriendsReply{}
	mi := &file_friendpb_friend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendsReply) ProtoMessage() {}

func (x *AcceptFriendsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendsReply.ProtoReflect.Descriptor instead.
func (*AcceptFriendsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{13}
}

func (x *AcceptFriendsReply) GetFriends() []*GameFriend {
	if x != nil {
		return x.Friends
	}
	return nil
}

type RejectFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendGids    []int64                `protobuf:"varint,1,rep,packed,name=friend_gids,json=friendGids,proto3" json:"friend_gids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFriendsRequest) Reset() {
	*x = RejectFriendsRequest{}
	mi := &file_friendpb_friend_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendsRequest) ProtoMessage() {}

func (x *RejectFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendsRequest.ProtoReflect.Descriptor instead.
func (*RejectFriendsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{14}
}

func (x *RejectFriendsRequest) GetFriendGids() []int64 {
	if x != nil {
		return x.FriendGids
	}
	return nil
}

type RejectFriendsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFriendsReply) Reset() {
	*x = RejectFriendsReply{}
	mi := &file_friendpb_friend_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFriendsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendsReply) ProtoMessage() {}

func (x *RejectFriendsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendsReply.ProtoReflect.Descriptor instead.
func (*RejectFriendsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{15}
}

type SetBlockApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         bool                   `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBlockApplicationsRequest) Reset() {
	*x = SetBlockApplicationsRequest{}
	mi := &file_friendpb_friend_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBlockApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBlockApplicationsRequest) ProtoMessage() {}

func (x *SetBlockApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBlockApplicationsRequest.ProtoReflect.Descriptor instead.
func (*SetBlockApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{16}
}

func (x *SetBlockApplicationsRequest) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

type SetBlockApplicationsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         bool                   `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBlockApplicationsReply) Reset() {
	*x = SetBlockApplicationsReply{}
	mi := &file_friendpb_friend_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBlockApplicationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBlockApplicationsReply) ProtoMessage() {}

func (x *SetBlockApplicationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBlockApplicationsReply.ProtoReflect.Descriptor instead.
func (*SetBlockApplicationsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{17}
}

func (x *SetBlockApplicationsReply) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

type GetGameFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendGids    []int64                `protobuf:"varint,1,rep,packed,name=friend_gids,json=friendGids,proto3" json:"friend_gids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameFriendsRequest) Reset() {
	*x = GetGameFriendsRequest{}
	mi := &file_friendpb_friend_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameFriendsRequest) ProtoMessage() {}

func (x *GetGameFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameFriendsRequest.ProtoReflect.Descriptor instead.
func (*GetGameFriendsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{18}
}

func (x *GetGameFriendsRequest) GetFriendGids() []int64 {
	if x != nil {
		return x.FriendGids
	}
	return nil
}

type GetGameFriendsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*GameFriend          `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameFriendsReply) Reset() {
	*x = GetGameFriendsReply{}
	mi := &file_friendpb_friend_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameFriendsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameFriendsReply) ProtoMessage() {}

func (x *GetGameFriendsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameFriendsReply.ProtoReflect.Descriptor instead.
func (*GetGameFriendsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{19}
}

func (x *GetGameFriendsReply) GetFriends() []*GameFriend {
	if x != nil {
		return x.Friends
	}
	return nil
}

type SetTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendGid     int64                  `protobuf:"varint,1,opt,name=friend_gid,json=friendGid,proto3" json:"friend_gid,omitempty"`
	Tags          *Tags                  `protobuf:"bytes,2,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTagsRequest) Reset() {
	*x = SetTagsRequest{}
	mi := &file_friendpb_friend_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagsRequest) ProtoMessage() {}

func (x *SetTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagsRequest.ProtoReflect.Descriptor instead.
func (*SetTagsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{20}
}

func (x *SetTagsRequest) GetFriendGid() int64 {
	if x != nil {
		return x.FriendGid
	}
	return 0
}

func (x *SetTagsRequest) GetTags() *Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SetTagsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTagsReply) Reset() {
	*x = SetTagsReply{}
	mi := &file_friendpb_friend_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTagsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagsReply) ProtoMessage() {}

func (x *SetTagsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagsReply.ProtoReflect.Descriptor instead.
func (*SetTagsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{21}
}

type ReportInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInvitationRequest) Reset() {
	*x = ReportInvitationRequest{}
	mi := &file_friendpb_friend_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInvitationRequest) ProtoMessage() {}

func (x *ReportInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInvitationRequest.ProtoReflect.Descriptor instead.
func (*ReportInvitationRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{22}
}

func (x *ReportInvitationRequest) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

type ReportInvitationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInvitationReply) Reset() {
	*x = ReportInvitationReply{}
	mi := &file_friendpb_friend_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInvitationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInvitationReply) ProtoMessage() {}

func (x *ReportInvitationReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInvitationReply.ProtoReflect.Descriptor instead.
func (*ReportInvitationReply) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{23}
}

type DelFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelFriendRequest) Reset() {
	*x = DelFriendRequest{}
	mi := &file_friendpb_friend_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFriendRequest) ProtoMessage() {}

func (x *DelFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFriendRequest.ProtoReflect.Descriptor instead.
func (*DelFriendRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{24}
}

func (x *DelFriendRequest) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type DelFriendReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelFriendReply) Reset() {
	*x = DelFriendReply{}
	mi := &file_friendpb_friend_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelFriendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFriendReply) ProtoMessage() {}

func (x *DelFriendReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFriendReply.ProtoReflect.Descriptor instead.
func (*DelFriendReply) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{25}
}

type FriendApplicationReceivedNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*Application         `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendApplicationReceivedNotify) Reset() {
	*x = FriendApplicationReceivedNotify{}
	mi := &file_friendpb_friend_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendApplicationReceivedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendApplicationReceivedNotify) ProtoMessage() {}

func (x *FriendApplicationReceivedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendApplicationReceivedNotify.ProtoReflect.Descriptor instead.
func (*FriendApplicationReceivedNotify) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{26}
}

func (x *FriendApplicationReceivedNotify) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

type FriendAddedNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*GameFriend          `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendAddedNotify) Reset() {
	*x = FriendAddedNotify{}
	mi := &file_friendpb_friend_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendAddedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendAddedNotify) ProtoMessage() {}

func (x *FriendAddedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendAddedNotify.ProtoReflect.Descriptor instead.
func (*FriendAddedNotify) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{27}
}

func (x *FriendAddedNotify) GetFriends() []*GameFriend {
	if x != nil {
		return x.Friends
	}
	return nil
}

type DelFriendNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelFriendNotify) Reset() {
	*x = DelFriendNotify{}
	mi := &file_friendpb_friend_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelFriendNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFriendNotify) ProtoMessage() {}

func (x *DelFriendNotify) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_friend_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFriendNotify.ProtoReflect.Descriptor instead.
func (*DelFriendNotify) Descriptor() ([]byte, []int) {
	return file_friendpb_friend_proto_rawDescGZIP(), []int{28}
}

func (x *DelFriendNotify) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

var File_friendpb_friend_proto protoreflect.FileDescriptor

const file_friendpb_friend_proto_rawDesc = "" +
	"\n" +
	"\x15friendpb/friend.proto\x12\x0fgamepb.friendpb\x1a\x1favatarframepb/avatarframe.proto\"\xb8\x02\n" +
	"\x05Plant\x12 \n" +
	"\fdry_time_sec\x18\x01 \x01(\x03R\n" +
	"dryTimeSec\x12\"\n" +
	"\rweed_time_sec\x18\x02 \x01(\x03R\vweedTimeSec\x12&\n" +
	"\x0finsect_time_sec\x18\x03 \x01(\x03R\rinsectTimeSec\x12\"\n" +
	"\rripe_time_sec\x18\x04 \x01(\x03R\vripeTimeSec\x12\"\n" +
	"\rripe_fruit_id\x18\x05 \x01(\x03R\vripeFruitId\x12&\n" +
	"\x0fsteal_plant_num\x18\x06 \x01(\x03R\rstealPlantNum\x12\x17\n" +
	"\adry_num\x18\a \x01(\x03R\x06dryNum\x12\x19\n" +
	"\bweed_num\x18\b \x01(\x03R\aweedNum\x12\x1d\n" +
	"\n" +
	"insect_num\x18\t \x01(\x03R\tinsectNum\":\n" +
	"\x04Tags\x12\x15\n" +
	"\x06is_new\x18\x01 \x01(\bR\x05isNew\x12\x1b\n" +
	"\tis_follow\x18\x02 \x01(\bR\bisFollow\"\xc5\x03\n" +
	"\n" +
	"GameFriend\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\x03R\x03gid\x12\x17\n" +
	"\aopen_id\x18\x02 \x01(\tR\x06openId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x03R\x05level\x12\x12\n" +
	"\x04gold\x18\a \x01(\x03R\x04gold\x12)\n" +
	"\x04tags\x18\b \x01(\v2\x15.gamepb.friendpb.TagsR\x04tags\x12,\n" +
	"\x05plant\x18\t \x01(\v2\x16.gamepb.friendpb.PlantR\x05plant\x12+\n" +
	"\x11authorized_status\x18\n" +
	" \x01(\x05R\x10authorizedStatus\x12>\n" +
	"\villustrated\x18\f \x01(\v2\x1c.gamepb.friendpb.IllustratedR\villustrated\x12Q\n" +
	"\x13equip_avatar_frames\x18\r \x03(\v2!.gamepb.avatarframepb.AvatarFrameR\x11equipAvatarFrames\"a\n" +
	"\vIllustrated\x12'\n" +
	"\x0fnormal_progress\x18\x01 \x01(\x05R\x0enormalProgress\x12)\n" +
	"\x10premium_progress\x18\x02 \x01(\x05R\x0fpremiumProgress\"\x0f\n" +
	"\rGetAllRequest\"\xb9\x01\n" +
	"\vGetAllReply\x12>\n" +
	"\fgame_friends\x18\x01 \x03(\v2\x1b.gamepb.friendpb.GameFriendR\vgameFriends\x12=\n" +
	"\vinvitations\x18\x02 \x03(\v2\x1b.gamepb.friendpb.InvitationR\vinvitations\x12+\n" +
	"\x11application_count\x18\x03 \x01(\x03R\x10applicationCount\"+\n" +
	"\x0eSyncAllRequest\x12\x19\n" +
	"\bopen_ids\x18\x02 \x03(\tR\aopenIds\"\xba\x01\n" +
	"\fSyncAllReply\x12>\n" +
	"\fgame_friends\x18\x01 \x03(\v2\x1b.gamepb.friendpb.GameFriendR\vgameFriends\x12=\n" +
	"\vinvitations\x18\x02 \x03(\v2\x1b.gamepb.friendpb.InvitationR\vinvitations\x12+\n" +
	"\x11application_count\x18\x03 \x01(\x03R\x10applicationCount\"\x9a\x01\n" +
	"\vApplication\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\x03R\x03gid\x12\x17\n" +
	"\atime_at\x18\x02 \x01(\x03R\x06timeAt\x12\x17\n" +
	"\aopen_id\x18\x03 \x01(\tR\x06openId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x03R\x05level\">\n" +
	"\n" +
	"Invitation\x12\x17\n" +
	"\aopen_id\x18\x01 \x01(\tR\x06openId\x12\x17\n" +
	"\atime_at\x18\x02 \x01(\x03R\x06timeAt\"\x18\n" +
	"\x16GetApplicationsRequest\"\x87\x01\n" +
	"\x14GetApplicationsReply\x12@\n" +
	"\fapplications\x18\x01 \x03(\v2\x1c.gamepb.friendpb.ApplicationR\fapplications\x12-\n" +
	"\x12block_applications\x18\x02 \x01(\bR\x11blockApplications\"7\n" +
	"\x14AcceptFriendsRequest\x12\x1f\n" +
	"\vfriend_gids\x18\x01 \x03(\x03R\n" +
	"friendGids\"K\n" +
	"\x12AcceptFriendsReply\x125\n" +
	"\afriends\x18\x01 \x03(\v2\x1b.gamepb.friendpb.GameFriendR\afriends\"7\n" +
	"\x14RejectFriendsRequest\x12\x1f\n" +
	"\vfriend_gids\x18\x01 \x03(\x03R\n" +
	"friendGids\"\x14\n" +
	"\x12RejectFriendsReply\"3\n" +
	"\x1bSetBlockApplicationsRequest\x12\x14\n" +
	"\x05block\x18\x01 \x01(\bR\x05block\"1\n" +
	"\x19SetBlockApplicationsReply\x12\x14\n" +
	"\x05block\x18\x01 \x01(\bR\x05block\"8\n" +
	"\x15GetGameFriendsRequest\x12\x1f\n" +
	"\vfriend_gids\x18\x01 \x03(\x03R\n" +
	"friendGids\"L\n" +
	"\x13GetGameFriendsReply\x125\n" +
	"\afriends\x18\x01 \x03(\v2\x1b.gamepb.friendpb.GameFriendR\afriends\"Z\n" +
	"\x0eSetTagsRequest\x12\x1d\n" +
	"\n" +
	"friend_gid\x18\x01 \x01(\x03R\tfriendGid\x12)\n" +
	"\x04tags\x18\x02 \x01(\v2\x15.gamepb.friendpb.TagsR\x04tags\"\x0e\n" +
	"\fSetTagsReply\"2\n" +
	"\x17ReportInvitationRequest\x12\x17\n" +
	"\aopen_id\x18\x01 \x01(\tR\x06openId\"\x17\n" +
	"\x15ReportInvitationReply\"$\n" +
	"\x10DelFriendRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\x03R\x03gid\"\x10\n" +
	"\x0eDelFriendReply\"c\n" +
	"\x1fFriendApplicationReceivedNotify\x12@\n" +
	"\fapplications\x18\x01 \x03(\v2\x1c.gamepb.friendpb.ApplicationR\fapplications\"J\n" +
	"\x11FriendAddedNotify\x125\n" +
	"\afriends\x18\x01 \x03(\v2\x1b.gamepb.friendpb.GameFriendR\afriends\"#\n" +
	"\x0fDelFriendNotify\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\x03R\x03gidB\x1cZ\x1aqq-farm-bot/proto/friendpbb\x06proto3"

var (
	file_friendpb_friend_proto_rawDescOnce sync.Once
	file_friendpb_friend_proto_rawDescData []byte
)

func file_friendpb_friend_proto_rawDescGZIP() []byte {
	file_friendpb_friend_proto_rawDescOnce.Do(func() {
		file_friendpb_friend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friendpb_friend_proto_rawDesc), len(file_friendpb_friend_proto_rawDesc)))
	})
	return file_friendpb_friend_proto_rawDescData
}

var file_friendpb_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_friendpb_friend_proto_goTypes = []any{
	(*Plant)(nil),                           // 0: gamepb.friendpb.Plant
	(*Tags)(nil),                            // 1: gamepb.friendpb.Tags
	(*GameFriend)(nil),                      // 2: gamepb.friendpb.GameFriend
	(*Illustrated)(nil),                     // 3: gamepb.friendpb.Illustrated
	(*GetAllRequest)(nil),                   // 4: gamepb.friendpb.GetAllRequest
	(*GetAllReply)(nil),                     // 5: gamepb.friendpb.GetAllReply
	(*SyncAllRequest)(nil),                  // 6: gamepb.friendpb.SyncAllRequest
	(*SyncAllReply)(nil),                    // 7: gamepb.friendpb.SyncAllReply
	(*Application)(nil),                     // 8: gamepb.friendpb.Application
	(*Invitation)(nil),                      // 9: gamepb.friendpb.Invitation
	(*GetApplicationsRequest)(nil),          // 10: gamepb.friendpb.GetApplicationsRequest
	(*GetApplicationsReply)(nil),            // 11: gamepb.friendpb.GetApplicationsReply
	(*AcceptFriendsRequest)(nil),            // 12: gamepb.friendpb.AcceptFriendsRequest
	(*AcceptFriendsReply)(nil),              // 13: gamepb.friendpb.AcceptFriendsReply
	(*RejectFriendsRequest)(nil),            // 14: gamepb.friendpb.RejectFriendsRequest
	(*RejectFriendsReply)(nil),              // 15: gamepb.friendpb.RejectFriendsReply
	(*SetBlockApplicationsRequest)(nil),     // 16: gamepb.friendpb.SetBlockApplicationsRequest
	(*SetBlockApplicationsReply)(nil),       // 17: gamepb.friendpb.SetBlockApplicationsReply
	(*GetGameFriendsRequest)(nil),           // 18: gamepb.friendpb.GetGameFriendsRequest
	(*GetGameFriendsReply)(nil),             // 19: gamepb.friendpb.GetGameFriendsReply
	(*SetTagsRequest)(nil),                  // 20: gamepb.friendpb.SetTagsRequest
	(*SetTagsReply)(nil),                    // 21: gamepb.friendpb.SetTagsReply
	(*ReportInvitationRequest)(nil),         // 22: gamepb.friendpb.ReportInvitationRequest
	(*ReportInvitationReply)(nil),           // 23: gamepb.friendpb.ReportInvitationReply
	(*DelFriendRequest)(nil),                // 24: gamepb.friendpb.DelFriendRequest
	(*DelFriendReply)(nil),                  // 25: gamepb.friendpb.DelFriendReply
	(*FriendApplicationReceivedNotify)(nil), // 26: gamepb.friendpb.FriendApplicationReceivedNotify
	(*FriendAddedNotify)(nil),               // 27: gamepb.friendpb.FriendAddedNotify
	(*DelFriendNotify)(nil),                 // 28: gamepb.friendpb.DelFriendNotify
	(*avatarframepb.AvatarFrame)(nil),       // 29: gamepb.avatarframepb.AvatarFrame
}
var file_friendpb_friend_proto_depIdxs = []int32{
	1,  // 0: gamepb.friendpb.GameFriend.tags:type_name -> gamepb.friendpb.Tags
	0,  // 1: gamepb.friendpb.GameFriend.plant:type_name -> gamepb.friendpb.Plant
	3,  // 2: gamepb.friendpb.GameFriend.illustrated:type_name -> gamepb.friendpb.Illustrated
	29, // 3: gamepb.friendpb.GameFriend.equip_avatar_frames:type_name -> gamepb.avatarframepb.AvatarFrame
	2,  // 4: gamepb.friendpb.GetAllReply.game_friends:type_name -> gamepb.friendpb.GameFriend
	9,  // 5: gamepb.friendpb.GetAllReply.invitations:type_name -> gamepb.friendpb.Invitation
	2,  // 6: gamepb.friendpb.SyncAllReply.game_friends:type_name -> gamepb.friendpb.GameFriend
	9,  // 7: gamepb.friendpb.SyncAllReply.invitations:type_name -> gamepb.friendpb.Invitation
	8,  // 8: gamepb.friendpb.GetApplicationsReply.applications:type_name -> gamepb.friendpb.Application
	2,  // 9: gamepb.friendpb.AcceptFriendsReply.friends:type_name -> gamepb.friendpb.GameFriend
	2,  // 10: gamepb.friendpb.GetGameFriendsReply.friends:type_name -> gamepb.friendpb.GameFriend
	1,  // 11: gamepb.friendpb.SetTagsRequest.tags:type_name -> gamepb.friendpb.Tags
	8,  // 12: gamepb.friendpb.FriendApplicationReceivedNotify.applications:type_name -> gamepb.friendpb.Application
	2,  // 13: gamepb.friendpb.FriendAddedNotify.friends:type_name -> gamepb.friendpb.GameFriend
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_friendpb_friend_proto_init() }
func file_friendpb_friend_proto_init() {
	if File_friendpb_friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friendpb_friend_proto_rawDesc), len(file_friendpb_friend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_friendpb_friend_proto_goTypes,
		DependencyIndexes: file_friendpb_friend_proto_depIdxs,
		MessageInfos:      file_friendpb_friend_proto_msgTypes,
	}.Build()
	File_friendpb_friend_proto = out.File
	file_friendpb_friend_proto_goTypes = nil
	file_friendpb_friend_proto_depIdxs = nil
}
