// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: userpb/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionStatus int32

const (
	VersionStatus_VERSION_STATUS_UNKNOWN   VersionStatus = 0
	VersionStatus_VERSION_STATUS_RECOMMEND VersionStatus = 1
	VersionStatus_VERSION_STATUS_FORCE     VersionStatus = 2
)

// Enum value maps for VersionStatus.
var (
	VersionStatus_name = map[int32]string{
		0: "VERSION_STATUS_UNKNOWN",
		1: "VERSION_STATUS_RECOMMEND",
		2: "VERSION_STATUS_FORCE",
	}
	VersionStatus_value = map[string]int32{
		"VERSION_STATUS_UNKNOWN":   0,
		"VERSION_STATUS_RECOMMEND": 1,
		"VERSION_STATUS_FORCE":     2,
	}
)

func (x VersionStatus) Enum() *VersionStatus {
	p := new(VersionStatus)
	*p = x
	return p
}

func (x VersionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VersionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_userpb_user_proto_enumTypes[0].Descriptor()
}

func (VersionStatus) Type() protoreflect.EnumType {
	return &file_userpb_user_proto_enumTypes[0]
}

func (x VersionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VersionStatus.Descriptor instead.
func (VersionStatus) EnumDescriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{0}
}

type CertType int32

const (
	CertType_CERT_TYPE_CHINA_ID_CARD     CertType = 0
	CertType_CERT_TYPE_OVERSEAS_PASSPORT CertType = 414
	CertType_CERT_TYPE_HK_MACAU_TAIWAN   CertType = 516
	CertType_CERT_TYPE_FOREIGN_PERMANENT CertType = 553
	CertType_CERT_TYPE_OTHER             CertType = 555
)

// Enum value maps for CertType.
var (
	CertType_name = map[int32]string{
		0:   "CERT_TYPE_CHINA_ID_CARD",
		414: "CERT_TYPE_OVERSEAS_PASSPORT",
		516: "CERT_TYPE_HK_MACAU_TAIWAN",
		553: "CERT_TYPE_FOREIGN_PERMANENT",
		555: "CERT_TYPE_OTHER",
	}
	CertType_value = map[string]int32{
		"CERT_TYPE_CHINA_ID_CARD":     0,
		"CERT_TYPE_OVERSEAS_PASSPORT": 414,
		"CERT_TYPE_HK_MACAU_TAIWAN":   516,
		"CERT_TYPE_FOREIGN_PERMANENT": 553,
		"CERT_TYPE_OTHER":             555,
	}
)

func (x CertType) Enum() *CertType {
	p := new(CertType)
	*p = x
	return p
}

func (x CertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertType) Descriptor() protoreflect.EnumDescriptor {
	return file_userpb_user_proto_enumTypes[1].Descriptor()
}

func (CertType) Type() protoreflect.EnumType {
	return &file_userpb_user_proto_enumTypes[1]
}

func (x CertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertType.Descriptor instead.
func (CertType) EnumDescriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{1}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SharerId      int64                  `protobuf:"varint,3,opt,name=sharer_id,json=sharerId,proto3" json:"sharer_id,omitempty"`
	SharerOpenId  string                 `protobuf:"bytes,4,opt,name=sharer_open_id,json=sharerOpenId,proto3" json:"sharer_open_id,omitempty"`
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,5,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	ShareCfgId    int64                  `protobuf:"varint,6,opt,name=share_cfg_id,json=shareCfgId,proto3" json:"share_cfg_id,omitempty"`
	SceneId       string                 `protobuf:"bytes,7,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	ReportData    *ReportData            `protobuf:"bytes,8,opt,name=report_data,json=reportData,proto3" json:"report_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_userpb_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetSharerId() int64 {
	if x != nil {
		return x.SharerId
	}
	return 0
}

func (x *LoginRequest) GetSharerOpenId() string {
	if x != nil {
		return x.SharerOpenId
	}
	return ""
}

func (x *LoginRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *LoginRequest) GetShareCfgId() int64 {
	if x != nil {
		return x.ShareCfgId
	}
	return 0
}

func (x *LoginRequest) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

func (x *LoginRequest) GetReportData() *ReportData {
	if x != nil {
		return x.ReportData
	}
	return nil
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	SysSoftware   string                 `protobuf:"bytes,2,opt,name=sys_software,json=sysSoftware,proto3" json:"sys_software,omitempty"`
	SysHardware   string                 `protobuf:"bytes,3,opt,name=sys_hardware,json=sysHardware,proto3" json:"sys_hardware,omitempty"`
	TelecomOper   string                 `protobuf:"bytes,4,opt,name=telecom_oper,json=telecomOper,proto3" json:"telecom_oper,omitempty"`
	Network       string                 `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	ScreenWidth   int64                  `protobuf:"varint,6,opt,name=screen_width,json=screenWidth,proto3" json:"screen_width,omitempty"`
	ScreenHeight  int64                  `protobuf:"varint,7,opt,name=screen_height,json=screenHeight,proto3" json:"screen_height,omitempty"`
	Density       float32                `protobuf:"fixed32,8,opt,name=density,proto3" json:"density,omitempty"`
	Cpu           string                 `protobuf:"bytes,9,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int64                  `protobuf:"varint,10,opt,name=memory,proto3" json:"memory,omitempty"`
	GlRender      string                 `protobuf:"bytes,11,opt,name=gl_render,json=glRender,proto3" json:"gl_render,omitempty"`
	GlVersion     string                 `protobuf:"bytes,12,opt,name=gl_version,json=glVersion,proto3" json:"gl_version,omitempty"`
	DeviceId      string                 `protobuf:"bytes,13,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AndroidOaid   string                 `protobuf:"bytes,14,opt,name=android_oaid,json=androidOaid,proto3" json:"android_oaid,omitempty"`
	IosCaid       string                 `protobuf:"bytes,15,opt,name=ios_caid,json=iosCaid,proto3" json:"ios_caid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_userpb_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfo) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *DeviceInfo) GetSysSoftware() string {
	if x != nil {
		return x.SysSoftware
	}
	return ""
}

func (x *DeviceInfo) GetSysHardware() string {
	if x != nil {
		return x.SysHardware
	}
	return ""
}

func (x *DeviceInfo) GetTelecomOper() string {
	if x != nil {
		return x.TelecomOper
	}
	return ""
}

func (x *DeviceInfo) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DeviceInfo) GetScreenWidth() int64 {
	if x != nil {
		return x.ScreenWidth
	}
	return 0
}

func (x *DeviceInfo) GetScreenHeight() int64 {
	if x != nil {
		return x.ScreenHeight
	}
	return 0
}

func (x *DeviceInfo) GetDensity() float32 {
	if x != nil {
		return x.Density
	}
	return 0
}

func (x *DeviceInfo) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *DeviceInfo) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *DeviceInfo) GetGlRender() string {
	if x != nil {
		return x.GlRender
	}
	return ""
}

func (x *DeviceInfo) GetGlVersion() string {
	if x != nil {
		return x.GlVersion
	}
	return ""
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetAndroidOaid() string {
	if x != nil {
		return x.AndroidOaid
	}
	return ""
}

func (x *DeviceInfo) GetIosCaid() string {
	if x != nil {
		return x.IosCaid
	}
	return ""
}

type ReportData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Callback        string                 `protobuf:"bytes,1,opt,name=callback,proto3" json:"callback,omitempty"`
	CdExtendInfo    string                 `protobuf:"bytes,2,opt,name=cd_extend_info,json=cdExtendInfo,proto3" json:"cd_extend_info,omitempty"`
	ClickId         string                 `protobuf:"bytes,3,opt,name=click_id,json=clickId,proto3" json:"click_id,omitempty"`
	ClueToken       string                 `protobuf:"bytes,4,opt,name=clue_token,json=clueToken,proto3" json:"clue_token,omitempty"`
	MinigameChannel string                 `protobuf:"bytes,5,opt,name=minigame_channel,json=minigameChannel,proto3" json:"minigame_channel,omitempty"`
	MinigamePlatid  int32                  `protobuf:"varint,6,opt,name=minigame_platid,json=minigamePlatid,proto3" json:"minigame_platid,omitempty"`
	ReqId           string                 `protobuf:"bytes,7,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Trackid         string                 `protobuf:"bytes,8,opt,name=trackid,proto3" json:"trackid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportData) Reset() {
	*x = ReportData{}
	mi := &file_userpb_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportData) ProtoMessage() {}

func (x *ReportData) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportData.ProtoReflect.Descriptor instead.
func (*ReportData) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{2}
}

func (x *ReportData) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *ReportData) GetCdExtendInfo() string {
	if x != nil {
		return x.CdExtendInfo
	}
	return ""
}

func (x *ReportData) GetClickId() string {
	if x != nil {
		return x.ClickId
	}
	return ""
}

func (x *ReportData) GetClueToken() string {
	if x != nil {
		return x.ClueToken
	}
	return ""
}

func (x *ReportData) GetMinigameChannel() string {
	if x != nil {
		return x.MinigameChannel
	}
	return ""
}

func (x *ReportData) GetMinigamePlatid() int32 {
	if x != nil {
		return x.MinigamePlatid
	}
	return 0
}

func (x *ReportData) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *ReportData) GetTrackid() string {
	if x != nil {
		return x.Trackid
	}
	return ""
}

type LoginReply struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Basic                       *BasicInfo             `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`
	TimeNowMillis               int64                  `protobuf:"varint,3,opt,name=time_now_millis,json=timeNowMillis,proto3" json:"time_now_millis,omitempty"`
	IsFirstLogin                bool                   `protobuf:"varint,4,opt,name=is_first_login,json=isFirstLogin,proto3" json:"is_first_login,omitempty"`
	QqGroupInfos                []*QQGroupInfo         `protobuf:"bytes,6,rep,name=qq_group_infos,json=qqGroupInfos,proto3" json:"qq_group_infos,omitempty"`
	VersionInfo                 *VersionInfo           `protobuf:"bytes,9,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	QqFriendRecommendAuthorized int64                  `protobuf:"varint,11,opt,name=qq_friend_recommend_authorized,json=qqFriendRecommendAuthorized,proto3" json:"qq_friend_recommend_authorized,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_userpb_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetBasic() *BasicInfo {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *LoginReply) GetTimeNowMillis() int64 {
	if x != nil {
		return x.TimeNowMillis
	}
	return 0
}

func (x *LoginReply) GetIsFirstLogin() bool {
	if x != nil {
		return x.IsFirstLogin
	}
	return false
}

func (x *LoginReply) GetQqGroupInfos() []*QQGroupInfo {
	if x != nil {
		return x.QqGroupInfos
	}
	return nil
}

func (x *LoginReply) GetVersionInfo() *VersionInfo {
	if x != nil {
		return x.VersionInfo
	}
	return nil
}

func (x *LoginReply) GetQqFriendRecommendAuthorized() int64 {
	if x != nil {
		return x.QqFriendRecommendAuthorized
	}
	return 0
}

type BasicInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Gid              int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level            int64                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Exp              int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Gold             int64                  `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"`
	OpenId           string                 `protobuf:"bytes,6,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	AvatarUrl        string                 `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Remark           string                 `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Signature        string                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	Gender           int32                  `protobuf:"varint,10,opt,name=gender,proto3" json:"gender,omitempty"`
	AuthorizedStatus int32                  `protobuf:"varint,13,opt,name=authorized_status,json=authorizedStatus,proto3" json:"authorized_status,omitempty"`
	DisableNudge     bool                   `protobuf:"varint,14,opt,name=disable_nudge,json=disableNudge,proto3" json:"disable_nudge,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BasicInfo) Reset() {
	*x = BasicInfo{}
	mi := &file_userpb_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicInfo) ProtoMessage() {}

func (x *BasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicInfo.ProtoReflect.Descriptor instead.
func (*BasicInfo) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{4}
}

func (x *BasicInfo) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *BasicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BasicInfo) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *BasicInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *BasicInfo) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *BasicInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *BasicInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *BasicInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *BasicInfo) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *BasicInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *BasicInfo) GetAuthorizedStatus() int32 {
	if x != nil {
		return x.AuthorizedStatus
	}
	return 0
}

func (x *BasicInfo) GetDisableNudge() bool {
	if x != nil {
		return x.DisableNudge
	}
	return false
}

type QQGroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QqGroupId     string                 `protobuf:"bytes,1,opt,name=qq_group_id,json=qqGroupId,proto3" json:"qq_group_id,omitempty"`
	QqGroupName   string                 `protobuf:"bytes,2,opt,name=qq_group_name,json=qqGroupName,proto3" json:"qq_group_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QQGroupInfo) Reset() {
	*x = QQGroupInfo{}
	mi := &file_userpb_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QQGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QQGroupInfo) ProtoMessage() {}

func (x *QQGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QQGroupInfo.ProtoReflect.Descriptor instead.
func (*QQGroupInfo) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{5}
}

func (x *QQGroupInfo) GetQqGroupId() string {
	if x != nil {
		return x.QqGroupId
	}
	return ""
}

func (x *QQGroupInfo) GetQqGroupName() string {
	if x != nil {
		return x.QqGroupName
	}
	return ""
}

type VersionInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	VersionRecommend string                 `protobuf:"bytes,2,opt,name=version_recommend,json=versionRecommend,proto3" json:"version_recommend,omitempty"`
	VersionForce     string                 `protobuf:"bytes,3,opt,name=version_force,json=versionForce,proto3" json:"version_force,omitempty"`
	ResVersion       string                 `protobuf:"bytes,4,opt,name=res_version,json=resVersion,proto3" json:"res_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	mi := &file_userpb_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{6}
}

func (x *VersionInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VersionInfo) GetVersionRecommend() string {
	if x != nil {
		return x.VersionRecommend
	}
	return ""
}

func (x *VersionInfo) GetVersionForce() string {
	if x != nil {
		return x.VersionForce
	}
	return ""
}

func (x *VersionInfo) GetResVersion() string {
	if x != nil {
		return x.ResVersion
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           int64                  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	ClientVersion string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_userpb_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *HeartbeatRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type HeartbeatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	VersionInfo   *VersionInfo           `protobuf:"bytes,2,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	mi := &file_userpb_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatReply) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *HeartbeatReply) GetVersionInfo() *VersionInfo {
	if x != nil {
		return x.VersionInfo
	}
	return nil
}

type FriendInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendInfo) Reset() {
	*x = FriendInfo{}
	mi := &file_userpb_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInfo) ProtoMessage() {}

func (x *FriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInfo.ProtoReflect.Descriptor instead.
func (*FriendInfo) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{9}
}

func (x *FriendInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

type QQVipInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsVip         bool                   `protobuf:"varint,1,opt,name=is_vip,json=isVip,proto3" json:"is_vip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QQVipInfo) Reset() {
	*x = QQVipInfo{}
	mi := &file_userpb_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QQVipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QQVipInfo) ProtoMessage() {}

func (x *QQVipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QQVipInfo.ProtoReflect.Descriptor instead.
func (*QQVipInfo) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{10}
}

func (x *QQVipInfo) GetIsVip() bool {
	if x != nil {
		return x.IsVip
	}
	return false
}

type SetDisplayInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDisplayInfoRequest) Reset() {
	*x = SetDisplayInfoRequest{}
	mi := &file_userpb_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDisplayInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDisplayInfoRequest) ProtoMessage() {}

func (x *SetDisplayInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDisplayInfoRequest.ProtoReflect.Descriptor instead.
func (*SetDisplayInfoRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{11}
}

func (x *SetDisplayInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetDisplayInfoRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *SetDisplayInfoRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SetDisplayInfoRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *SetDisplayInfoRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type SetDisplayInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDisplayInfoReply) Reset() {
	*x = SetDisplayInfoReply{}
	mi := &file_userpb_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDisplayInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDisplayInfoReply) ProtoMessage() {}

func (x *SetDisplayInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDisplayInfoReply.ProtoReflect.Descriptor instead.
func (*SetDisplayInfoReply) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{12}
}

func (x *SetDisplayInfoReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetDisplayInfoReply) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *SetDisplayInfoReply) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SetDisplayInfoReply) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *SetDisplayInfoReply) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type ReportArkClickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SharerId      int64                  `protobuf:"varint,1,opt,name=sharer_id,json=sharerId,proto3" json:"sharer_id,omitempty"`
	SharerOpenId  string                 `protobuf:"bytes,2,opt,name=sharer_open_id,json=sharerOpenId,proto3" json:"sharer_open_id,omitempty"`
	SceneId       string                 `protobuf:"bytes,3,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	ShareCfgId    int64                  `protobuf:"varint,4,opt,name=share_cfg_id,json=shareCfgId,proto3" json:"share_cfg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportArkClickRequest) Reset() {
	*x = ReportArkClickRequest{}
	mi := &file_userpb_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportArkClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportArkClickRequest) ProtoMessage() {}

func (x *ReportArkClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportArkClickRequest.ProtoReflect.Descriptor instead.
func (*ReportArkClickRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{13}
}

func (x *ReportArkClickRequest) GetSharerId() int64 {
	if x != nil {
		return x.SharerId
	}
	return 0
}

func (x *ReportArkClickRequest) GetSharerOpenId() string {
	if x != nil {
		return x.SharerOpenId
	}
	return ""
}

func (x *ReportArkClickRequest) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

func (x *ReportArkClickRequest) GetShareCfgId() int64 {
	if x != nil {
		return x.ShareCfgId
	}
	return 0
}

type ReportArkClickReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportArkClickReply) Reset() {
	*x = ReportArkClickReply{}
	mi := &file_userpb_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportArkClickReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportArkClickReply) ProtoMessage() {}

func (x *ReportArkClickReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportArkClickReply.ProtoReflect.Descriptor instead.
func (*ReportArkClickReply) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{14}
}

type BasicNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basic         *BasicInfo             `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicNotify) Reset() {
	*x = BasicNotify{}
	mi := &file_userpb_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicNotify) ProtoMessage() {}

func (x *BasicNotify) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicNotify.ProtoReflect.Descriptor instead.
func (*BasicNotify) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{15}
}

func (x *BasicNotify) GetBasic() *BasicInfo {
	if x != nil {
		return x.Basic
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_userpb_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{16}
}

func (x *LogoutRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_userpb_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{17}
}

type ClientReportFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OsType        int32                  `protobuf:"varint,1,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	PlatFromType  int32                  `protobuf:"varint,2,opt,name=plat_from_type,json=platFromType,proto3" json:"plat_from_type,omitempty"`
	OpenId        string                 `protobuf:"bytes,3,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Gid           int64                  `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Now           int64                  `protobuf:"varint,6,opt,name=now,proto3" json:"now,omitempty"`
	Level         int64                  `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	FlowType      int64                  `protobuf:"varint,101,opt,name=flow_type,json=flowType,proto3" json:"flow_type,omitempty"`
	FlowTypeStr   string                 `protobuf:"bytes,102,opt,name=flow_type_str,json=flowTypeStr,proto3" json:"flow_type_str,omitempty"`
	ParamInt1     int64                  `protobuf:"varint,103,opt,name=param_int1,json=paramInt1,proto3" json:"param_int1,omitempty"`
	ParamInt2     int64                  `protobuf:"varint,104,opt,name=param_int2,json=paramInt2,proto3" json:"param_int2,omitempty"`
	ParamInt3     int64                  `protobuf:"varint,105,opt,name=param_int3,json=paramInt3,proto3" json:"param_int3,omitempty"`
	ParamInt4     int64                  `protobuf:"varint,106,opt,name=param_int4,json=paramInt4,proto3" json:"param_int4,omitempty"`
	ParamInt5     int64                  `protobuf:"varint,107,opt,name=param_int5,json=paramInt5,proto3" json:"param_int5,omitempty"`
	ParamStr6     string                 `protobuf:"bytes,108,opt,name=param_str6,json=paramStr6,proto3" json:"param_str6,omitempty"`
	ParamStr7     string                 `protobuf:"bytes,109,opt,name=param_str7,json=paramStr7,proto3" json:"param_str7,omitempty"`
	ParamStr8     string                 `protobuf:"bytes,110,opt,name=param_str8,json=paramStr8,proto3" json:"param_str8,omitempty"`
	ParamStr9     string                 `protobuf:"bytes,111,opt,name=param_str9,json=paramStr9,proto3" json:"param_str9,omitempty"`
	ParamStr10    string                 `protobuf:"bytes,112,opt,name=param_str10,json=paramStr10,proto3" json:"param_str10,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientReportFlowRequest) Reset() {
	*x = ClientReportFlowRequest{}
	mi := &file_userpb_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientReportFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReportFlowRequest) ProtoMessage() {}

func (x *ClientReportFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReportFlowRequest.ProtoReflect.Descriptor instead.
func (*ClientReportFlowRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{18}
}

func (x *ClientReportFlowRequest) GetOsType() int32 {
	if x != nil {
		return x.OsType
	}
	return 0
}

func (x *ClientReportFlowRequest) GetPlatFromType() int32 {
	if x != nil {
		return x.PlatFromType
	}
	return 0
}

func (x *ClientReportFlowRequest) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *ClientReportFlowRequest) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ClientReportFlowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientReportFlowRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *ClientReportFlowRequest) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ClientReportFlowRequest) GetFlowType() int64 {
	if x != nil {
		return x.FlowType
	}
	return 0
}

func (x *ClientReportFlowRequest) GetFlowTypeStr() string {
	if x != nil {
		return x.FlowTypeStr
	}
	return ""
}

func (x *ClientReportFlowRequest) GetParamInt1() int64 {
	if x != nil {
		return x.ParamInt1
	}
	return 0
}

func (x *ClientReportFlowRequest) GetParamInt2() int64 {
	if x != nil {
		return x.ParamInt2
	}
	return 0
}

func (x *ClientReportFlowRequest) GetParamInt3() int64 {
	if x != nil {
		return x.ParamInt3
	}
	return 0
}

func (x *ClientReportFlowRequest) GetParamInt4() int64 {
	if x != nil {
		return x.ParamInt4
	}
	return 0
}

func (x *ClientReportFlowRequest) GetParamInt5() int64 {
	if x != nil {
		return x.ParamInt5
	}
	return 0
}

func (x *ClientReportFlowRequest) GetParamStr6() string {
	if x != nil {
		return x.ParamStr6
	}
	return ""
}

func (x *ClientReportFlowRequest) GetParamStr7() string {
	if x != nil {
		return x.ParamStr7
	}
	return ""
}

func (x *ClientReportFlowRequest) GetParamStr8() string {
	if x != nil {
		return x.ParamStr8
	}
	return ""
}

func (x *ClientReportFlowRequest) GetParamStr9() string {
	if x != nil {
		return x.ParamStr9
	}
	return ""
}

func (x *ClientReportFlowRequest) GetParamStr10() string {
	if x != nil {
		return x.ParamStr10
	}
	return ""
}

type ClientReportFlowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientReportFlowReply) Reset() {
	*x = ClientReportFlowReply{}
	mi := &file_userpb_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientReportFlowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReportFlowReply) ProtoMessage() {}

func (x *ClientReportFlowReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReportFlowReply.ProtoReflect.Descriptor instead.
func (*ClientReportFlowReply) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{19}
}

type BatchClientReportFlowRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Requests      []*ClientReportFlowRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchClientReportFlowRequest) Reset() {
	*x = BatchClientReportFlowRequest{}
	mi := &file_userpb_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchClientReportFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClientReportFlowRequest) ProtoMessage() {}

func (x *BatchClientReportFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClientReportFlowRequest.ProtoReflect.Descriptor instead.
func (*BatchClientReportFlowRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{20}
}

func (x *BatchClientReportFlowRequest) GetRequests() []*ClientReportFlowRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchClientReportFlowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailCount     int32                  `protobuf:"varint,2,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchClientReportFlowReply) Reset() {
	*x = BatchClientReportFlowReply{}
	mi := &file_userpb_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchClientReportFlowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClientReportFlowReply) ProtoMessage() {}

func (x *BatchClientReportFlowReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClientReportFlowReply.ProtoReflect.Descriptor instead.
func (*BatchClientReportFlowReply) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{21}
}

func (x *BatchClientReportFlowReply) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchClientReportFlowReply) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

type CommandNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandNotify) Reset() {
	*x = CommandNotify{}
	mi := &file_userpb_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandNotify) ProtoMessage() {}

func (x *CommandNotify) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandNotify.ProtoReflect.Descriptor instead.
func (*CommandNotify) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{22}
}

func (x *CommandNotify) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CommandNotify) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ReportRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReportedGid      int64                  `protobuf:"varint,1,opt,name=reported_gid,json=reportedGid,proto3" json:"reported_gid,omitempty"`
	ReportCategory   int32                  `protobuf:"varint,2,opt,name=report_category,json=reportCategory,proto3" json:"report_category,omitempty"`
	ReportScene      int32                  `protobuf:"varint,4,opt,name=report_scene,json=reportScene,proto3" json:"report_scene,omitempty"`
	ReportDesc       string                 `protobuf:"bytes,5,opt,name=report_desc,json=reportDesc,proto3" json:"report_desc,omitempty"`
	ReportContent    string                 `protobuf:"bytes,6,opt,name=report_content,json=reportContent,proto3" json:"report_content,omitempty"`
	ReportGroupId    string                 `protobuf:"bytes,10,opt,name=report_group_id,json=reportGroupId,proto3" json:"report_group_id,omitempty"`
	ReportGroupName  string                 `protobuf:"bytes,11,opt,name=report_group_name,json=reportGroupName,proto3" json:"report_group_name,omitempty"`
	ReportBattleId   string                 `protobuf:"bytes,12,opt,name=report_battle_id,json=reportBattleId,proto3" json:"report_battle_id,omitempty"`
	ReportBattleTime int64                  `protobuf:"varint,13,opt,name=report_battle_time,json=reportBattleTime,proto3" json:"report_battle_time,omitempty"`
	ReportEntrance   int32                  `protobuf:"varint,14,opt,name=report_entrance,json=reportEntrance,proto3" json:"report_entrance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_userpb_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{23}
}

func (x *ReportRequest) GetReportedGid() int64 {
	if x != nil {
		return x.ReportedGid
	}
	return 0
}

func (x *ReportRequest) GetReportCategory() int32 {
	if x != nil {
		return x.ReportCategory
	}
	return 0
}

func (x *ReportRequest) GetReportScene() int32 {
	if x != nil {
		return x.ReportScene
	}
	return 0
}

func (x *ReportRequest) GetReportDesc() string {
	if x != nil {
		return x.ReportDesc
	}
	return ""
}

func (x *ReportRequest) GetReportContent() string {
	if x != nil {
		return x.ReportContent
	}
	return ""
}

func (x *ReportRequest) GetReportGroupId() string {
	if x != nil {
		return x.ReportGroupId
	}
	return ""
}

func (x *ReportRequest) GetReportGroupName() string {
	if x != nil {
		return x.ReportGroupName
	}
	return ""
}

func (x *ReportRequest) GetReportBattleId() string {
	if x != nil {
		return x.ReportBattleId
	}
	return ""
}

func (x *ReportRequest) GetReportBattleTime() int64 {
	if x != nil {
		return x.ReportBattleTime
	}
	return 0
}

func (x *ReportRequest) GetReportEntrance() int32 {
	if x != nil {
		return x.ReportEntrance
	}
	return 0
}

type ReportReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportReply) Reset() {
	*x = ReportReply{}
	mi := &file_userpb_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportReply) ProtoMessage() {}

func (x *ReportReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportReply.ProtoReflect.Descriptor instead.
func (*ReportReply) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{24}
}

func (x *ReportReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ReportReply) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CertId        string                 `protobuf:"bytes,2,opt,name=cert_id,json=certId,proto3" json:"cert_id,omitempty"`
	CertType      int32                  `protobuf:"varint,3,opt,name=cert_type,json=certType,proto3" json:"cert_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_userpb_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteAccountRequest) GetCertId() string {
	if x != nil {
		return x.CertId
	}
	return ""
}

func (x *DeleteAccountRequest) GetCertType() int32 {
	if x != nil {
		return x.CertType
	}
	return 0
}

type DeleteAccountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountReply) Reset() {
	*x = DeleteAccountReply{}
	mi := &file_userpb_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountReply) ProtoMessage() {}

func (x *DeleteAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountReply.ProtoReflect.Descriptor instead.
func (*DeleteAccountReply) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteAccountReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteAccountReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SetQQFriendRecommendAuthorizedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    int64                  `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetQQFriendRecommendAuthorizedRequest) Reset() {
	*x = SetQQFriendRecommendAuthorizedRequest{}
	mi := &file_userpb_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetQQFriendRecommendAuthorizedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQQFriendRecommendAuthorizedRequest) ProtoMessage() {}

func (x *SetQQFriendRecommendAuthorizedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQQFriendRecommendAuthorizedRequest.ProtoReflect.Descriptor instead.
func (*SetQQFriendRecommendAuthorizedRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{27}
}

func (x *SetQQFriendRecommendAuthorizedRequest) GetAuthorized() int64 {
	if x != nil {
		return x.Authorized
	}
	return 0
}

type SetQQFriendRecommendAuthorizedReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    int64                  `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetQQFriendRecommendAuthorizedReply) Reset() {
	*x = SetQQFriendRecommendAuthorizedReply{}
	mi := &file_userpb_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetQQFriendRecommendAuthorizedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQQFriendRecommendAuthorizedReply) ProtoMessage() {}

func (x *SetQQFriendRecommendAuthorizedReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQQFriendRecommendAuthorizedReply.ProtoReflect.Descriptor instead.
func (*SetQQFriendRecommendAuthorizedReply) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{28}
}

func (x *SetQQFriendRecommendAuthorizedReply) GetAuthorized() int64 {
	if x != nil {
		return x.Authorized
	}
	return 0
}

type UserSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisableNudge  bool                   `protobuf:"varint,1,opt,name=disable_nudge,json=disableNudge,proto3" json:"disable_nudge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	mi := &file_userpb_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{29}
}

func (x *UserSettings) GetDisableNudge() bool {
	if x != nil {
		return x.DisableNudge
	}
	return false
}

type SetUserSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisableNudge  bool                   `protobuf:"varint,1,opt,name=disable_nudge,json=disableNudge,proto3" json:"disable_nudge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserSettingsRequest) Reset() {
	*x = SetUserSettingsRequest{}
	mi := &file_userpb_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserSettingsRequest) ProtoMessage() {}

func (x *SetUserSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserSettingsRequest.ProtoReflect.Descriptor instead.
func (*SetUserSettingsRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{30}
}

func (x *SetUserSettingsRequest) GetDisableNudge() bool {
	if x != nil {
		return x.DisableNudge
	}
	return false
}

type SetUserSettingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserSettingsReply) Reset() {
	*x = SetUserSettingsReply{}
	mi := &file_userpb_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserSettingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserSettingsReply) ProtoMessage() {}

func (x *SetUserSettingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserSettingsReply.ProtoReflect.Descriptor instead.
func (*SetUserSettingsReply) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{31}
}

type GetUserSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingsRequest) Reset() {
	*x = GetUserSettingsRequest{}
	mi := &file_userpb_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingsRequest) ProtoMessage() {}

func (x *GetUserSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSettingsRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{32}
}

type GetUserSettingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *UserSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingsReply) Reset() {
	*x = GetUserSettingsReply{}
	mi := &file_userpb_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingsReply) ProtoMessage() {}

func (x *GetUserSettingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingsReply.ProtoReflect.Descriptor instead.
func (*GetUserSettingsReply) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{33}
}

func (x *GetUserSettingsReply) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type BatchGetBasicInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gids          []int64                `protobuf:"varint,1,rep,packed,name=gids,proto3" json:"gids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetBasicInfoRequest) Reset() {
	*x = BatchGetBasicInfoRequest{}
	mi := &file_userpb_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetBasicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetBasicInfoRequest) ProtoMessage() {}

func (x *BatchGetBasicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetBasicInfoRequest.ProtoReflect.Descriptor instead.
func (*BatchGetBasicInfoRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{34}
}

func (x *BatchGetBasicInfoRequest) GetGids() []int64 {
	if x != nil {
		return x.Gids
	}
	return nil
}

type BatchGetBasicInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basics        []*BasicInfo           `protobuf:"bytes,1,rep,name=basics,proto3" json:"basics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetBasicInfoReply) Reset() {
	*x = BatchGetBasicInfoReply{}
	mi := &file_userpb_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetBasicInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetBasicInfoReply) ProtoMessage() {}

func (x *BatchGetBasicInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetBasicInfoReply.ProtoReflect.Descriptor instead.
func (*BatchGetBasicInfoReply) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{35}
}

func (x *BatchGetBasicInfoReply) GetBasics() []*BasicInfo {
	if x != nil {
		return x.Basics
	}
	return nil
}

var File_userpb_user_proto protoreflect.FileDescriptor

const file_userpb_user_proto_rawDesc = "" +
	"\n" +
	"\x11userpb/user.proto\x12\rgamepb.userpb\"\x86\x02\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\tsharer_id\x18\x03 \x01(\x03R\bsharerId\x12$\n" +
	"\x0esharer_open_id\x18\x04 \x01(\tR\fsharerOpenId\x12:\n" +
	"\vdevice_info\x18\x05 \x01(\v2\x19.gamepb.userpb.DeviceInfoR\n" +
	"deviceInfo\x12 \n" +
	"\fshare_cfg_id\x18\x06 \x01(\x03R\n" +
	"shareCfgId\x12\x19\n" +
	"\bscene_id\x18\a \x01(\tR\asceneId\x12:\n" +
	"\vreport_data\x18\b \x01(\v2\x19.gamepb.userpb.ReportDataR\n" +
	"reportData\"\xd9\x03\n" +
	"\n" +
	"DeviceInfo\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\x12!\n" +
	"\fsys_software\x18\x02 \x01(\tR\vsysSoftware\x12!\n" +
	"\fsys_hardware\x18\x03 \x01(\tR\vsysHardware\x12!\n" +
	"\ftelecom_oper\x18\x04 \x01(\tR\vtelecomOper\x12\x18\n" +
	"\anetwork\x18\x05 \x01(\tR\anetwork\x12!\n" +
	"\fscreen_width\x18\x06 \x01(\x03R\vscreenWidth\x12#\n" +
	"\rscreen_height\x18\a \x01(\x03R\fscreenHeight\x12\x18\n" +
	"\adensity\x18\b \x01(\x02R\adensity\x12\x10\n" +
	"\x03cpu\x18\t \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\n" +
	" \x01(\x03R\x06memory\x12\x1b\n" +
	"\tgl_render\x18\v \x01(\tR\bglRender\x12\x1d\n" +
	"\n" +
	"gl_version\x18\f \x01(\tR\tglVersion\x12\x1b\n" +
	"\tdevice_id\x18\r \x01(\tR\bdeviceId\x12!\n" +
	"\fandroid_oaid\x18\x0e \x01(\tR\vandroidOaid\x12\x19\n" +
	"\bios_caid\x18\x0f \x01(\tR\aiosCaid\"\x8d\x02\n" +
	"\n" +
	"ReportData\x12\x1a\n" +
	"\bcallback\x18\x01 \x01(\tR\bcallback\x12$\n" +
	"\x0ecd_extend_info\x18\x02 \x01(\tR\fcdExtendInfo\x12\x19\n" +
	"\bclick_id\x18\x03 \x01(\tR\aclickId\x12\x1d\n" +
	"\n" +
	"clue_token\x18\x04 \x01(\tR\tclueToken\x12)\n" +
	"\x10minigame_channel\x18\x05 \x01(\tR\x0fminigameChannel\x12'\n" +
	"\x0fminigame_platid\x18\x06 \x01(\x05R\x0eminigamePlatid\x12\x15\n" +
	"\x06req_id\x18\a \x01(\tR\x05reqId\x12\x18\n" +
	"\atrackid\x18\b \x01(\tR\atrackid\"\xd0\x02\n" +
	"\n" +
	"LoginReply\x12.\n" +
	"\x05basic\x18\x01 \x01(\v2\x18.gamepb.userpb.BasicInfoR\x05basic\x12&\n" +
	"\x0ftime_now_millis\x18\x03 \x01(\x03R\rtimeNowMillis\x12$\n" +
	"\x0eis_first_login\x18\x04 \x01(\bR\fisFirstLogin\x12@\n" +
	"\x0eqq_group_infos\x18\x06 \x03(\v2\x1a.gamepb.userpb.QQGroupInfoR\fqqGroupInfos\x12=\n" +
	"\fversion_info\x18\t \x01(\v2\x1a.gamepb.userpb.VersionInfoR\vversionInfo\x12C\n" +
	"\x1eqq_friend_recommend_authorized\x18\v \x01(\x03R\x1bqqFriendRecommendAuthorized\"\xc5\x02\n" +
	"\tBasicInfo\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\x03R\x03gid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x03R\x05level\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12\x12\n" +
	"\x04gold\x18\x05 \x01(\x03R\x04gold\x12\x17\n" +
	"\aopen_id\x18\x06 \x01(\tR\x06openId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark\x12\x1c\n" +
	"\tsignature\x18\t \x01(\tR\tsignature\x12\x16\n" +
	"\x06gender\x18\n" +
	" \x01(\x05R\x06gender\x12+\n" +
	"\x11authorized_status\x18\r \x01(\x05R\x10authorizedStatus\x12#\n" +
	"\rdisable_nudge\x18\x0e \x01(\bR\fdisableNudge\"Q\n" +
	"\vQQGroupInfo\x12\x1e\n" +
	"\vqq_group_id\x18\x01 \x01(\tR\tqqGroupId\x12\"\n" +
	"\rqq_group_name\x18\x02 \x01(\tR\vqqGroupName\"\x98\x01\n" +
	"\vVersionInfo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12+\n" +
	"\x11version_recommend\x18\x02 \x01(\tR\x10versionRecommend\x12#\n" +
	"\rversion_force\x18\x03 \x01(\tR\fversionForce\x12\x1f\n" +
	"\vres_version\x18\x04 \x01(\tR\n" +
	"resVersion\"K\n" +
	"\x10HeartbeatRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\x03R\x03gid\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\"p\n" +
	"\x0eHeartbeatReply\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\x12=\n" +
	"\fversion_info\x18\x02 \x01(\v2\x1a.gamepb.userpb.VersionInfoR\vversionInfo\"%\n" +
	"\n" +
	"FriendInfo\x12\x17\n" +
	"\aopen_id\x18\x01 \x01(\tR\x06openId\"\"\n" +
	"\tQQVipInfo\x12\x15\n" +
	"\x06is_vip\x18\x01 \x01(\bR\x05isVip\"\x98\x01\n" +
	"\x15SetDisplayInfoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tR\tavatarUrl\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\"\x96\x01\n" +
	"\x13SetDisplayInfoReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tR\tavatarUrl\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\"\x97\x01\n" +
	"\x15ReportArkClickRequest\x12\x1b\n" +
	"\tsharer_id\x18\x01 \x01(\x03R\bsharerId\x12$\n" +
	"\x0esharer_open_id\x18\x02 \x01(\tR\fsharerOpenId\x12\x19\n" +
	"\bscene_id\x18\x03 \x01(\tR\asceneId\x12 \n" +
	"\fshare_cfg_id\x18\x04 \x01(\x03R\n" +
	"shareCfgId\"\x15\n" +
	"\x13ReportArkClickReply\"=\n" +
	"\vBasicNotify\x12.\n" +
	"\x05basic\x18\x01 \x01(\v2\x18.gamepb.userpb.BasicInfoR\x05basic\"'\n" +
	"\rLogoutRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\r\n" +
	"\vLogoutReply\"\xb8\x04\n" +
	"\x17ClientReportFlowRequest\x12\x17\n" +
	"\aos_type\x18\x01 \x01(\x05R\x06osType\x12$\n" +
	"\x0eplat_from_type\x18\x02 \x01(\x05R\fplatFromType\x12\x17\n" +
	"\aopen_id\x18\x03 \x01(\tR\x06openId\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\x03R\x03gid\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x10\n" +
	"\x03now\x18\x06 \x01(\x03R\x03now\x12\x14\n" +
	"\x05level\x18\a \x01(\x03R\x05level\x12\x1b\n" +
	"\tflow_type\x18e \x01(\x03R\bflowType\x12\"\n" +
	"\rflow_type_str\x18f \x01(\tR\vflowTypeStr\x12\x1d\n" +
	"\n" +
	"param_int1\x18g \x01(\x03R\tparamInt1\x12\x1d\n" +
	"\n" +
	"param_int2\x18h \x01(\x03R\tparamInt2\x12\x1d\n" +
	"\n" +
	"param_int3\x18i \x01(\x03R\tparamInt3\x12\x1d\n" +
	"\n" +
	"param_int4\x18j \x01(\x03R\tparamInt4\x12\x1d\n" +
	"\n" +
	"param_int5\x18k \x01(\x03R\tparamInt5\x12\x1d\n" +
	"\n" +
	"param_str6\x18l \x01(\tR\tparamStr6\x12\x1d\n" +
	"\n" +
	"param_str7\x18m \x01(\tR\tparamStr7\x12\x1d\n" +
	"\n" +
	"param_str8\x18n \x01(\tR\tparamStr8\x12\x1d\n" +
	"\n" +
	"param_str9\x18o \x01(\tR\tparamStr9\x12\x1f\n" +
	"\vparam_str10\x18p \x01(\tR\n" +
	"paramStr10\"\x17\n" +
	"\x15ClientReportFlowReply\"b\n" +
	"\x1cBatchClientReportFlowRequest\x12B\n" +
	"\brequests\x18\x01 \x03(\v2&.gamepb.userpb.ClientReportFlowRequestR\brequests\"`\n" +
	"\x1aBatchClientReportFlowReply\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\x02 \x01(\x05R\tfailCount\"7\n" +
	"\rCommandNotify\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"\x9b\x03\n" +
	"\rReportRequest\x12!\n" +
	"\freported_gid\x18\x01 \x01(\x03R\vreportedGid\x12'\n" +
	"\x0freport_category\x18\x02 \x01(\x05R\x0ereportCategory\x12!\n" +
	"\freport_scene\x18\x04 \x01(\x05R\vreportScene\x12\x1f\n" +
	"\vreport_desc\x18\x05 \x01(\tR\n" +
	"reportDesc\x12%\n" +
	"\x0ereport_content\x18\x06 \x01(\tR\rreportContent\x12&\n" +
	"\x0freport_group_id\x18\n" +
	" \x01(\tR\rreportGroupId\x12*\n" +
	"\x11report_group_name\x18\v \x01(\tR\x0freportGroupName\x12(\n" +
	"\x10report_battle_id\x18\f \x01(\tR\x0ereportBattleId\x12,\n" +
	"\x12report_battle_time\x18\r \x01(\x03R\x10reportBattleTime\x12'\n" +
	"\x0freport_entrance\x18\x0e \x01(\x05R\x0ereportEntrance\"T\n" +
	"\vReportReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"`\n" +
	"\x14DeleteAccountRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\acert_id\x18\x02 \x01(\tR\x06certId\x12\x1b\n" +
	"\tcert_type\x18\x03 \x01(\x05R\bcertType\"@\n" +
	"\x12DeleteAccountReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"G\n" +
	"%SetQQFriendRecommendAuthorizedRequest\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\x03R\n" +
	"authorized\"E\n" +
	"#SetQQFriendRecommendAuthorizedReply\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\x03R\n" +
	"authorized\"3\n" +
	"\fUserSettings\x12#\n" +
	"\rdisable_nudge\x18\x01 \x01(\bR\fdisableNudge\"=\n" +
	"\x16SetUserSettingsRequest\x12#\n" +
	"\rdisable_nudge\x18\x01 \x01(\bR\fdisableNudge\"\x16\n" +
	"\x14SetUserSettingsReply\"\x18\n" +
	"\x16GetUserSettingsRequest\"O\n" +
	"\x14GetUserSettingsReply\x127\n" +
	"\bsettings\x18\x01 \x01(\v2\x1b.gamepb.userpb.UserSettingsR\bsettings\".\n" +
	"\x18BatchGetBasicInfoRequest\x12\x12\n" +
	"\x04gids\x18\x01 \x03(\x03R\x04gids\"J\n" +
	"\x16BatchGetBasicInfoReply\x120\n" +
	"\x06basics\x18\x01 \x03(\v2\x18.gamepb.userpb.BasicInfoR\x06basics*c\n" +
	"\rVersionStatus\x12\x1a\n" +
	"\x16VERSION_STATUS_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18VERSION_STATUS_RECOMMEND\x10\x01\x12\x18\n" +
	"\x14VERSION_STATUS_FORCE\x10\x02*\xa1\x01\n" +
	"\bCertType\x12\x1b\n" +
	"\x17CERT_TYPE_CHINA_ID_CARD\x10\x00\x12 \n" +
	"\x1bCERT_TYPE_OVERSEAS_PASSPORT\x10\x9e\x03\x12\x1e\n" +
	"\x19CERT_TYPE_HK_MACAU_TAIWAN\x10\x84\x04\x12 \n" +
	"\x1bCERT_TYPE_FOREIGN_PERMANENT\x10\xa9\x04\x12\x14\n" +
	"\x0fCERT_TYPE_OTHER\x10\xab\x04B\x1aZ\x18qq-farm-bot/proto/userpbb\x06proto3"

var (
	file_userpb_user_proto_rawDescOnce sync.Once
	file_userpb_user_proto_rawDescData []byte
)

func file_userpb_user_proto_rawDescGZIP() []byte {
	file_userpb_user_proto_rawDescOnce.Do(func() {
		file_userpb_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userpb_user_proto_rawDesc), len(file_userpb_user_proto_rawDesc)))
	})
	return file_userpb_user_proto_rawDescData
}

var file_userpb_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_userpb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_userpb_user_proto_goTypes = []any{
	(VersionStatus)(0),                            // 0: gamepb.userpb.VersionStatus
	(CertType)(0),                                 // 1: gamepb.userpb.CertType
	(*LoginRequest)(nil),                          // 2: gamepb.userpb.LoginRequest
	(*DeviceInfo)(nil),                            // 3: gamepb.userpb.DeviceInfo
	(*ReportData)(nil),                            // 4: gamepb.userpb.ReportData
	(*LoginReply)(nil),                            // 5: gamepb.userpb.LoginReply
	(*BasicInfo)(nil),                             // 6: gamepb.userpb.BasicInfo
	(*QQGroupInfo)(nil),                           // 7: gamepb.userpb.QQGroupInfo
	(*VersionInfo)(nil),                           // 8: gamepb.userpb.VersionInfo
	(*HeartbeatRequest)(nil),                      // 9: gamepb.userpb.HeartbeatRequest
	(*HeartbeatReply)(nil),                        // 10: gamepb.userpb.HeartbeatReply
	(*FriendInfo)(nil),                            // 11: gamepb.userpb.FriendInfo
	(*QQVipInfo)(nil),                             // 12: gamepb.userpb.QQVipInfo
	(*SetDisplayInfoRequest)(nil),                 // 13: gamepb.userpb.SetDisplayInfoRequest
	(*SetDisplayInfoReply)(nil),                   // 14: gamepb.userpb.SetDisplayInfoReply
	(*ReportArkClickRequest)(nil),                 // 15: gamepb.userpb.ReportArkClickRequest
	(*ReportArkClickReply)(nil),                   // 16: gamepb.userpb.ReportArkClickReply
	(*BasicNotify)(nil),                           // 17: gamepb.userpb.BasicNotify
	(*LogoutRequest)(nil),                         // 18: gamepb.userpb.LogoutRequest
	(*LogoutReply)(nil),                           // 19: gamepb.userpb.LogoutReply
	(*ClientReportFlowRequest)(nil),               // 20: gamepb.userpb.ClientReportFlowRequest
	(*ClientReportFlowReply)(nil),                 // 21: gamepb.userpb.ClientReportFlowReply
	(*BatchClientReportFlowRequest)(nil),          // 22: gamepb.userpb.BatchClientReportFlowRequest
	(*BatchClientReportFlowReply)(nil),            // 23: gamepb.userpb.BatchClientReportFlowReply
	(*CommandNotify)(nil),                         // 24: gamepb.userpb.CommandNotify
	(*ReportRequest)(nil),                         // 25: gamepb.userpb.ReportRequest
	(*ReportReply)(nil),                           // 26: gamepb.userpb.ReportReply
	(*DeleteAccountRequest)(nil),                  // 27: gamepb.userpb.DeleteAccountRequest
	(*DeleteAccountReply)(nil),                    // 28: gamepb.userpb.DeleteAccountReply
	(*SetQQFriendRecommendAuthorizedRequest)(nil), // 29: gamepb.userpb.SetQQFriendRecommendAuthorizedRequest
	(*SetQQFriendRecommendAuthorizedReply)(nil),   // 30: gamepb.userpb.SetQQFriendRecommendAuthorizedReply
	(*UserSettings)(nil),                          // 31: gamepb.userpb.UserSettings
	(*SetUserSettingsRequest)(nil),                // 32: gamepb.userpb.SetUserSettingsRequest
	(*SetUserSettingsReply)(nil),                  // 33: gamepb.userpb.SetUserSettingsReply
	(*GetUserSettingsRequest)(nil),                // 34: gamepb.userpb.GetUserSettingsRequest
	(*GetUserSettingsReply)(nil),                  // 35: gamepb.userpb.GetUserSettingsReply
	(*BatchGetBasicInfoRequest)(nil),              // 36: gamepb.userpb.BatchGetBasicInfoRequest
	(*BatchGetBasicInfoReply)(nil),                // 37: gamepb.userpb.BatchGetBasicInfoReply
}
var file_userpb_user_proto_depIdxs = []int32{
	3,  // 0: gamepb.userpb.LoginRequest.device_info:type_name -> gamepb.userpb.DeviceInfo
	4,  // 1: gamepb.userpb.LoginRequest.report_data:type_name -> gamepb.userpb.ReportData
	6,  // 2: gamepb.userpb.LoginReply.basic:type_name -> gamepb.userpb.BasicInfo
	7,  // 3: gamepb.userpb.LoginReply.qq_group_infos:type_name -> gamepb.userpb.QQGroupInfo
	8,  // 4: gamepb.userpb.LoginReply.version_info:type_name -> gamepb.userpb.VersionInfo
	8,  // 5: gamepb.userpb.HeartbeatReply.version_info:type_name -> gamepb.userpb.VersionInfo
	6,  // 6: gamepb.userpb.BasicNotify.basic:type_name -> gamepb.userpb.BasicInfo
	20, // 7: gamepb.userpb.BatchClientReportFlowRequest.requests:type_name -> gamepb.userpb.ClientReportFlowRequest
	31, // 8: gamepb.userpb.GetUserSettingsReply.settings:type_name -> gamepb.userpb.UserSettings
	6,  // 9: gamepb.userpb.BatchGetBasicInfoReply.basics:type_name -> gamepb.userpb.BasicInfo
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_userpb_user_proto_init() }
func file_userpb_user_proto_init() {
	if File_userpb_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userpb_user_proto_rawDesc), len(file_userpb_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userpb_user_proto_goTypes,
		DependencyIndexes: file_userpb_user_proto_depIdxs,
		EnumInfos:         file_userpb_user_proto_enumTypes,
		MessageInfos:      file_userpb_user_proto_msgTypes,
	}.Build()
	File_userpb_user_proto = out.File
	file_userpb_user_proto_goTypes = nil
	file_userpb_user_proto_depIdxs = nil
}
